<?php

namespace app\modules\purchasinglog\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{
	
	public function actionBiayaGrader(){
		$model = new \app\models\TBiayaGraderDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TBiayaGraderDetail'];
				$model->tgl_awal = $form_params['TBiayaGraderDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TBiayaGraderDetail']['tgl_akhir'];
				$model->biaya_grader_kode = $form_params['TBiayaGraderDetail']['biaya_grader_kode'];
				$model->status = $form_params['TBiayaGraderDetail']['status'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('biayaGrader/index',['model'=>$model]);
	}
	public function actionBiayaGraderPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TBiayaGraderDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TBiayaGraderDetail'];
		$model->tgl_awal = !empty($_GET['TBiayaGraderDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBiayaGraderDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TBiayaGraderDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBiayaGraderDetail']['tgl_akhir']):"";
		$model->biaya_grader_kode = $_GET['TBiayaGraderDetail']['biaya_grader_kode'];
		$model->status = $_GET['TBiayaGraderDetail']['status'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Biaya Grader');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionKontraklog(){
		$model = new \app\models\TLogKontrak();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLogKontrak'];
				$model->tgl_awal = $form_params['TLogKontrak']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLogKontrak']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('kontraklog/index',['model'=>$model]);
	}
	public function actionKontraklogPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLogKontrak();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLogKontrak'];
		$model->tgl_awal = !empty($_GET['TLogKontrak']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogKontrak']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLogKontrak']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogKontrak']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Kontrak Log');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionMonitoringPembelianLog(){
		$model = new \app\models\TPengajuanPembelianlog();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TPengajuanPembelianlog'];
				$model->tgl_awal = $form_params['TPengajuanPembelianlog']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanPembelianlog']['tgl_akhir'];
				$model->suplier_id = $form_params['TPengajuanPembelianlog']['suplier_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('monitoringPembelianLog/index',['model'=>$model]);
	}
	public function actionMonitoringPembelianLogPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPengajuanPembelianlog();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanPembelianlog'];
		$model->tgl_awal = !empty($_GET['TPengajuanPembelianlog']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanPembelianlog']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPengajuanPembelianlog']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanPembelianlog']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TPengajuanPembelianlog']['suplier_id'];
		$paramprint['judul'] = Yii::t('app', 'Monitoring Pembelian Log');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionMonitoringPembelianLogDetail($id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\TPengajuanPembelianlog::findOne($id);
			$modMonitoring = \app\models\TMonitoringPembelianlog::find()->where("pengajuan_pembelianlog_id = ".$model->pengajuan_pembelianlog_id)->all();
			return $this->render('/laporan/monitoringPembelianLog/detailMonitoring',['model'=>$model,'modMonitoring'=>$modMonitoring]);
        }
    }
}
