<?php

namespace app\modules\purchasinglog\controllers;

use Yii;
use app\modules\logistik\controllers\SupplierController as DeltaBaseController;

class SupplierlogController extends DeltaBaseController{
	
    public $path_view = '@module_logistik/supplier/';
	public function actionIndex(){
		$model = new \app\models\MSuplier();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['MSuplier'];
				$model->suplier_nm = $form_params['MSuplier']['suplier_nm'];
				$model->suplier_nm_company = $form_params['MSuplier']['suplier_nm_company'];
				$model->suplier_almt = $form_params['MSuplier']['suplier_almt'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render($this->path_view.'index',['model'=>$model]);
	}
    
    public function actionPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MSuplier();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['MSuplier'];
		$model->suplier_nm = $_GET['MSuplier']['suplier_nm'];
		$model->suplier_nm_company = $_GET['MSuplier']['suplier_nm_company'];
		$model->suplier_almt = $_GET['MSuplier']['suplier_almt'];
		$paramprint['judul'] = Yii::t('app', 'Master Supplier');
		if($caraprint == 'PRINT'){
			return $this->renderPartial($this->path_view.'print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial($this->path_view.'print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
}
