<?php

namespace app\modules\tuk\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionDokumenPenjualan(){
		$model = new \app\models\TDokumenPenjualan();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualan'];
				$model->jenis_produk = $form_params['TDokumenPenjualan']['jenis_produk'];
				$model->tgl_awal = $form_params['TDokumenPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualan']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/dokumenPenjualan/index',['model'=>$model]);
	}
	
	public function actionDokumenPenjualanPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualan'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualan']['jenis_produk'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionDokumenDetail(){
		$model = new \app\models\TDokumenPenjualanDetail();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualanDetail'];
				$model->tgl_awal = $form_params['TDokumenPenjualanDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualanDetail']['tgl_akhir'];
				$model->jenis_produk = $form_params['TDokumenPenjualanDetail']['jenis_produk'];
				$model->cust_id = $form_params['TDokumenPenjualanDetail']['cust_id'];
				$model->dokumen_penjualan_id = $form_params['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/dokumenDetail/index',['model'=>$model]);
	}
	
	public function actionDokumenDetailPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualanDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualanDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualanDetail']['jenis_produk'];
		$model->cust_id = $_GET['TDokumenPenjualanDetail']['cust_id'];
		$model->dokumen_penjualan_id = $_GET['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPenerbitanDokumen(){
		$model = new \app\models\TDokumenPenjualan();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualan'];
				$model->tgl_awal = $form_params['TDokumenPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualan']['tgl_akhir'];
				$model->jenis_produk = $form_params['TDokumenPenjualan']['jenis_produk'];
				$model->cust_id = $form_params['TDokumenPenjualan']['cust_id'];
				$model->provinsi = $form_params['TDokumenPenjualan']['provinsi'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPenerbitanKoDt() ));
		}
		return $this->render('/laporan/penerbitanDokumen/index',['model'=>$model]);
	}
	
	public function actionPenerbitanDokumenPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualan'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualan']['jenis_produk'];
		$model->cust_id = $_GET['TDokumenPenjualan']['cust_id'];
		$model->provinsi = $_GET['TDokumenPenjualan']['provinsi'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
