<?php

namespace app\modules\gudang\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class AvailablestockprodukController extends DeltaBaseController
{
    
	public $defaultAction = 'index';
    
	public function actionIndex(){
        if(\Yii::$app->request->get('dt')=='table-master'){
			$param['table']= \app\models\HPersediaanProduk::tableName();
			$param['pk']= \app\models\HPersediaanProduk::primaryKey()[0];
			$param['column'] = [$param['table'].'.produk_id',
								'm_brg_produk.produk_group',
								'm_brg_produk.produk_kode',
								'm_brg_produk.produk_nama',
								'sum(in_qty_palet-out_qty_palet) AS palet',
								'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
								'in_qty_kecil_satuan',
								'sum(in_qty_m3-out_qty_m3) AS kubikasi',
								];
            $param['group'] = 'GROUP BY m_brg_produk.produk_group, '.$param['table'].'.produk_id, m_brg_produk.produk_kode, m_brg_produk.produk_nama, in_qty_kecil_satuan';
			$param['join']= ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id'];
			$param['having'] = "HAVING SUM(in_qty_palet-out_qty_palet) > 0";
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
		}
		return $this->render('index');
	}
	
	public function actionStockPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$param = Yii::$app->request->get('param');
		if(!empty($param)){
			$where = "WHERE m_brg_produk.produk_group ilike '%{$param}%' OR m_brg_produk.produk_kode ilike '%{$param}%' OR m_brg_produk.produk_nama ilike '%{$param}%'";
		}else{
			$where = "";
		}
		$sql = "SELECT h_persediaan_produk.produk_id,
					   m_brg_produk.produk_group,
					   m_brg_produk.produk_kode,
					   m_brg_produk.produk_nama,
					   m_brg_produk.produk_dimensi,
					   sum(in_qty_palet-out_qty_palet) AS palet,
					   sum(in_qty_kecil-out_qty_kecil) AS qty_kecil,
					   in_qty_kecil_satuan,
					   sum(in_qty_m3-out_qty_m3) AS kubikasi
				FROM h_persediaan_produk
				JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
				$where
				GROUP BY m_brg_produk.produk_group, h_persediaan_produk.produk_id, m_brg_produk.produk_kode, m_brg_produk.produk_nama, m_brg_produk.produk_dimensi, in_qty_kecil_satuan
				HAVING SUM(in_qty_palet-out_qty_palet) > 0
				";
		$model = \Yii::$app->db->createCommand($sql)->queryAll();
		$paramprint['judul'] = Yii::t('app', 'Laporan Ketersediaan Stock Produk Barang Jadi');
		$paramprint['judul2'] = "Per : ".\app\components\DeltaFormatter::formatDateTimeForUser(date('d/m/Y h:i:s'));
		if($caraprint == 'PRINT'){
			return $this->render('print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionProduklist($produk_id=null,$satuan_kecil=null){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-produk'){
				$param['table']= \app\models\HPersediaanProduk::tableName();
				$param['pk']= \app\models\HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									$param['table'].'.nomor_produksi',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'm_gudang.gudang_nm',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 '.$param['table'].'.nomor_produksi,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 m_gudang.gudang_nm,
									 in_qty_kecil_satuan
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi
								  JOIN m_gudang ON m_gudang.gudang_id = '.$param['table'].'.gudang_id'];
				if(!empty($produk_id)){
					$param['where'] = $param['table'].".produk_id = ".$produk_id;
				}
				if(!empty($produk_id) && !empty($satuan_kecil)){
					$param['where'] .= " AND in_qty_kecil_satuan = '$satuan_kecil'";
				}
				$param['having'] = "HAVING SUM(in_qty_kecil-out_qty_kecil) > 0";
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('produklist',['produk_id'=>$produk_id,'satuan_kecil'=>$satuan_kecil]);
        }
    }
	
	public function actionProdukListOnModal($tr_seq=null,$jns_produk=null,$notin=null){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-produk'){
				$notinpost = json_decode( Yii::$app->request->get('notin') );
				$notin = "";
				if(!empty($notinpost)){
					$notin = "AND h_persediaan_produk.nomor_produksi NOT IN(";
					foreach($notinpost as $i => $not){
						$notin .= "'$not'";
						if( ($i+1)!=(count($notinpost)) ){
							$notin .= ",";
						}
					}
					$notin .= ")";
				}
				$param['table']= \app\models\HPersediaanProduk::tableName();
				$param['pk']= \app\models\HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									$param['table'].'.nomor_produksi',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'm_gudang.gudang_nm',
									'sum(in_qty_palet-out_qty_palet) AS qty_palet',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									$param['table'].'.gudang_id',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									'.$param['table'].'.nomor_produksi,
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 m_gudang.gudang_nm,
									 in_qty_kecil_satuan,
									 '.$param['table'].'.gudang_id
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi
								  JOIN m_gudang ON m_gudang.gudang_id = '.$param['table'].'.gudang_id'];
				$param['where'] = "m_brg_produk.produk_group = '".$jns_produk."' ".$notin;
				$param['having'] = "HAVING SUM(in_qty_palet-out_qty_palet) > 0";
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('listOnModal',['tr_seq'=>$tr_seq,'jns_produk'=>$jns_produk,'notin'=>$notin]);
		}
	}
	
	public function actionCurrentStock(){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-produk'){
				$param['table']= \app\models\HPersediaanProduk::tableName();
				$param['pk']= \app\models\HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									$param['table'].'.nomor_produksi',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 '.$param['table'].'.nomor_produksi,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 in_qty_kecil_satuan
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi'];
				$param['having'] = "HAVING SUM(in_qty_kecil-out_qty_kecil) > 0";
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('currentstock');
        }
    }
	
}
