<?php

namespace app\modules\gudang\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionMutasiGudangLogistik(){
		$model = new \app\models\TMutasiGudanglogistik();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TMutasiGudanglogistik'];
				$model->tgl_awal = $form_params['TMutasiGudanglogistik']['tgl_awal'];
				$model->tgl_akhir = $form_params['TMutasiGudanglogistik']['tgl_akhir'];
				$model->bhp_nm = $form_params['TMutasiGudanglogistik']['bhp_nm'];
				$model->kode = $form_params['TMutasiGudanglogistik']['kode'];
				$model->departement_id = $form_params['TMutasiGudanglogistik']['departement_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/mutasigudanglogistik/index',['model'=>$model]);
	}
	
	public function actionMutasiGudangLogistikPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TMutasiGudanglogistik();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TMutasiGudanglogistik'];
		$model->tgl_awal = !empty($_GET['TMutasiGudanglogistik']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TMutasiGudanglogistik']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TMutasiGudanglogistik']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TMutasiGudanglogistik']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TMutasiGudanglogistik']['bhp_nm'];
		$model->kode = $_GET['TMutasiGudanglogistik']['kode'];
		$model->departement_id = $_GET['TMutasiGudanglogistik']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Mutasi Barang Gudang Logistik');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionStockProduk(){
		$model = new \app\models\HPersediaanProduk();
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->produk_nama = $form_params['HPersediaanProduk']['produk_nama'];
				$model->produk_group = $form_params['HPersediaanProduk']['produk_group'];
				$model->per_tanggal = $form_params['HPersediaanProduk']['per_tanggal'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/stockProduk/index',['model'=>$model]);
	}
	
	public function actionStockProdukPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->produk_nama = $_GET['HPersediaanProduk']['produk_nama'];
		$model->produk_group = $_GET['HPersediaanProduk']['produk_group'];
		$model->per_tanggal = $_GET['HPersediaanProduk']['per_tanggal'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Produk');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionStockPalet(){
		$model = new \app\models\HPersediaanProduk();
		$model->produk_group = 'Plywood';
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->nomor_produksi = isset($form_params['HPersediaanProduk']['nomor_produksi'])?$form_params['HPersediaanProduk']['nomor_produksi']:null;
				$model->produk_group = isset($form_params['HPersediaanProduk']['produk_group'])?$form_params['HPersediaanProduk']['produk_group']:null;
				$model->produk_nama = isset($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:null;
				$model->jenis_kayu = isset($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:null;
				$model->grade = isset($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:null;
				$model->glue = isset($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:null;
				$model->profil_kayu = isset($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:null;
				$model->per_tanggal = isset($form_params['HPersediaanProduk']['per_tanggal'])?$form_params['HPersediaanProduk']['per_tanggal']:null;
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPaletDt() ));
		}
		return $this->render('/laporan/stockPalet/index',['model'=>$model]);
	}
	
	public function actionStockPaletPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->nomor_produksi = isset($_GET['HPersediaanProduk']['nomor_produksi'])?$_GET['HPersediaanProduk']['nomor_produksi']:null;
		$model->produk_group = isset($_GET['HPersediaanProduk']['produk_group'])?$_GET['HPersediaanProduk']['produk_group']:null;
		$model->produk_nama = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		$model->jenis_kayu = isset($_GET['HPersediaanProduk']['jenis_kayu'])?$_GET['HPersediaanProduk']['jenis_kayu']:null;
		$model->grade = isset($_GET['HPersediaanProduk']['grade'])?$_GET['HPersediaanProduk']['grade']:null;
		$model->glue = isset($_GET['HPersediaanProduk']['glue'])?$_GET['HPersediaanProduk']['glue']:null;
		$model->profil_kayu = isset($_GET['HPersediaanProduk']['profil_kayu'])?$_GET['HPersediaanProduk']['profil_kayu']:null;
		$model->kondisi_kayu = isset($_GET['HPersediaanProduk']['kondisi_kayu'])?$_GET['HPersediaanProduk']['kondisi_kayu']:null;
		$model->per_tanggal = isset($_GET['HPersediaanProduk']['per_tanggal'])?$_GET['HPersediaanProduk']['per_tanggal']:null;
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Palet');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionProdukKeluar(){
		$model = new \app\models\HPersediaanProduk();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->tgl_awal = $form_params['HPersediaanProduk']['tgl_awal'];
				$model->tgl_akhir = $form_params['HPersediaanProduk']['tgl_akhir'];
				$model->nomor_produksi = $form_params['HPersediaanProduk']['nomor_produksi'];
				$model->reff_no = $form_params['HPersediaanProduk']['reff_no'];
				$model->cara_keluar = $form_params['HPersediaanProduk']['cara_keluar'];
				$model->produk_nama = $form_params['HPersediaanProduk']['produk_nama'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanProdukKeluarDt() ));
		}
		return $this->render('/laporan/produkKeluar/index',['model'=>$model]);
	}
	
	public function actionProdukKeluarPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->tgl_awal = !empty($_GET['HPersediaanProduk']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['HPersediaanProduk']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['HPersediaanProduk']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['HPersediaanProduk']['tgl_akhir']):"";
		$model->nomor_produksi = $_GET['HPersediaanProduk']['nomor_produksi'];
		$model->cara_keluar = $_GET['HPersediaanProduk']['cara_keluar'];
		$model->produk_nama = $_GET['HPersediaanProduk']['produk_nama'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Produk Keluar');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionDeadStock(){
		$model = new \app\models\HPersediaanProduk();
		$model->produk_group = "Plywood";
		if(\Yii::$app->request->isAjax){
			$data['html'] = '';
			$data['head'] = "";
			if((\Yii::$app->request->get('params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('params'),$form_params); $post = []; $where = [];
				$post['produk_group'] = !empty($form_params['HPersediaanProduk']['produk_group'])?$form_params['HPersediaanProduk']['produk_group']:"";
				$post['produk_nama'] = !empty($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:"";
				$post['jenis_kayu'] = !empty($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:"";
				$post['grade'] = !empty($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:"";
				$post['glue'] = !empty($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:"";
				$post['profil_kayu'] = !empty($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:"";
				$post['kondisi_kayu'] = !empty($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:"";
				$post['gudang_id'] = !empty($form_params['HPersediaanProduk']['gudang_id'])?$form_params['HPersediaanProduk']['gudang_id']:"";
				$post['produk_nama'] = !empty($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:"";
				if(count($post)>0){
					foreach($post as $ii => $w){
						if(!empty($w)){
							if($ii == "gudang_id"){
								$where[$ii] = "h_persediaan_produk.".$ii." = '".$w."'";
							}else{
								$where[$ii] = $ii." = '".$w."'";
							}
						}
					}
					$where = implode(" AND ", $where);
				}
				$sqlhead = "SELECT to_char(t_terima_ko.tanggal, 'YYYY-MM') AS periode, sum(in_qty_palet-out_qty_palet) AS palet, sum(in_qty_kecil-out_qty_kecil) AS pcs
							FROM h_persediaan_produk
							JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
							JOIN t_terima_ko ON t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
							WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
								".(!empty($where)?" AND ".$where:"")."
							GROUP BY 1
							HAVING SUM(in_qty_palet-out_qty_palet) > 0
							ORDER BY 1 DESC";
				$modHead = \Yii::$app->db->createCommand($sqlhead)->queryAll();
				if(!empty($modHead)){
					$data['head'] .= $this->renderPartial('/laporan/deadStock/_head',['modHead'=>$modHead]);
				}
				$sql = "SELECT h_persediaan_produk.produk_id, 
								m_brg_produk.produk_group, 
								m_brg_produk.produk_kode, 
								m_brg_produk.produk_nama, 
								m_brg_produk.produk_dimensi, 
								h_persediaan_produk.gudang_id,
								m_gudang.gudang_nm, 
								sum(in_qty_palet-out_qty_palet) AS palet, 
								sum(in_qty_kecil-out_qty_kecil) AS qty_kecil, 
								in_qty_kecil_satuan, 
								sum(in_qty_m3-out_qty_m3) AS kubikasi
						FROM h_persediaan_produk
						JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
						JOIN m_gudang ON m_gudang.gudang_id = h_persediaan_produk.gudang_id
						WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
							".(!empty($where)?" AND ".$where:"")."
						GROUP BY h_persediaan_produk.produk_id, 
								m_brg_produk.produk_group, 
								m_brg_produk.produk_kode, 
								m_brg_produk.produk_nama, 
								produk_dimensi, 
								h_persediaan_produk.gudang_id, 
								m_gudang.gudang_nm, 
								in_qty_kecil_satuan
						HAVING SUM(in_qty_palet-out_qty_palet) > 0
						ORDER BY h_persediaan_produk.produk_id ASC";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					foreach($mods as $i => $produk){
						$td = '';
						if(isset($modHead)){
							foreach($modHead as $ii => $head){
								$sql = "SELECT h_persediaan_produk.gudang_id, sum(in_qty_palet-out_qty_palet) AS palet, sum(in_qty_kecil-out_qty_kecil) AS qty_kecil FROM h_persediaan_produk 
										JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
										JOIN t_terima_ko on t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
										WHERE h_persediaan_produk.produk_id = {$produk['produk_id']} AND h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%' AND h_persediaan_produk.gudang_id = {$produk['gudang_id']}
											AND to_char(t_terima_ko.tanggal, 'YYYY-MM') = '{$head['periode']}'
										GROUP BY h_persediaan_produk.gudang_id
										HAVING SUM(in_qty_palet-out_qty_palet) > 0";
								$mod = Yii::$app->db->createCommand($sql)->queryOne();
								$td .= '<td class="td-detail kolom-'.$head['periode'].' detail-palet" style="text-align:right; font-size: 1.1rem; padding-right: 10px;">';
								$td .= (!empty($mod))?$mod['palet']:"-";
								$td .= '</td>';
								$td .= '<td class="td-detail kolom-'.$head['periode'].' detail-pcs" style="text-align:right; font-size: 1.1rem; border-right: solid 1px #999;">';
								$td .= (!empty($mod['qty_kecil']))?\app\components\DeltaFormatter::formatNumberForUserFloat($mod['qty_kecil']):"-";
								$td .= '</td>';
							}
						}
						$data['html'] .= $this->renderPartial('/laporan/deadStock/_item',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where,'td'=>$td]);
					}
					$data['html'] .= $this->renderPartial('/laporan/deadStock/_itemtotal',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where]);
				}
			}
			return $this->asJson($data);
		}
		return $this->render('/laporan/deadStock/index',['model'=>$model]);
	}
	
	public function actionDeadStockPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		
		
		$post['produk_group'] = isset($_GET['HPersediaanProduk']['produk_group'])?$_GET['HPersediaanProduk']['produk_group']:null;
		$post['produk_nama'] = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		$post['jenis_kayu'] = isset($_GET['HPersediaanProduk']['jenis_kayu'])?$_GET['HPersediaanProduk']['jenis_kayu']:null;
		$post['grade'] = isset($_GET['HPersediaanProduk']['grade'])?$_GET['HPersediaanProduk']['grade']:null;
		$post['glue'] = isset($_GET['HPersediaanProduk']['glue'])?$_GET['HPersediaanProduk']['glue']:null;
		$post['profil_kayu'] = isset($_GET['HPersediaanProduk']['profil_kayu'])?$_GET['HPersediaanProduk']['profil_kayu']:null;
		$post['kondisi_kayu'] = isset($_GET['HPersediaanProduk']['kondisi_kayu'])?$_GET['HPersediaanProduk']['kondisi_kayu']:null;
		$post['gudang_id'] = isset($_GET['HPersediaanProduk']['gudang_id'])?$_GET['HPersediaanProduk']['gudang_id']:null;
		$post['produk_nama'] = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		if(count($post)>0){
			foreach($post as $ii => $w){
				if(!empty($w)){
					if($ii == "gudang_id"){
						$where[$ii] = "h_persediaan_produk.".$ii." = '".$w."'";
					}else{
						$where[$ii] = $ii." = '".$w."'";
					}
				}
			}
			$where = implode(" AND ", $where);
		}
		$sqlhead = "SELECT to_char(t_terima_ko.tanggal, 'YYYY-MM') AS periode, sum(in_qty_palet-out_qty_palet) AS palet
					FROM h_persediaan_produk
					JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
					JOIN t_terima_ko ON t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
					WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
						".(!empty($where)?" AND ".$where:"")."
					GROUP BY 1
					HAVING SUM(in_qty_palet-out_qty_palet) > 0
					ORDER BY 1 DESC";
		$modHead = \Yii::$app->db->createCommand($sqlhead)->queryAll();
//		if(!empty($modHead)){
//			$data['head'] .= $this->renderPartial('/laporan/deadStock/_head',['modHead'=>$modHead]);
//		}
		$sql = "SELECT h_persediaan_produk.produk_id, 
						m_brg_produk.produk_group, 
						m_brg_produk.produk_kode, 
						m_brg_produk.produk_nama, 
						m_brg_produk.produk_dimensi, 
						h_persediaan_produk.gudang_id,
						m_gudang.gudang_nm, 
						sum(in_qty_palet-out_qty_palet) AS palet, 
						sum(in_qty_kecil-out_qty_kecil) AS qty_kecil, 
						in_qty_kecil_satuan, 
						sum(in_qty_m3-out_qty_m3) AS kubikasi
				FROM h_persediaan_produk
				JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
				JOIN m_gudang ON m_gudang.gudang_id = h_persediaan_produk.gudang_id
				WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
					".(!empty($where)?" AND ".$where:"")."
				GROUP BY h_persediaan_produk.produk_id, 
						m_brg_produk.produk_group, 
						m_brg_produk.produk_kode, 
						m_brg_produk.produk_nama, 
						produk_dimensi, 
						h_persediaan_produk.gudang_id, 
						m_gudang.gudang_nm, 
						in_qty_kecil_satuan
				HAVING SUM(in_qty_palet-out_qty_palet) > 0
				ORDER BY h_persediaan_produk.produk_id ASC";
		$mods = \Yii::$app->db->createCommand($sql)->queryAll();
//		if(count($mods)>0){
//			foreach($mods as $i => $produk){
//				$data['html'] .= $this->renderPartial('/laporan/deadStock/_item',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where]);
//			}
//		}
		
		$paramprint['judul'] = Yii::t('app', 'Laporan Umur Stock');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2(date('d/m/Y'));
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
		}
	}
}
