<?php

namespace app\modules\marketing\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionPenjualanHarian(){
		$model = new \app\models\TNotaPenjualan();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TNotaPenjualan'];
				$model->tgl_awal = $form_params['TNotaPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TNotaPenjualan']['tgl_akhir'];
				$model->jenis_produk = $form_params['TNotaPenjualan']['jenis_produk'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/penjualanHarian/index',['model'=>$model]);
	}
	
	public function actionPenjualanHarianPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TNotaPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TNotaPenjualan'];
		$model->tgl_awal = !empty($_GET['TNotaPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TNotaPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualan']['tgl_akhir']):"";
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal Harian');
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal');
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/penjualanHarian/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/penjualanHarian/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/penjualanHarian/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPenjualanLokalDetail(){
		$model = new \app\models\TNotaPenjualanDetail();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TNotaPenjualanDetail'];
				$model->tgl_awal = $form_params['TNotaPenjualanDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TNotaPenjualanDetail']['tgl_akhir'];
				$model->jenis_produk = $form_params['TNotaPenjualanDetail']['jenis_produk'];
				$model->cust_id = $form_params['TNotaPenjualanDetail']['cust_id'];
//				$model->kode = $form_params['TNotaPenjualanDetail']['kode'];
				$model->sales_id = $form_params['TNotaPenjualanDetail']['sales_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/penjualanLokalDetail/index',['model'=>$model]);
	}
	
	public function actionPenjualanLokalDetailPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TNotaPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TNotaPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TNotaPenjualanDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualanDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TNotaPenjualanDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualanDetail']['tgl_akhir']):"";
		$model->jenis_produk = !empty($_GET['TNotaPenjualanDetail']['jenis_produk'])?$_GET['TNotaPenjualanDetail']['jenis_produk']:"";
		$model->cust_id = !empty($_GET['TNotaPenjualanDetail']['cust_id'])?$_GET['TNotaPenjualanDetail']['cust_id']:"";
//		$model->kode = !empty($_GET['TNotaPenjualanDetail']['kode'])?$_GET['TNotaPenjualanDetail']['kode']:"";
		$model->sales_id = !empty($_GET['TNotaPenjualanDetail']['sales_id'])?$_GET['TNotaPenjualanDetail']['sales_id']:"";
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal Harian');
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal');
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/penjualanLokalDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/penjualanHarian/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/penjualanLokalDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
