<?php

namespace app\modules\kasir\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionPenerimaanNonTunai(){
		$model = new \app\models\TKasBesarNontunai();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKasBesarNontunai'];
				$model->tgl_awal = $form_params['TKasBesarNontunai']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKasBesarNontunai']['tgl_akhir'];
				$model->kode = $form_params['TKasBesarNontunai']['kode'];
				$model->keterangan = $form_params['TKasBesarNontunai']['keterangan'];
				$model->nama_customer = $form_params['TKasBesarNontunai']['nama_customer'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/penerimaanNonTunai/index',['model'=>$model]);
	}
	
	public function actionPenerimaanNonTunaiPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKasBesarNontunai();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKasBesarNontunai'];
		$model->tgl_awal = !empty($_GET['TKasBesarNontunai']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBesarNontunai']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKasBesarNontunai']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBesarNontunai']['tgl_akhir']):"";
		$model->kode = $_GET['TKasBesarNontunai']['kode'];
		$model->keterangan = $_GET['TKasBesarNontunai']['keterangan'];
		$model->nama_customer = $_GET['TKasBesarNontunai']['nama_customer'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Kasir Non-Tunai');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penerimaanNonTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penerimaanNonTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penerimaanNonTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPenerimaanPenjualanTunai(){
		$model = new \app\models\TKasBesar();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKasBesar'];
				$model->tgl_awal = $form_params['TKasBesar']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKasBesar']['tgl_akhir'];
				$model->no_tandaterima = $form_params['TKasBesar']['no_tandaterima'];
				$model->deskripsi = $form_params['TKasBesar']['deskripsi'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/penerimaanPenjualanTunai/index',['model'=>$model]);
	}
	
	public function actionPenerimaanPenjualanTunaiPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKasBesar();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKasBesar'];
		$model->tgl_awal = !empty($_GET['TKasBesar']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBesar']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKasBesar']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBesar']['tgl_akhir']):"";
		$model->no_tandaterima = $_GET['TKasBesar']['no_tandaterima'];
		$model->deskripsi = $_GET['TKasBesar']['deskripsi'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Tunai');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penerimaanPenjualanTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penerimaanPenjualanTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penerimaanPenjualanTunai/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionKasbonGantung(){
		$model = new \app\models\TKasBon();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKasBon'];
				$model->tgl_awal = $form_params['TKasBon']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKasBon']['tgl_akhir'];
				$model->kode = $form_params['TKasBon']['kode'];
				$model->penerima = $form_params['TKasBon']['penerima'];
				$model->deskripsi = $form_params['TKasBon']['deskripsi'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt("gantung") ));
		}
		return $this->render('/laporan/kasbonGantung/index',['model'=>$model]);
	}
	
	public function actionKasbonGantungPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKasBon();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKasBon'];
		$model->tgl_awal = !empty($_GET['TKasBon']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBon']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKasBon']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBon']['tgl_akhir']):"";
		$model->kode = $_GET['TKasBon']['kode'];
		$model->penerima = $_GET['TKasBon']['penerima'];
		$model->deskripsi = $_GET['TKasBon']['deskripsi'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Kasbon Gantung Kas Kecil');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kasbonGantung/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kasbonGantung/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kasbonGantung/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionKasbonRealisasi(){
		$model = new \app\models\TKasBon();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKasBon'];
				$model->tgl_awal = $form_params['TKasBon']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKasBon']['tgl_akhir'];
				$model->kode = $form_params['TKasBon']['kode'];
				$model->penerima = $form_params['TKasBon']['penerima'];
				$model->deskripsi = $form_params['TKasBon']['deskripsi'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt("realisasi") ));
		}
		return $this->render('/laporan/kasbonRealisasi/index',['model'=>$model]);
	}
	
	public function actionKasbonRealisasiPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKasBon();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKasBon'];
		$model->tgl_awal = !empty($_GET['TKasBon']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBon']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKasBon']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKasBon']['tgl_akhir']):"";
		$model->kode = $_GET['TKasBon']['kode'];
		$model->penerima = $_GET['TKasBon']['penerima'];
		$model->deskripsi = $_GET['TKasBon']['deskripsi'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Kasbon Terealisasi Kas Kecil');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kasbonRealisasi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kasbonRealisasi/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kasbonRealisasi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
        
        public function actionSaldokasbesar(){
		$model = new \app\models\TKasBesar();
		$model->tgl_awal = date('d/m/Y',strtotime("-10 day"));
		$model->tgl_akhir = date('d/m/Y');
                if(\Yii::$app->request->isAjax){
			if(isset($_POST['search'])){
				$data['html'] = "<tr><td colspan='6' style='text-align: center;'>". Yii::t('app', 'No Data Available'). "</td></tr>";
				$data['saldoakhir'] = 0;
				$form_params = [];
				parse_str($_POST['formdata'],$form_params);
				$tgl_awal = $form_params['TKasBesar']['tgl_awal']." 00:00:00";
				$tgl_akhir = $form_params['TKasBesar']['tgl_akhir']." 23:59:59";
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kasbesar.debit) AS debit, SUM(h_saldo_kasbesar.kredit) AS kredit FROM t_closing_kasir
						LEFT JOIN h_saldo_kasbesar ON h_saldo_kasbesar.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl_awal."' AND '".$tgl_akhir."' AND t_closing_kasir.tipe = 'KB'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC
					";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					$data['html'] = "";
					foreach($mods as $i => $detail){
						$data['html'] .= $this->renderPartial('_item',['detail'=>$detail,'i'=>$i,'totalrows'=>count($mods)]);
					}
					$data['saldoakhir'] = \app\models\HSaldoKasbesar::getSaldoAkhir();
				}
				return $this->asJson($data);
			}
		}
		return $this->render('/laporan/saldokasbesar/index',['model'=>$model]);
	}
        public function actionGetLaporanByTanggal($tgl){
		if(\Yii::$app->request->isAjax){
			if(!empty($tgl)){
				$awal = $tgl." 00:00:00";
				$akhir = $tgl." 23:59:59";
				$models = \app\models\HSaldoKasbesar::find()->where("tanggal BETWEEN '".$awal."' AND '".$akhir."' ")->orderBy('kode ASC')->all();
				if(count($models)>0){
					return $this->renderAjax('laporanbytgl',['models'=>$models]);
				}
			}
		}
	}
	
	public function actionPrintoutLaporan(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$model = \app\models\HSaldoKasbesar::find()->where(" tanggal = '".$tgl."' ")->orderBy('kode ASC')->all();
		$paramprint['judul'] = Yii::t('app', 'Laporan Kas Besar');
		$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser( substr($tgl, 0,10) );
		if($caraprint == 'PRINT'){
			return $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
        
    public function actionSaldokaskecil(){
        $model = new \app\models\TKasKecil();
		$model->tgl_awal = date('d/m/Y',strtotime("-10 day"));
		$model->tgl_akhir = date('d/m/Y');
	
		if(\Yii::$app->request->isAjax){
			if(isset($_POST['search'])){
				$data['html'] = "<tr><td colspan='6' style='text-align: center;'>". Yii::t('app', 'No Data Available'). "</td></tr>";
				$data['saldoakhir'] = 0;
				$form_params = [];
				parse_str($_POST['formdata'],$form_params);
				$tgl_awal = $form_params['TKasKecil']['tgl_awal']." 00:00:00";
				$tgl_akhir = $form_params['TKasKecil']['tgl_akhir']." 23:59:59";
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kaskecil.debit) AS debit, SUM(h_saldo_kaskecil.kredit) AS kredit FROM t_closing_kasir
						LEFT JOIN h_saldo_kaskecil ON h_saldo_kaskecil.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl_awal."' AND '".$tgl_akhir."' AND t_closing_kasir.tipe = 'KK'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC
						";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					$data['html'] = "";
					foreach($mods as $i => $detail){
						$data['html'] .= $this->renderPartial('_item',['detail'=>$detail,'i'=>$i,'totalrows'=>count($mods)]);
					}
					$data['saldoakhir'] = \app\models\HSaldoKaskecil::getSaldoAkhir();
				}
				return $this->asJson($data);
			}
		}		
		return $this->render('/laporan/saldokaskecil/index',['model'=>$model]);
	}

    public function actionSaldokaskecilxxx(){
        $model = new \app\models\TKasKecil();
		$model->tgl_awal = date('d/m/Y',strtotime("-10 day"));
		$model->tgl_akhir = date('d/m/Y');
	
		if(\Yii::$app->request->isAjax){
			if(isset($_POST['search'])){
				$data['html'] = "<tr><td colspan='6' style='text-align: center;'>". Yii::t('app', 'No Data Available'). "</td></tr>";
				$data['saldoakhir'] = 0;
				$form_params = [];
				parse_str($_POST['formdata'],$form_params);
				$tgl_awal = $form_params['TKasKecil']['tgl_awal']." 00:00:00";
				$tgl_akhir = $form_params['TKasKecil']['tgl_akhir']." 23:59:59";
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kaskecil.debit) AS debit, SUM(h_saldo_kaskecil.kredit) AS kredit FROM t_closing_kasir
						LEFT JOIN h_saldo_kaskecil ON h_saldo_kaskecil.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl_awal."' AND '".$tgl_akhir."' AND t_closing_kasir.tipe = 'KK'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC
						";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					$data['html'] = "";
					foreach($mods as $i => $detail){
						$data['html'] .= $this->renderPartial('saldokaskecil/_item',['detail'=>$detail,'i'=>$i,'totalrows'=>count($mods)]);
					}
					$data['saldoakhir'] = \app\models\HSaldoKaskecil::getSaldoAkhir();
				}
				return $this->asJson($data);
			}
		}		
		return $this->render('/laporan/saldokaskecil/index',['model'=>$model]);
	}

}
