<?php

namespace app\modules\kasir\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class SaldokasbesarController extends DeltaBaseController
{
	public $defaultAction = 'index';
	public function actionIndex(){
        $model = new \app\models\TKasBesar();
		$model->tgl_awal = date('d/m/Y',strtotime("-10 day"));
		$model->tgl_akhir = date('d/m/Y');
		
		if(\Yii::$app->request->isAjax){
			if(isset($_POST['search'])){
				$data['html'] = "<tr><td colspan='6' style='text-align: center;'>". Yii::t('app', 'No Data Available'). "</td></tr>";
				$data['saldoakhir'] = 0;
				$form_params = [];
				parse_str($_POST['formdata'],$form_params);
				$tgl_awal = $form_params['TKasBesar']['tgl_awal']." 00:00:00";
				$tgl_akhir = $form_params['TKasBesar']['tgl_akhir']." 23:59:59";
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kasbesar.debit) AS debit, SUM(h_saldo_kasbesar.kredit) AS kredit 
                        FROM t_closing_kasir
						LEFT JOIN h_saldo_kasbesar ON h_saldo_kasbesar.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl_awal."' AND '".$tgl_akhir."' AND t_closing_kasir.tipe = 'KB'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC
						";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					$data['html'] = "";
					foreach($mods as $i => $detail){
						$data['html'] .= $this->renderPartial('_item',['detail'=>$detail,'i'=>$i,'totalrows'=>count($mods)]);
					}
					$data['saldoakhir'] = \app\models\HSaldoKasbesar::getSaldoAkhir();
				}
				return $this->asJson($data);
			}
		}
		
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionGetLaporanByTanggal($tgl){
		if(\Yii::$app->request->isAjax){
			if(!empty($tgl)){
				$awal = $tgl." 00:00:00";
				$akhir = $tgl." 23:59:59";
				$models = \app\models\HSaldoKasbesar::find()->where("tanggal BETWEEN '".$awal."' AND '".$akhir."' ")->orderBy('kode ASC')->all();
				if(count($models)>0){
					return $this->renderAjax('laporanbytgl',['models'=>$models]);
				}
			}
		}
	}
	
	public function actionPrintoutLaporan(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$model = \app\models\HSaldoKasbesar::find()->where(" tanggal = '".$tgl."' ")->orderBy('kode ASC')->all();
		$paramprint['judul'] = Yii::t('app', 'Laporan Kas Besar');
		$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser( substr($tgl, 0,10) );
		if($caraprint == 'PRINT'){
			return $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
}
