<?php

namespace app\modules\purchasing\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{
	public function actionPersediaanBhp(){
		$model = new \app\models\HPersediaanBhp();
		$model->tgl_transaksi = date('d/m/Y');
		$model->available = TRUE;
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['HPersediaanBhp'];
				$model->bhp_nm = $form_params['HPersediaanBhp']['bhp_nm'];
				$model->bhp_group = $form_params['HPersediaanBhp']['bhp_group'];
				$model->available = $form_params['HPersediaanBhp']['available'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('persedianBhp/index',['model'=>$model]);
	}
	
	public function actionPersediaanBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->tgl_transaksi = (isset($_GET['HPersediaanBhp']['tgl_transaksi'])?$_GET['HPersediaanBhp']['tgl_transaksi']:"");
		$model->bhp_nm = (isset($_GET['HPersediaanBhp']['bhp_nm'])?$_GET['HPersediaanBhp']['bhp_nm']:"");
		$model->bhp_group = (isset($_GET['HPersediaanBhp']['bhp_group'])?$_GET['HPersediaanBhp']['bhp_group']:"");
		$model->available = (isset($_GET['HPersediaanBhp']['available'])?$_GET['HPersediaanBhp']['available']:"");
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Bahan Pembantu');
		if(!empty($model->tgl_transaksi)){
			$paramprint['judul2'] = "Per Tanggal ". \app\components\DeltaFormatter::formatDateTimeForDb($model->tgl_transaksi);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionSpp(){
		$model = new \app\models\TSppDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TSppDetail'];
				$model->tgl_awal = $form_params['TSppDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSppDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSppDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSppDetail']['bhp_group'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('spp/index',['model'=>$model]);
	}
	
	public function actionSppPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSppDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSppDetail'];
		$model->tgl_awal = !empty($_GET['TSppDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSppDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSppDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSppDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSppDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSppDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Permintaan Pembelian Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPoBhp(){
		$model = new \app\models\TSpoDetail();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TSpoDetail'];
				$model->tgl_awal = $form_params['TSpoDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSpoDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSpoDetail']['bhp_group'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('poBhp/index',['model'=>$model]);
	}
	
	public function actionPoBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSpoDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSpoDetail'];
		$model->tgl_awal = !empty($_GET['TSpoDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpoDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSpoDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpoDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSpoDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSpoDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan PO Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionTerimaBhp(){
		$model = new \app\models\TTerimaBhpDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TTerimaBhpDetail'];
				$model->tgl_awal = $form_params['TTerimaBhpDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TTerimaBhpDetail']['tgl_akhir'];
				$model->terimabhp_kode = $form_params['TTerimaBhpDetail']['terimabhp_kode'];
				$model->bhp_nm = $form_params['TTerimaBhpDetail']['bhp_nm'];
				$model->suplier_id = $form_params['TTerimaBhpDetail']['suplier_id'];
				$model->terimabhpd_keterangan = $form_params['TTerimaBhpDetail']['terimabhpd_keterangan'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('terimaBhp/index',['model'=>$model]);
	}
	public function actionTerimaBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhpDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhpDetail'];
		$model->tgl_awal = !empty($_GET['TTerimaBhpDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhpDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_akhir']):"";
		$model->terimabhp_kode = $_GET['TTerimaBhpDetail']['terimabhp_kode'];
		$model->bhp_nm = $_GET['TTerimaBhpDetail']['bhp_nm'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionBhpKeluar(){
            $model = new \app\models\TBpbDetail();
            $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
            $bpb_dept = \app\models\TBpb::find()->where(['departement_id'=>Yii::$app->user->identity->pegawai->departement_id])->all();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TBpbDetail'];
				$model->tgl_awal = $form_params['TBpbDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TBpbDetail']['tgl_akhir'];
				$model->bpb_kode = $form_params['TBpbDetail']['bpb_kode'];
				$model->bhp_nm = $form_params['TBpbDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TBpbDetail']['bhp_group'];
				$model->departement_id = $form_params['TBpbDetail']['departement_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
//		return $this->render('bhpKeluar/index',['model'=>$model]);
                return $this->render('bhpKeluar/index',['model'=>$model,'bpb_dept'=>$bpb_dept]);
	}
	public function actionBhpKeluarPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TBpbDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TBpbDetail'];
		$model->tgl_awal = !empty($_GET['TBpbDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBpbDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TBpbDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBpbDetail']['tgl_akhir']):"";
		$model->bpb_kode = $_GET['TBpbDetail']['bpb_kode'];
		$model->bhp_nm = $_GET['TBpbDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TBpbDetail']['bhp_group'];
		$model->departement_id = $_GET['TBpbDetail']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengeluaran Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionLoglist(){
		$model = new \app\models\TLoglistDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLoglistDetail'];
				$model->tgl_awal = $form_params['TLoglistDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLoglistDetail']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('loglist/index',['model'=>$model]);
	}
	public function actionLoglistPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLoglistDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLoglistDetail'];
		$model->tgl_awal = !empty($_GET['TLoglistDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLoglistDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Loglist');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPembayaranDp(){
		$model = new \app\models\TLogBayarDp();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLogBayarDp'];
				$model->tgl_awal = $form_params['TLogBayarDp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLogBayarDp']['tgl_akhir'];
				$model->nomor = $form_params['TLogBayarDp']['nomor'];
				$model->suplier_id = $form_params['TLogBayarDp']['suplier_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('pembayaranDp/index',['model'=>$model]);
	}
	public function actionPembayaranDpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLogBayarDp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLogBayarDp'];
		$model->tgl_awal = !empty($_GET['TLogBayarDp']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogBayarDp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLogBayarDp']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogBayarDp']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengajuan DP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionSpl(){
		$model = new \app\models\TSplDetail();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TSplDetail'];
				$model->tgl_awal = $form_params['TSplDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSplDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSplDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSplDetail']['bhp_group'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('spl/index',['model'=>$model]);
	}
	
	public function actionSplPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSplDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSplDetail'];
		$model->tgl_awal = !empty($_GET['TSplDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSplDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSplDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSplDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSplDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSplDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan PO Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionBhpTerbeli(){
		$model = new \app\models\TSpoDetail();
		$modSplDetail = new \app\models\TSplDetail();
		if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TSpoDetail'];
				$model->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchTotalBeliDt() ));
		}
		if(\Yii::$app->request->get('dt')=='table-laporan2'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$modSplDetail->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $modSplDetail->searchTotalBeliDt() ));
		}
		return $this->render('bhpTerbeli/index',['model'=>$model]);
	}
	
	public function actionBhpTerbeliPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSpoDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->bhp_nm = (isset($_GET['TSpoDetail']['bhp_nm'])?$_GET['TSpoDetail']['bhp_nm']:"");
		$paramprint['judul'] = Yii::t('app', 'Bahan Pembantu Terbeli');
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPengajuanTagihan(){
		$model = new \app\models\TPengajuanTagihan();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TPengajuanTagihan'];
				$model->tgl_awal = $form_params['TPengajuanTagihan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanTagihan']['tgl_akhir'];
				$model->suplier_id = $form_params['TPengajuanTagihan']['suplier_id'];
				$model->nomor_nota = $form_params['TPengajuanTagihan']['nomor_nota'];
				$model->jenis_pembelian = $form_params['TPengajuanTagihan']['jenis_pembelian'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('pengajuanTagihan/index',['model'=>$model]);
	}
	
	public function actionPengajuanTagihanPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPengajuanTagihan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanTagihan'];
		$model->tgl_awal = !empty($_GET['TPengajuanTagihan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanTagihan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPengajuanTagihan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanTagihan']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TPengajuanTagihan']['suplier_id'];
		$model->nomor_nota = $_GET['TPengajuanTagihan']['nomor_nota'];
		$model->jenis_pembelian = $_GET['TPengajuanTagihan']['jenis_pembelian'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengajuan Tagihan BHP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
