<?php

namespace app\modules\purchasing\controllers;

use app\components\DeltaFormatter;
use app\components\SSP;
use app\models\MBrgBhp;
use app\models\TmpSppSpoSplTbp;
use app\models\TSppDetail;
use app\models\MapSppDetailReff;
use Yii;
use app\controllers\DeltaBaseController;
use yii\db\Exception;
use yii\helpers\Json;

class LaporanController extends DeltaBaseController
{
	public function actionPersediaanBhp(){
		$model = new \app\models\HPersediaanBhp();
		$model->tgl_transaksi = date('d/m/Y');
		$model->available = TRUE;
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanBhp'];
				$model->bhp_nm = $form_params['HPersediaanBhp']['bhp_nm'];
				$model->bhp_group = $form_params['HPersediaanBhp']['bhp_group'];
				$model->available = $form_params['HPersediaanBhp']['available'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('persedianBhp/index',['model'=>$model]);
	}
	
	public function actionPersediaanBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\HPersediaanBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->tgl_transaksi = (isset($_GET['HPersediaanBhp']['tgl_transaksi'])?$_GET['HPersediaanBhp']['tgl_transaksi']:"");
		$model->bhp_nm = (isset($_GET['HPersediaanBhp']['bhp_nm'])?$_GET['HPersediaanBhp']['bhp_nm']:"");
		$model->bhp_group = (isset($_GET['HPersediaanBhp']['bhp_group'])?$_GET['HPersediaanBhp']['bhp_group']:"");
		$model->available = (isset($_GET['HPersediaanBhp']['available'])?$_GET['HPersediaanBhp']['available']:"");
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Bahan Pembantu');
		if(!empty($model->tgl_transaksi)){
			$paramprint['judul2'] = "Per Tanggal ". DeltaFormatter::formatDateTimeForDb($model->tgl_transaksi);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/persedianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionSpp(){
		$model = new TSppDetail();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TSppDetail'];
				$model->tgl_awal = $form_params['TSppDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSppDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSppDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSppDetail']['bhp_group'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('spp/index',['model'=>$model]);
	}
	
	public function actionInfo($id,$sppdid)
	{
		if (\Yii::$app->request->isAjax) {
			$model = \app\models\MapSppDetailReff::findOne(['reff_detail_id'=>$id,'sppd_id'=>$sppdid]);
			
			$ex = substr($model->reff_no, 0,3);			
			if($ex == "SPO"){				
				$modSPO = \app\models\TSpo::findOne(['spo_kode'=>$model->reff_no]);
				$modelDetail = \app\models\TSpoDetail::findOne(['spod_id'=>$id]);			
				$renData = $this->renderAjax('/laporan/monitoringSpp/infoSPO', ['spo_id'=>$modSPO->spo_id,'bhp_id' => $modelDetail->bhp_id, 'id' => $id, 'model' => $model]);
			}elseif($ex == "SPL"){
				$modSPL = \app\models\TSpl::findOne(['spl_kode'=>$model->reff_no]);
				$modelDetail = \app\models\TSplDetail::findOne(['spld_id'=>$id]);
				$renData = $this->renderAjax('/laporan/monitoringSpp/infoSPL', ['spl_id'=>$modSPL->spl_id,'bhp_id' => $modelDetail->bhp_id, 'id' => $id, 'model' => $model]);
			}
			return $renData ;
		}
	}

	public function actionInfoPenerimaan($id,$sppdid)
	{
		if (\Yii::$app->request->isAjax) {
			$model = \app\models\MapSppDetailReff::findOne(['terima_bhpd_id'=>$id,'sppd_id'=>$sppdid]);
			$modelTbpDetail = \app\models\TTerimaBhpDetail::findOne(['terima_bhpd_id'=>$id]);
			$modTbp = \app\models\TTerimaBhp::findOne(['terima_bhp_id'=>$modelTbpDetail->terima_bhp_id]);									
			$renData = $this->renderAjax('/laporan/monitoringSpp/infoTBP', ['terima_bhp_id'=>$modelTbpDetail->terima_bhp_id,'bhp_id' => $modelTbpDetail->bhp_id, 'id' => $id, 'model' => $model, 'modTbp'=>$modTbp]);			
			return $renData ;
		}
	}
	public function actionInfoSpb($id,$sppdid)
	{
		if (\Yii::$app->request->isAjax) {
			$modelDetail = \app\models\TSpbDetail::findOne(['spbd_id'=>$id]);
			$renData = $this->renderAjax('/laporan/monitoringSpp/infoSPB', ['id' => $id, 'sppdid' => $sppdid,'spb_id'=>$modelDetail->spb_id,'modelDetail'=>$modelDetail]);			
			return $renData ;
		}
	}
	public function actionInfoPenawaranBhp($id)
	{
		if (\Yii::$app->request->isAjax) {
			$model = \app\models\MapPenawaranBhp::findOne(['sppd_id'=>$id]);
			$renData = $this->renderAjax('/laporan/monitoringSpp/infoPenawaran', ['terima_bhp_id'=>$modelTbpDetail->terima_bhp_id,'bhp_id' => $modelTbpDetail->bhp_id, 'id' => $id, 'model' => $model, 'modTbp'=>$modTbp]);			
			return $renData ;
		}
	}
	public function actionSppPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TSppDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSppDetail'];
		$model->tgl_awal = !empty($_GET['TSppDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TSppDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSppDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TSppDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSppDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSppDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Permintaan Pembelian Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/spp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionMonitoringSpp(){
		$model = new TmpSppSpoSplTbp();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TmpSppSpoSplTbp'];
				$model->tgl_awal = $form_params['TmpSppSpoSplTbp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TmpSppSpoSplTbp']['tgl_akhir'];
				$model->bhp_nm = $form_params['TmpSppSpoSplTbp']['bhp_nm'];
				$model->bhp_group = $form_params['TmpSppSpoSplTbp']['bhp_group'];
				$model->status_closed = $form_params['TmpSppSpoSplTbp']['status_closed'];
				$model->status_pembelian = $form_params['TmpSppSpoSplTbp']['status_pembelian'];
				$model->spp_kode = $form_params['TmpSppSpoSplTbp']['spp_kode'];
				$model->status_pemenuhan = $form_params['TmpSppSpoSplTbp']['status_pemenuhan'];
				$model->suplier_id = $form_params['TmpSppSpoSplTbp']['suplier_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('monitoringSpp/index',['model'=>$model]);
	}
	
	public function actionMonitoringSppPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TmpSppSpoSplTbp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TmpSppSpoSplTbp'];
		$model->tgl_awal = !empty($_GET['TmpSppSpoSplTbp']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TmpSppSpoSplTbp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TmpSppSpoSplTbp']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TmpSppSpoSplTbp']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TmpSppSpoSplTbp']['bhp_nm'];
		$model->bhp_group = $_GET['TmpSppSpoSplTbp']['bhp_group'];
		$model->status_closed = $_GET['TmpSppSpoSplTbp']['status_closed'];
		$model->status_pembelian = $_GET['TmpSppSpoSplTbp']['status_pembelian'];
		$model->spp_kode = $_GET['TmpSppSpoSplTbp']['spp_kode'];	
		$model->status_pemenuhan = $_GET['TmpSppSpoSplTbp']['status_pemenuhan'];	
		$model->suplier_id = $_GET['TmpSppSpoSplTbp']['suplier_id'];
		$paramprint['judul'] = Yii::t('app', 'Monitoring Permintaan Pembelian Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/monitoringSpp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/monitoringSpp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/monitoringSpp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionPoBhp(){
		$model = new \app\models\TSpoDetail();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TSpoDetail'];
				$model->tgl_awal = $form_params['TSpoDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSpoDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSpoDetail']['bhp_group'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('poBhp/index',['model'=>$model]);
	}
	
	public function actionPoBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSpoDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSpoDetail'];
		$model->tgl_awal = !empty($_GET['TSpoDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TSpoDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSpoDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TSpoDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSpoDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSpoDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan PO Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/poBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionTerimaBhp(){
		$model = new \app\models\ViewTerimaBhpDetail();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['ViewTerimaBhpDetail'];
				$model->tgl_awal = $form_params['ViewTerimaBhpDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['ViewTerimaBhpDetail']['tgl_akhir'];
				$model->terimabhp_kode = $form_params['ViewTerimaBhpDetail']['terimabhp_kode'];
				$model->bhp_nm = $form_params['ViewTerimaBhpDetail']['bhp_nm'];
				$model->suplier_id = $form_params['ViewTerimaBhpDetail']['suplier_id'];
				$model->terimabhpd_keterangan = $form_params['ViewTerimaBhpDetail']['terimabhpd_keterangan'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('terimaBhp/index',['model'=>$model]);
	}

    public function actionTerimaBhpTotal()
    {
        $model = new \app\models\ViewTerimaBhpDetail();
        $param = Yii::$app->request->get('ViewTerimaBhpDetail');
        $model->attributes              = $param;
        $model->tgl_awal                = $param['tgl_awal'];
        $model->tgl_akhir               = $param['tgl_akhir'];
        $model->terimabhp_kode          = $param['terimabhp_kode'];
        $model->bhp_nm                  = $param['bhp_nm'];
        $model->suplier_id              = $param['suplier_id'];
        $model->terimabhpd_keterangan   = $param['terimabhpd_keterangan'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
            // $total += $row['total'];
			$total += ($row['terimabhpd_qty'] * $row['terimabhpd_harga']) + $row['ppn'] + $row['pph_peritem'] + $row['total_pbbkb'];
        }
        return Json::encode(['total' => $total]);
    }

	public function actionTerimaBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\ViewTerimaBhpDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['ViewTerimaBhpDetail'];
		$model->tgl_awal = !empty($_GET['ViewTerimaBhpDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['ViewTerimaBhpDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['ViewTerimaBhpDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['ViewTerimaBhpDetail']['tgl_akhir']):"";
		$model->terimabhp_kode = $_GET['ViewTerimaBhpDetail']['terimabhp_kode'];
		$model->bhp_nm = $_GET['ViewTerimaBhpDetail']['bhp_nm'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/terimaBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	// 2020-09-10 /cis/web/purchasing/laporan/TerimaBhpFilterNoFaktur
	public function actionTerimaBhpFilterNoFaktur(){
		$model = new \app\models\TTerimaBhp();
        if(Yii::$app->request->get('dt') == 'table-laporan'){
			$form_params = []; 
			parse_str(Yii::$app->request->get('laporan_params'),$form_params);
			/*$periode = $form_params['periode'];
            $periode == '' ? $periode = 30 : $periode = $periode;*/
            $model->tgl_awal = $form_params['TTerimaBhp']['tgl_awal'];
            $model->tgl_akhir = $form_params['TTerimaBhp']['tgl_akhir'];
            $model->suplier_id = $form_params['TTerimaBhp']['suplier_id'];
            $tgl_awal = $model->tgl_awal;
            $tgl_akhir = $model->tgl_akhir;
            $suplier_id = $model->suplier_id;
			return Json::encode(SSP::complex( $model->searchLaporanFilterNoFakturDt($tgl_awal, $tgl_akhir, $suplier_id) ));
		}
		return $this->render('terimaBhpFilterNoFaktur/index',['model'=>$model]);
    }
    
    // 2021-01-12 /cis/web/purchasing/laporan/TerimaBhpFilterNoFakturPrint
	public function actionTerimaBhpFilterNoFakturPrint(){
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\TTerimaBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->tgl_awal = !empty($_GET['TTerimaBhp']['tgl_awal']) ? DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_awal']) : "";
        $model->tgl_akhir = !empty($_GET['TTerimaBhp']['tgl_akhir']) ? DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_akhir']) : "";
        $model->suplier_id = !empty($_GET['TTerimaBhp']['suplier_id']) ? $_GET['TTerimaBhp']['suplier_id'] : "";
        $tgl_awal = $model->tgl_awal;
        $tgl_akhir = $model->tgl_akhir;
        $suplier_id = $model->suplier_id;
        $paramprint['judul'] = Yii::t('app', 'Faktur Pajak Belum Diterima');
        
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
        }
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/terimaBhpFilterNoFaktur/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir,'suplier_id'=>$suplier_id]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.' || Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/terimaBhpFilterNoFaktur/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir,'suplier_id'=>$suplier_id]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/terimaBhpFilterNoFaktur/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir,'suplier_id'=>$suplier_id]);
        }
	}

	public function actionBhpKeluar(){
            $model = new \app\models\TBpbDetail();
            $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
            $bpb_dept = \app\models\TBpb::find()->where(['departement_id'=>Yii::$app->user->identity->pegawai->departement_id])->all();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TBpbDetail'];
				$model->tgl_awal = $form_params['TBpbDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TBpbDetail']['tgl_akhir'];
				$model->bpb_kode = $form_params['TBpbDetail']['bpb_kode'];
				$model->bhp_nm = $form_params['TBpbDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TBpbDetail']['bhp_group'];
				$model->departement_id = $form_params['TBpbDetail']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
//		return $this->render('bhpKeluar/index',['model'=>$model]);
                return $this->render('bhpKeluar/index',['model'=>$model,'bpb_dept'=>$bpb_dept]);
	}
	public function actionBhpKeluarPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TBpbDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TBpbDetail'];
		$model->tgl_awal = !empty($_GET['TBpbDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TBpbDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TBpbDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TBpbDetail']['tgl_akhir']):"";
		$model->bpb_kode = $_GET['TBpbDetail']['bpb_kode'];
		$model->bhp_nm = $_GET['TBpbDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TBpbDetail']['bhp_group'];
		$model->departement_id = $_GET['TBpbDetail']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengeluaran Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/bhpKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionLoglist(){
		$model = new \app\models\TLoglistDetail();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TLoglistDetail'];
				$model->tgl_awal = $form_params['TLoglistDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLoglistDetail']['tgl_akhir'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('loglist/index',['model'=>$model]);
	}
	public function actionLoglistPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLoglistDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLoglistDetail'];
		$model->tgl_awal = !empty($_GET['TLoglistDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLoglistDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Loglist');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/loglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPembayaranDp(){
		$model = new \app\models\TLogBayarDp();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TLogBayarDp'];
				$model->tgl_awal = $form_params['TLogBayarDp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLogBayarDp']['tgl_akhir'];
				$model->nomor = $form_params['TLogBayarDp']['nomor'];
				$model->suplier_id = $form_params['TLogBayarDp']['suplier_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('pembayaranDp/index',['model'=>$model]);
	}
	public function actionPembayaranDpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLogBayarDp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLogBayarDp'];
		$model->tgl_awal = !empty($_GET['TLogBayarDp']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TLogBayarDp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLogBayarDp']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TLogBayarDp']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengajuan DP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pembayaranDp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionSpl(){
		$model = new \app\models\TSplDetail();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TSplDetail'];
				$model->tgl_awal = $form_params['TSplDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TSplDetail']['tgl_akhir'];
				$model->bhp_nm = $form_params['TSplDetail']['bhp_nm'];
				$model->bhp_group = $form_params['TSplDetail']['bhp_group'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('spl/index',['model'=>$model]);
	}
	
	public function actionSplPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSplDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TSplDetail'];
		$model->tgl_awal = !empty($_GET['TSplDetail']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TSplDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TSplDetail']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TSplDetail']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TSplDetail']['bhp_nm'];
		$model->bhp_group = $_GET['TSplDetail']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Laporan PO Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/spl/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionBhpTerbeli(){
		$model = new \app\models\TSpoDetail();
		$modSplDetail = new \app\models\TSplDetail();
		if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TSpoDetail'];
				$model->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
			}
			return Json::encode(SSP::complex( $model->searchTotalBeliDt() ));
		}
		if(Yii::$app->request->get('dt')=='table-laporan2'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$modSplDetail->bhp_nm = $form_params['TSpoDetail']['bhp_nm'];
			}
			return Json::encode(SSP::complex( $modSplDetail->searchTotalBeliDt() ));
		}
		return $this->render('bhpTerbeli/index',['model'=>$model]);
	}
	
	public function actionBhpTerbeliPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TSpoDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->bhp_nm = (isset($_GET['TSpoDetail']['bhp_nm'])?$_GET['TSpoDetail']['bhp_nm']:"");
		$paramprint['judul'] = Yii::t('app', 'Bahan Pembantu Terbeli');
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/bhpTerbeli/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPengajuanTagihan(){
		$model = new \app\models\TPengajuanTagihan();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TPengajuanTagihan'];
				$model->tgl_awal = $form_params['TPengajuanTagihan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanTagihan']['tgl_akhir'];
				$model->suplier_id = $form_params['TPengajuanTagihan']['suplier_id'];
				$model->nomor_nota = $form_params['TPengajuanTagihan']['nomor_nota'];
				$model->jenis_pembelian = $form_params['TPengajuanTagihan']['jenis_pembelian'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('pengajuanTagihan/index',['model'=>$model]);
	}
	
	public function actionPengajuanTagihanPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPengajuanTagihan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanTagihan'];
		$model->tgl_awal = !empty($_GET['TPengajuanTagihan']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanTagihan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPengajuanTagihan']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanTagihan']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TPengajuanTagihan']['suplier_id'];
		$model->nomor_nota = $_GET['TPengajuanTagihan']['nomor_nota'];
		$model->jenis_pembelian = $_GET['TPengajuanTagihan']['jenis_pembelian'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengajuan Tagihan BHP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pengajuanTagihan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	// fungsi menampilkan modal info
    public function actionPoBhpInfo($spod_id){
		if(Yii::$app->request->isAjax){
			$spod_id = $spod_id;
			$spo_id = Yii::$app->db->createCommand('select spo_id from t_spo_detail where spod_id = '.$spod_id)->queryScalar();
			$t_spo = \app\models\TSpo::find()->where('spo_id = '.$spo_id)->one();
			$supplier_id = Yii::$app->db->createCommand('select suplier_id from t_spo where spo_id = '.$spo_id)->queryScalar();
			$map_penawaran_bhp = \app\models\MapPenawaranBhp::find()->where('spod_id = '.$spod_id.'')->orderBy('penawaran_bhp_id asc')->all();
            return $this->renderAjax('/laporan/poBhp/info',['spod_id'=>$spod_id, 'supplier_id'=>$supplier_id, 't_spo'=>$t_spo, 'map_penawaran_bhp'=>$map_penawaran_bhp]);
		}
	}

    /**
     * @return string
     */
    public function actionSppinprogress(){
        $model              = new TSppDetail();
        $model->tgl_awal    = date('01/m/Y');

        if(Yii::$app->request->get('dt') === 'table-laporan'){
            if((Yii::$app->request->get('laporan_params')) !== null){
                $form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
                $filter = $form_params['TSppDetail'];
            }

            $param['table']     = TSppDetail::tableName();
            $param['pk']        = $param['table'].'.'.TSppDetail::primaryKey()[0];
            $param['column']    = [
                't_spp_detail.sppd_id',
                't_spp.spp_tanggal',
                't_spp.spp_kode',
                'm_brg_bhp.bhp_nm',
                't_spp_detail.sppd_qty',
                'm_brg_bhp.bhp_satuan',
                't_spp_detail.sppd_ket',
                'm_suplier.suplier_nm',
                'm_departement.departement_nama',
                't_spp_detail.bhp_id'
            ];
            $param['join']      = [
                'INNER JOIN t_spp ON t_spp_detail.spp_id = t_spp.spp_id',
                'INNER JOIN m_brg_bhp ON m_brg_bhp.bhp_id = t_spp_detail.bhp_id',
                'INNER JOIN m_departement ON t_spp.departement_id = m_departement.departement_id',
                'INNER JOIN m_suplier ON t_spp_detail.suplier_id = m_suplier.suplier_id'
            ];

            $param['where']     = [
                't_spp_detail.status_closed IS NULL ',
                't_spp_detail.sppd_id NOT IN ( SELECT map_spp_detail_reff.sppd_id FROM map_spp_detail_reff WHERE map_spp_detail_reff.terima_bhpd_id IS NOT NULL ) ',
                't_spp.cancel_transaksi_id IS NULL '
            ];

            if(isset($filter['tgl_awal'], $filter['tgl_akhir']) && !empty($filter['tgl_awal']) && !empty($filter['tgl_akhir'])) {
                $param['where'][] = "t_spp.spp_tanggal BETWEEN '{$filter['tgl_awal']}' AND '{$filter['tgl_akhir']}' ";
            }

            if(isset($filter['bhp_nm']) && !empty($filter['bhp_nm'])) {
                $param['where'][] = "m_brg_bhp.bhp_nm ILIKE '%{$filter['bhp_nm']}%' ";
            }

            if(isset($filter['bhp_group']) && !empty($filter['bhp_group'])) {
                $param['where'][] = "m_brg_bhp.bhp_group = '{$filter['bhp_group']}' ";
            }

            if(isset($filter['suplier_id']) && !empty($filter['suplier_id'])) {
                $param['where'][] = "t_spp_detail.suplier_id = {$filter['suplier_id']} ";
            }

            return Json::encode(SSP::complex( $param ));
        }
        return $this->render('sppinprogress/index', compact('model'));
    }

    /**
     * @param $bhp_id
     * @return string|void
     * @throws Exception
     */
    public function actionTrackterimabybhp($bhp_id)
    {
        if(isset($bhp_id)) {
            $sql = "
                SELECT COALESCE
                    ( t_spo.spo_tanggal, t_spl.spl_tanggal ) reff_tanggal,
                    COALESCE ( t_spo.spo_kode, t_spl.spl_kode ) reff_kode,
                    COALESCE ( t_spo_detail.spod_qty, t_spl_detail.spld_qty ) reff_qty,
                    t_terima_bhp.tglterima,
                    t_terima_bhp.terimabhp_kode,
                    t_terima_bhp_detail.terimabhpd_qty,
                    map_spp_detail_reff.sppd_id 
                FROM
                    t_terima_bhp_detail
                    INNER JOIN t_terima_bhp ON t_terima_bhp.terima_bhp_id = t_terima_bhp_detail.terima_bhp_id
                    LEFT JOIN map_spp_detail_reff ON t_terima_bhp_detail.terima_bhpd_id = map_spp_detail_reff.terima_bhpd_id
                    LEFT JOIN t_spo ON t_spo.spo_kode = map_spp_detail_reff.reff_no
                    LEFT JOIN t_spo_detail ON t_spo_detail.spod_id = map_spp_detail_reff.reff_detail_id
                    LEFT JOIN t_spl ON t_spl.spl_kode = map_spp_detail_reff.reff_no
                    LEFT JOIN t_spl_detail ON t_spl_detail.spld_id = map_spp_detail_reff.reff_detail_id 
                WHERE
                    t_terima_bhp_detail.bhp_id = $bhp_id
                ORDER BY
                    t_terima_bhp.tglterima
            ";
            $model  = Yii::$app->db->createCommand($sql)->queryAll();
            $bhp    = MBrgBhp::findOne($bhp_id);
            return $this->renderAjax('sppinprogress/tracking', compact('model', 'bhp'));
        }
    }
	public function actionSuplier(){
		$model = new \app\models\MSuplier();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['MSuplier'];
				$model->tgl_awal = $form_params['MSuplier']['tgl_awal'];
				$model->tgl_akhir = $form_params['MSuplier']['tgl_akhir'];
				$model->suplier_nm = $form_params['MSuplier']['suplier_nm'];
				$model->type = $form_params['MSuplier']['type'];
				$model->suplier_nm_company = $form_params['MSuplier']['suplier_nm_company'];
				$model->suplier_almt = $form_params['MSuplier']['suplier_almt'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDtSuplier() ));
		}
		return $this->render('suplier/index',['model'=>$model]);
	}

	public function actionSuplierPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MSuplier();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['MSuplier'];
		$model->tgl_awal = !empty($_GET['MSuplier']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['MSuplier']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['MSuplier']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['MSuplier']['tgl_akhir']):"";
		$model->suplier_nm = $_GET['MSuplier']['suplier_nm'];
		$model->type = $_GET['MSuplier']['type'];
		$model->suplier_nm_company = $_GET['MSuplier']['suplier_nm_company'];
		$model->suplier_almt = $_GET['MSuplier']['suplier_almt'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Suplier');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/suplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/suplier/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/suplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
