<?php

namespace app\modules\kasir\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class RekapkasbesarController extends DeltaBaseController
{
	public $defaultAction = 'index';
	public function actionIndex(){
        $model = new \app\models\TKasBesar();
		$model->tanggal = date('d/m/Y');
		if(\Yii::$app->request->isAjax){
			if(isset($_POST['getItems'])){
				$tgl = \app\components\DeltaFormatter::formatDateTimeForDb($_POST['tgl']);
				$data = [];
				$data['saldoawal'] = \app\models\HSaldoKasbesar::getSaldoAwal($tgl);
				$data['saldoakhir'] = \app\models\HSaldoKasbesar::getSaldoAkhir($tgl);
				
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kasbesar.debit) AS debit, SUM(h_saldo_kasbesar.kredit) AS kredit FROM t_closing_kasir
						LEFT JOIN h_saldo_kasbesar ON h_saldo_kasbesar.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl." 00:00:00' AND '".$tgl." 23:59:59' AND t_closing_kasir.tipe = 'KB'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC";
				$mods = \Yii::$app->db->createCommand($sql)->queryOne();
				$sql2 = "SELECT SUM(nominal) AS totalbon FROM h_bonsementara WHERE tanggal = '".$tgl."' AND tipe = 'KB' GROUP BY tanggal";
				$mods2 = \Yii::$app->db->createCommand($sql2)->queryOne();
				$sql3 = "SELECT SUM(subtotal) AS totaluangtunai FROM t_uangtunai WHERE tanggal = '".$tgl."' AND tipe = 'KB' GROUP BY tanggal";
				$mods3 = \Yii::$app->db->createCommand($sql3)->queryOne();
				
				$hasilpenjualan = $mods['debit'];
				$masuklain = 0;
				$setorbank = $mods['kredit'];
				$bonsementara = $mods2['totalbon'];
				$keluarlain = 0;
				$uangtunai = $mods3['totaluangtunai'];
				
				$data['hasilpenjualan'] = $hasilpenjualan;
				$data['masuklain'] = $masuklain;
				$data['totalmasuk'] = $hasilpenjualan + $masuklain;
				$data['setorbank'] = $setorbank;
				$data['bonsementara'] = $bonsementara;
				$data['totalkeluar'] = $setorbank + $bonsementara + $keluarlain;
				$data['uangtunai'] = $uangtunai;
				if(!empty($mods['tanggal'])){
					$data['statusclosing'] = 1;
				}else{
					$data['statusclosing'] = 0;
				}
				
				return $this->asJson($data);
			}
		}
		
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionRekap($tgl){
		if(\Yii::$app->request->isAjax){
			$tgl = Yii::$app->request->get('tgl');
			$info = Yii::$app->request->get('info');
			if($info=='uangtunai'){
				$model = new \app\models\TUangtunai();
				if(!empty($model)){
					return $this->renderAjax('uangtunai',['model'=>$model,'tgl'=>$tgl,'info'=>true]);
				}
			}
			if($info=='kasbon'){
				$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KB'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
				if(!empty($models)){
					return $this->renderAjax('kasbon',['models'=>$models,'tgl'=>$tgl]);
				}
			}
			return false;
		}
	}
	public function actionPrintrekap($tgl){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$info = Yii::$app->request->get('info');
		if($info=='uangtunai'){
			$model = new \app\models\TUangtunai();
			if(!empty($model)){
				return $this->renderAjax('uangtunai',['model'=>$model,'tgl'=>$tgl,'info'=>true]);
			}
		}
		if($info=='kasbon'){
			$paramprint['judul'] = Yii::t('app', 'Laporan Kasbon Sementara');
			$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
			$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KB'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
			if(!empty($models)){
				if($caraprint == 'PRINT'){
					return $this->renderAjax('printkasbon',['models'=>$models,'tgl'=>$tgl,'paramprint'=>$paramprint]);
				}else if($caraprint == 'PDF'){
					$pdf = Yii::$app->pdf;
					$pdf->options = ['title' => $paramprint['judul']];
					$pdf->filename = $paramprint['judul'].'.pdf';
					$pdf->mode = \kartik\mpdf\Pdf::MODE_UTF8;
					$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
					$pdf->content = $this->renderPartial('printkasbon',['models'=>$models,'paramprint'=>$paramprint]);
					return $pdf->render();
				}else if($caraprint == 'EXCEL'){
					return $this->renderPartial('printkasbon',['models'=>$models,'paramprint'=>$paramprint]);
				}
			}
		}
		return false;
	}
	
	public function actionPrintoutLaporan(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$model = \app\models\HSaldoKasbesar::find()->where(" tanggal = '".$tgl."' ")->orderBy('kode ASC')->all();
		$paramprint['judul'] = Yii::t('app', 'Laporan Kas Besar');
		$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser( substr($tgl, 0,10) );
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/saldokasbesar/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionTanggalSelisihClosing(){
		if(\Yii::$app->request->isAjax){
			$sql = "SELECT t_kas_besar.tanggal AS tgl_Laporan, h_saldo_kasbesar.created_at::DATE AS tgl_Closing, (h_saldo_kasbesar.created_at::DATE - t_kas_besar.tanggal) AS selisih_hari FROM t_kas_besar 
					JOIN h_saldo_kasbesar ON h_saldo_kasbesar.kode = t_kas_besar.kode
					WHERE t_kas_besar.tanggal != h_saldo_kasbesar.created_at::DATE
					GROUP BY t_kas_besar.tanggal, h_saldo_kasbesar.created_at::DATE
					ORDER BY t_kas_besar.tanggal DESC";
			$models = Yii::$app->db->createCommand($sql)->queryAll();
			return $this->renderAjax('tanggalselisihclosing',['models'=>$models]);
		}
	}
}
