<?php

namespace app\modules\kasir\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class RekapkaskecilController extends DeltaBaseController
{
	public $defaultAction = 'index';
	public function actionIndex(){
        $model = new \app\models\TKasKecil();
		$model->tanggal = date('d/m/Y');
		if(\Yii::$app->request->isAjax){
			if(isset($_POST['getItems'])){
				$tgl = \app\components\DeltaFormatter::formatDateTimeForDb($_POST['tgl']);
				$data = [];
				$data['saldoawal'] = \app\models\HSaldoKaskecil::getSaldoAwal($tgl);
				$data['saldoakhir'] = \app\models\HSaldoKaskecil::getSaldoAkhir($tgl);
				
				$sql = "SELECT t_closing_kasir.tanggal::date, SUM(h_saldo_kaskecil.debit) AS debit, SUM(h_saldo_kaskecil.kredit) AS kredit FROM t_closing_kasir
						LEFT JOIN h_saldo_kaskecil ON h_saldo_kaskecil.tanggal::date = t_closing_kasir.tanggal::date
						WHERE t_closing_kasir.tanggal BETWEEN '".$tgl." 00:00:00' AND '".$tgl." 23:59:59' AND t_closing_kasir.tipe = 'KK'
						GROUP BY t_closing_kasir.tanggal::date ORDER BY t_closing_kasir.tanggal::date ASC";
				$mods = \Yii::$app->db->createCommand($sql)->queryOne();
				$sql2 = "SELECT SUM(nominal) AS totalbon FROM h_bonsementara WHERE tanggal = '".$tgl."' AND tipe = 'KK' GROUP BY tanggal";
				$mods2 = \Yii::$app->db->createCommand($sql2)->queryOne();
				$sql3 = "SELECT SUM(subtotal) AS totaluangtunai FROM t_uangtunai WHERE tanggal = '".$tgl."' AND tipe = 'KK' GROUP BY tanggal";
				$mods3 = \Yii::$app->db->createCommand($sql3)->queryOne();
				$sql4 = "SELECT SUM(nominal) AS bonkasbesar FROM h_bonsementara WHERE tanggal = '".$tgl."' AND tipe = 'KB' AND status = 'KASBON KASBESAR KE KASKECIL' GROUP BY tanggal";
				$mods4 = \Yii::$app->db->createCommand($sql4)->queryOne();
				
				$penambahankas = $mods['debit'];
				$masuklain = 0;
				$operasional = $mods['kredit'];
				$bonsementara = $mods2['totalbon'];
				$keluarlain = 0;
				$uangtunai = $mods3['totaluangtunai'];
				$bonkasbesar = $mods4['bonkasbesar'];
				
				$data['penambahankas'] = $penambahankas;
				$data['masuklain'] = $masuklain;
				$data['totalmasuk'] = $penambahankas + $masuklain;
				$data['operasional'] = $operasional;
				$data['bonsementara'] = $bonsementara;
				$data['totalkeluar'] = $operasional + $bonsementara + $keluarlain;
				$data['bonkasbesar'] = $bonkasbesar;
				$data['uangtunai'] = $uangtunai;
				if(!empty($mods['tanggal'])){
					$data['statusclosing'] = 1;
				}else{
					$data['statusclosing'] = 0;
				}
				

				return $this->asJson($data);
			}
		}
		
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionGetRekapByTanggal($tgl){
		if(\Yii::$app->request->isAjax){
			if(!empty($tgl)){
				$awal = $tgl." 00:00:00";
				$akhir = $tgl." 23:59:59";
				$sql = "SELECT * FROM h_saldo_kaskecil WHERE tanggal BETWEEN '".$awal."' AND '".$akhir."'  
							ORDER BY CAST(SUBSTR(reff_no, 5, 4) AS integer) ASC";
				$models = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($models)>0){
					return $this->renderAjax('rekapbytgl',['models'=>$models]);
				}
			}
		}
	}
	
	public function actionPrintoutLaporan(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$sql = "SELECT * FROM h_saldo_kaskecil WHERE tanggal = '".$tgl."'  
				ORDER BY CAST(SUBSTR(reff_no, 5, 4) AS integer) ASC";
		$model = \Yii::$app->db->createCommand($sql)->queryAll();
		$paramprint['judul'] = Yii::t('app', 'Laporan Pengeluaran Kas Kecil');
		$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
		if($caraprint == 'PRINT'){
			return $this->render('/rekapkaskecil/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/rekapkaskecil/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/rekapkaskecil/printLaporan',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionPrintout(){
		$this->layout = '@views/layouts/metronic/print';
		$caraprint = Yii::$app->request->get('caraprint');
		$tgl = Yii::$app->request->get('tgl');
		$tipe = Yii::$app->request->get('tipe');
		if($tipe=='uangtunai'){
			$model = new \app\models\TUangtunai();
			if(!empty($model)){
				return $this->renderAjax('uangtunai',['model'=>$model,'tgl'=>$tgl,'info'=>true]);
			}
		}
		if($tipe=='kasbon'){
			$paramprint['judul'] = Yii::t('app', 'Laporan Kasbon Sementara');
			$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
			$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KK'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
			if(!empty($models)){
				if($caraprint == 'PRINT'){
					return $this->renderAjax('@app/modules/kasir/views/pengeluarankaskecil/printKasbon',['models'=>$models,'tgl'=>$tgl,'paramprint'=>$paramprint]);
				}else if($caraprint == 'PDF'){
					$pdf = Yii::$app->pdf;
					$pdf->options = ['title' => $paramprint['judul']];
					$pdf->filename = $paramprint['judul'].'.pdf';
					$pdf->mode = \kartik\mpdf\Pdf::MODE_UTF8;
					$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
					$pdf->content = $this->renderPartial('@app/modules/kasir/views/pengeluarankaskecil/printKasbon',['models'=>$models,'paramprint'=>$paramprint]);
					return $pdf->render();
				}else if($caraprint == 'EXCEL'){
					return $this->renderPartial('@app/modules/kasir/views/pengeluarankaskecil/printKasbon',['models'=>$models,'paramprint'=>$paramprint]);
				}
			}
		}
		if($tipe=='kasbonkasbesar'){
			$paramprint['judul'] = Yii::t('app', 'Laporan Hutang Kasbon Dari Kas Besar');
			$paramprint['judul2'] = "Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
			$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KB' AND status = 'KASBON KASBESAR KE KASKECIL'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
			if(!empty($models)){
				if($caraprint == 'PRINT'){
					return $this->renderAjax('@app/modules/kasir/views/pengeluarankaskecil/printKasbonKasbesar',['models'=>$models,'tgl'=>$tgl,'paramprint'=>$paramprint]);
				}else if($caraprint == 'PDF'){
					$pdf = Yii::$app->pdf;
					$pdf->options = ['title' => $paramprint['judul']];
					$pdf->filename = $paramprint['judul'].'.pdf';
					$pdf->mode = \kartik\mpdf\Pdf::MODE_UTF8;
					$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
					$pdf->content = $this->renderPartial('@app/modules/kasir/views/pengeluarankaskecil/printKasbonKasbesar',['models'=>$models,'paramprint'=>$paramprint]);
					return $pdf->render();
				}else if($caraprint == 'EXCEL'){
					return $this->renderPartial('@app/modules/kasir/views/pengeluarankaskecil/printKasbonKasbesar',['models'=>$models,'paramprint'=>$paramprint]);
				}
			}
		}
		return false;
	}
	
	public function actionRekapKaskecil($tgl){
		if(\Yii::$app->request->isAjax){
			$tgl = Yii::$app->request->get('tgl');
			$info = Yii::$app->request->get('info');
			if($info=='uangtunai'){
				$model = new \app\models\TUangtunai();
				if(!empty($model)){
					return $this->renderAjax('uangtunai',['model'=>$model,'tgl'=>$tgl,'info'=>true]);
				}
			}
			if($info=='kasbon'){
				$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KK'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
				if(!empty($models)){
					return $this->renderAjax('@app/modules/kasir/views/pengeluarankaskecil/kasbon',['models'=>$models,'tgl'=>$tgl]);
				}
			}
			if($info=='kasbonkasbesar'){
				$models = \app\models\HBonsementara::find()->where("tanggal = '".$tgl."' AND tipe = 'KB' AND status = 'KASBON KASBESAR KE KASKECIL'")->orderBy(['bonsementara_id'=>SORT_ASC])->all();;
				if(!empty($models)){
					return $this->renderAjax('@app/modules/kasir/views/pengeluarankaskecil/kasbonkasbesar',['models'=>$models,'tgl'=>$tgl]);
				}
			}
			return false;
		}
	}
	
	
	public function actionTanggalSelisihClosing(){
		if(\Yii::$app->request->isAjax){
			$sql = "SELECT t_kas_kecil.tanggal AS tgl_Laporan, h_saldo_kaskecil.created_at::DATE AS tgl_Closing, (h_saldo_kaskecil.created_at::DATE - t_kas_kecil.tanggal) AS selisih_hari FROM t_kas_kecil 
					JOIN h_saldo_kaskecil ON h_saldo_kaskecil.reff_no = t_kas_kecil.kode
					WHERE t_kas_kecil.tanggal != h_saldo_kaskecil.created_at::DATE
					GROUP BY t_kas_kecil.tanggal, h_saldo_kaskecil.created_at::DATE
					ORDER BY t_kas_kecil.tanggal DESC";
			$models = Yii::$app->db->createCommand($sql)->queryAll();
			return $this->renderAjax('tanggalselisihclosing',['models'=>$models]);
		}
	}
}
