<?php

namespace app\modules\marketing\controllers;

use Yii;
use yii\helpers\Json;
use app\components\SSP;
use app\models\TReturProduk;
use app\components\DeltaFormatter;
use app\models\TReturProdukDetail;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{
	public function actionPenjualanHarian()
	{
		$model = new \app\models\TNotaPenjualan();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TNotaPenjualan'];
				$model->tgl_awal = $form_params['TNotaPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TNotaPenjualan']['tgl_akhir'];
				$model->jenis_produk = $form_params['TNotaPenjualan']['jenis_produk'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/penjualanHarian/index', ['model' => $model]);
	}

	public function actionPenjualanHarianPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TNotaPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TNotaPenjualan'];
		$model->tgl_awal = !empty($_GET['TNotaPenjualan']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualan']['tgl_awal']) : "";
		$model->tgl_akhir = !empty($_GET['TNotaPenjualan']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualan']['tgl_akhir']) : "";
		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal Harian');
			$paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal');
			$paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
		}
		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/penjualanHarian/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/penjualanHarian/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/penjualanHarian/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionPenjualanLokalDetail()
	{
		$model = new \app\models\TNotaPenjualanDetail();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TNotaPenjualanDetail'];
				$model->tgl_awal = $form_params['TNotaPenjualanDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TNotaPenjualanDetail']['tgl_akhir'];
				$model->jenis_produk = $form_params['TNotaPenjualanDetail']['jenis_produk'];
				$model->cust_id = $form_params['TNotaPenjualanDetail']['cust_id'];
				//				$model->kode = $form_params['TNotaPenjualanDetail']['kode'];
				$model->sales_id = $form_params['TNotaPenjualanDetail']['sales_id'];
				$model->jenis_kayu = isset($form_params['TNotaPenjualanDetail']['jenis_kayu'])?$form_params['TNotaPenjualanDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TNotaPenjualanDetail']['grade'])?$form_params['TNotaPenjualanDetail']['grade']:null;
				$model->glue = isset($form_params['TNotaPenjualanDetail']['glue'])?$form_params['TNotaPenjualanDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TNotaPenjualanDetail']['profil_kayu'])?$form_params['TNotaPenjualanDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TNotaPenjualanDetail']['kondisi_kayu'])?$form_params['TNotaPenjualanDetail']['kondisi_kayu']:null;
				$model->produk_dimensi = isset($form_params['TNotaPenjualanDetail']['produk_dimensi'])?$form_params['TNotaPenjualanDetail']['produk_dimensi']:null;
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/penjualanLokalDetail/index', ['model' => $model]);
	}

	public function actionPenjualanLokalDetailPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TNotaPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TNotaPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TNotaPenjualanDetail']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualanDetail']['tgl_awal']) : "";
		$model->tgl_akhir = !empty($_GET['TNotaPenjualanDetail']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TNotaPenjualanDetail']['tgl_akhir']) : "";
		$model->jenis_produk = !empty($_GET['TNotaPenjualanDetail']['jenis_produk']) ? $_GET['TNotaPenjualanDetail']['jenis_produk'] : "";
		$model->cust_id = !empty($_GET['TNotaPenjualanDetail']['cust_id']) ? $_GET['TNotaPenjualanDetail']['cust_id'] : "";
		//		$model->kode = !empty($_GET['TNotaPenjualanDetail']['kode'])?$_GET['TNotaPenjualanDetail']['kode']:"";
		$model->sales_id = !empty($_GET['TNotaPenjualanDetail']['sales_id']) ? $_GET['TNotaPenjualanDetail']['sales_id'] : "";
		$model->jenis_kayu = !empty($_GET['TNotaPenjualanDetail']['jenis_kayu']) ? $_GET['TNotaPenjualanDetail']['jenis_kayu'] : "";
		$model->grade = !empty($_GET['TNotaPenjualanDetail']['grade']) ? $_GET['TNotaPenjualanDetail']['grade'] : "";
		$model->glue = !empty($_GET['TNotaPenjualanDetail']['glue']) ? $_GET['TNotaPenjualanDetail']['glue'] : "";
		$model->profil_kayu = !empty($_GET['TNotaPenjualanDetail']['profil_kayu']) ? $_GET['TNotaPenjualanDetail']['profil_kayu'] : "";
		$model->kondisi_kayu = !empty($_GET['TNotaPenjualanDetail']['kondisi_kayu']) ? $_GET['TNotaPenjualanDetail']['kondisi_kayu'] : "";
		$model->produk_dimensi = !empty($_GET['TNotaPenjualanDetail']['produk_dimensi']) ? $_GET['TNotaPenjualanDetail']['produk_dimensi'] : "";
		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal Harian');
			$paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penjualan Produk Lokal');
			$paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
		}
		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/penjualanLokalDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/penjualanLokalDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/penjualanLokalDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionApprovalOp()
	{
		$model = new \app\models\TOpKo();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TOpKo'];
				$model->tgl_awal = $form_params['TOpKo']['tgl_awal'];
				$model->tgl_akhir = $form_params['TOpKo']['tgl_akhir'];
				$model->status = $form_params['TOpKo']['status'];
				$model->jenis_produk = $form_params['TOpKo']['jenis_produk'];
				$model->cust_id = $form_params['TOpKo']['cust_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDtX()));
		}
		return $this->render('/laporan/approvalOp/index', ['model' => $model]);
	}

	public function actionApprovalOpPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TOpKo();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TOpKo'];

		$model->tgl_awal = !empty($_GET['TOpKo']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TOpKo']['tgl_awal']) : "";
		$model->tgl_akhir = !empty($_GET['TOpKo']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TOpKo']['tgl_akhir']) : "";

		//                $model->tgl_awal = $_GET['TOpKo']['tgl_awal'];
		//		$model->tgl_akhir = $_GET['TOpKo']['tgl_akhir'];


		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Order Penjualan');
			$paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Order Penjualan');
			$paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
		}
		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/approvalOp/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/approvalOp/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/approvalOp/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	/*public function actionPricelist(){
		$model = new \app\models\MHargaProduk();
		if(\Yii::$app->request->get('dt')=='table-laporan'){
				if((\Yii::$app->request->get('laporan_params')) !== null){
						$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
						$model->attributes = $form_params['MHargaProduk'];
						$model->produk_group = $form_params['MHargaProduk']['produk_group'];
				}
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/pricelist/index',['model'=>$model]);
	}*/

	public function actionPricelist()
	{
		$model = new \app\models\MBrgProduk();
		$modHarga = new \app\models\MHargaProduk();

		$xxx = \app\models\MHargaProduk::find()->orderBy(['harga_id' => SORT_DESC])->one();

		if (isset($_GET['jp']) && isset($_GET['tp'])) {
			$model->produk_group = $_GET['jp'];
		} else {
			$model->produk_group = 'Platform';
		}
		return $this->render('/laporan/pricelist/index', ['model' => $model, 'modHarga' => $modHarga, 'xxx' => $xxx]);
	}

	public function actionSetTglDropdown()
	{
		if (\Yii::$app->request->isAjax) {
			$produk_group = Yii::$app->request->post('produk_group');
			$mod = [];

			$sql = "select kode, harga_tanggal_penetapan
                        from m_harga_produk a
                        join m_brg_produk b ON b.produk_id = a.produk_id 
						where b.produk_group = '" . $produk_group . "'
						and status_approval = 'APPROVED'
                        group by kode, harga_tanggal_penetapan
                        order by harga_tanggal_penetapan DESC  " .
				" ";

			$mod = \Yii::$app->db->createCommand($sql)->queryAll();

			$arraymap = \yii\helpers\ArrayHelper::map($mod, 'kode', 'kode');
			$html = "";

			foreach ($arraymap as $i => $kode) {
				$sql_harga_tanggal_penetapan = "select harga_tanggal_penetapan from m_harga_produk where kode = '" . $kode . "' order by harga_id desc limit 1";
				$harga_tanggal_penetapan = Yii::$app->db->createCommand($sql_harga_tanggal_penetapan)->queryScalar();

				$sql_status_approval = "select status_approval from m_harga_produk where kode = '" . $kode . "' order by harga_id desc limit 1";
				$status_approval = Yii::$app->db->createCommand($sql_status_approval)->queryScalar();

				$sql_harga_enduser = "select sum(harga_enduser) from m_harga_produk where kode = '" . $kode . "'";
				$total_harga_enduser = Yii::$app->db->createCommand($sql_harga_enduser)->queryScalar();
				$total_harga_enduser = \app\components\DeltaFormatter::formatNumberForAllUser($total_harga_enduser);

				if ($status_approval == "APPROVED") {
					$style = "background-color: #fff; color: #5cb85c;";
				} else if ($status_approval == "REJECTED") {
					$style = "background-color: #fff; color: #d9534f;";
				} else {
					$style = "background-color: #fff; color: #000;";
				}
				$html .= \yii\bootstrap\Html::tag('option', Yii::t('app', 'Price List Tanggal : ') . \app\components\DeltaFormatter::formatDateTimeForUser($harga_tanggal_penetapan) . ' ' . $status_approval . ' ' . $total_harga_enduser . ' ' . $kode . '', ['style' => $style, 'value' => $harga_tanggal_penetapan, 'name' => 'harga_tanggal_penetapan', 'label' => $kode]);
			}
			$data['html'] = $html;
			return $this->asJson($data);
		}
	}

	public function actionPenerimaanJasaKD()
	{
		$model = new \app\models\TOpKo();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
		if (\Yii::$app->request->get('dt') == 'table-dataTable') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TOpKo'];
				$model->tgl_awal = $form_params['TOpKo']['tgl_awal'];
				$model->tgl_akhir = $form_params['TOpKo']['tgl_akhir'];
				$model->cust_an_nama = $form_params['TOpKo']['cust_an_nama'];
				$model->kode = $form_params['TOpKo']['kode'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanPenerimaanJasaKDDt()));
		}
		return $this->render('/laporan/penerimaanJasaKD/index', ['model' => $model]);
	}

	/**public function actionPenerimaanJasaKD()
	{
		if (\Yii::$app->request->get('dt') == 'table-dataTable') {
			$param['table'] = \app\models\TOpKo::tableName();
			$param['pk'] = $param['table'] . "." . \app\models\TOpKo::primaryKey()[0];
			$param['column'] = [
				$param['table'] . '.op_ko_id',																			//0	
				$param['table'] . '.kode',																				//1
				$param['table'] . '.jenis_produk',																		//2		
				$param['table'] . '.tanggal',																				//3
				'm_sales.sales_nm',																						//4
				$param['table'] . '.sistem_bayar',																		//5		
				$param['table'] . '.tanggal_kirim',																		//6		
				'm_customer.cust_an_nama',																				//7
				'm_customer.cust_pr_nama',																				//8
				$param['table'] . '.cancel_transaksi_id',																	//9			
				'MAX(t_spm_ko.spm_ko_id) AS spm_ko_id',																	//10			
				$param['table'] . '.status as xxx',																		//11
				'(select nota_penjualan_id
									from t_nota_penjualan 
									where t_nota_penjualan.op_ko_id = t_op_ko.op_ko_id
									limit 1 ) as yyy',																					//12
				'(select status from t_approval where reff_no = t_op_ko.kode and level = 1) as status_level_1',			//13
				'(select status from t_approval where reff_no = t_op_ko.kode and level = 2) as status_level_2',			//14
			];
			$param['join'] = ['JOIN m_sales ON m_sales.sales_id = ' . $param['table'] . '.sales_id 
							  JOIN m_customer ON m_customer.cust_id = ' . $param['table'] . '.cust_id
							  LEFT JOIN t_spm_ko ON t_spm_ko.op_ko_id = ' . $param['table'] . '.op_ko_id
							'];
			$param['group'] = "GROUP BY " . $param['table'] . ".op_ko_id,
										" . $param['table'] . ".kode, 
										" . $param['table'] . ".jenis_produk,
										" . $param['table'] . ".tanggal,
										m_sales.sales_nm,
										" . $param['table'] . ".sistem_bayar,
										" . $param['table'] . ".tanggal_kirim,
										m_customer.cust_an_nama,
										m_customer.cust_pr_nama,
										" . $param['table'] . ".cancel_transaksi_id,
										xxx,
										yyy
										";
			$param['where'] = "t_op_ko.cancel_transaksi_id IS NULL
									and t_op_ko.jenis_produk = 'JasaKD'
									";
			return \yii\helpers\Json::encode(\app\components\SSP::complex($param));
		}
		return $this->render('/laporan/penerimaanJasaKD/index');
	}*/

	public function actionInfo($id)
	{
		if (\Yii::$app->request->isAjax) {
			$model = \app\models\TOpKo::findOne($id);
			return $this->renderAjax('/laporan/penerimaanJasaKD/_info', ['op_ko_id' => $id, 'model' => $model]);
		}
	}

	public function actionInfo2($id)
	{
		if (\Yii::$app->request->isAjax) {
			$model = \app\models\TOpKo::findOne($id);
			return $this->renderAjax('/laporan/approvalOp/info', ['op_ko_id' => $id, 'model' => $model]);
		}
	}

	public function actionGetContent()
	{
		if (\Yii::$app->request->isAjax) {
			$jp = Yii::$app->request->get('jp');
			$kode = Yii::$app->request->get('kode');

			$sql_tanggal = "select harga_tanggal_penetapan from m_harga_produk where kode = '" . $kode . "' ";
			$harga_tanggal_penetapan = Yii::$app->db->createCommand($sql_tanggal)->queryScalar();

			$sql = " select b.kode, b.harga_tanggal_penetapan, a.produk_id, a.produk_kode, a.produk_nama, a.produk_dimensi, b.harga_enduser " .
				"   from m_brg_produk a " .
				"   left join m_harga_produk b on b.produk_id = a.produk_id " .
				"   where a.produk_group = '" . $jp . "'  " .
				//"   and a.active = TRUE ".
				//"	and b.harga_tanggal_penetapan = '".$tp."' ".
				"   and b.kode = '" . $kode . "' " .
				"   group by b.kode, b.harga_tanggal_penetapan, a.produk_id, a.produk_kode, a.produk_nama, b.harga_enduser " .
				"   order by a.produk_id asc " .
				"   ";

			$models = Yii::$app->db->createCommand($sql)->queryAll();
			$numrows = count($models);

			if ($numrows > 0) {
				return $this->renderAjax('/laporan/pricelist/_content', ['numrows' => $numrows, 'models' => $models, 'jp' => $jp, 'kode' => $kode, 'harga_tanggal_penetapan' => $harga_tanggal_penetapan]);
			} else {
				return $this->renderAjax('/laporan/pricelist/_content', ['numrows' => $numrows, 'sql' => $sql]);
			}
		}
	}

	public function actionPencapaianPenjualan()
	{
		$model = new \app\models\TTargetPenjualan();
		$model->periode = date('Y');

		if ((\Yii::$app->request->get('laporan_params')) !== null) {
			$form_params = [];
			parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
			$model->attributes = $form_params['TTargetPenjualan'];
			$model->periode = $form_params['TTargetPenjualan']['periode'];
			$data['html'] = $this->renderPartial('/laporan/pencapaianPenjualan/rekapContent', ['model' => $model]);
			return $this->asJson($data);
		}
		return $this->render('/laporan/pencapaianPenjualan/index', ['model' => $model]);
	}

	public function actionInfoPenjualan($periode)
	{
		if (\Yii::$app->request->isAjax) {
			$model = $periode;
			return $this->renderAjax('/laporan/pencapaianPenjualan/infoPenjualan', ['periode' => $periode]);
		}
	}

	public function actionReturPenjualan()
	{
		$model = new TReturProduk();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TReturProduk'];
				$model->tgl_awal = $form_params['TReturProduk']['tgl_awal'];
				$model->tgl_akhir = $form_params['TReturProduk']['tgl_akhir'];
				// $model->jenis_produk = $form_params['TReturProduk']['jenis_produk'];
			}
			return Json::encode(SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/returPenjualan/index', ['model' => $model]);
	}

	public function actionReturPenjualanPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new TReturProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturProduk'];
		$model->tgl_awal = !empty($_GET['TReturProduk']['tgl_awal']) ? DeltaFormatter::formatDateTimeForDb($_GET['TReturProduk']['tgl_awal']) : "";
		$model->tgl_akhir = !empty($_GET['TReturProduk']['tgl_akhir']) ? DeltaFormatter::formatDateTimeForDb($_GET['TReturProduk']['tgl_akhir']) : "";
		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Retur Penjualan');
			$paramprint['judul2'] = "Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Retur Penjualan');
			$paramprint['judul2'] = "Periode Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
		}
		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/returPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/returPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/returPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionReturPenjualanDetail()
	{
		$model 				= new TReturProdukDetail();
		$model->tgl_awal 	= date('d/m/Y');
		$model->tgl_akhir 	= date('d/m/Y');
		if (Yii::$app->request->get('dt') == 'table-laporan') {
			if ((Yii::$app->request->get('laporan_params')) !== null) {
				parse_str($_GET['laporan_params'], $params);
				$params 				= $params['TReturProdukDetail'];
				$model->attributes 		= $params;
				$model->tgl_awal 		= $params['tgl_awal'];
				$model->tgl_akhir 		= $params['tgl_akhir'];
				$model->jenis_produk 	= $params['jenis_produk'];
				$model->cust_id 		= $params['cust_id'];
				$model->sales_id 		= $params['sales_id'];
			}
			return Json::encode(SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/returPenjualanDetail/index', compact('model'));
	}

	public function actionReturPenjualanDetailPrint()
	{
		$this->layout 			= '@views/layouts/metronic/print';
		$model 					= new TReturProdukDetail();
		$caraprint 				= Yii::$app->request->get('caraprint');
		$model->attributes 		= $_GET['TReturProdukDetail'];
		$model->tgl_awal 		= !empty($_GET['TReturProdukDetail']['tgl_awal']) ? DeltaFormatter::formatDateTimeForDb($_GET['TReturProdukDetail']['tgl_awal']) : "";
		$model->tgl_akhir 		= !empty($_GET['TReturProdukDetail']['tgl_akhir']) ? DeltaFormatter::formatDateTimeForDb($_GET['TReturProdukDetail']['tgl_akhir']) : "";
		$model->jenis_produk	= !empty($_GET['TReturProdukDetail']['jenis_produk']) ? $_GET['TReturProdukDetail']['jenis_produk'] : "";
		$model->cust_id 		= !empty($_GET['TReturProdukDetail']['cust_id']) ? $_GET['TReturProdukDetail']['cust_id'] : "";
		$model->sales_id 		= !empty($_GET['TReturProdukDetail']['sales_id']) ? $_GET['TReturProdukDetail']['sales_id'] : "";
		
		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Retur Produk Detail');
			$paramprint['judul2'] = "Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Retur Produk Detail');
			$paramprint['judul2'] = "Periode Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
		}
		
		if($caraprint !== 'PDF') {
			return $this->render('/laporan/returPenjualanDetail/print', compact('model', 'paramprint'));
		}else {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/returPenjualanDetail/print', compact('model', 'paramprint'));
			return $pdf->render();
		}
	}

	public function actionPricelistlog()
	{
		$model = new \app\models\MBrgLog();
		$modHarga = new \app\models\MHargaLog();

		$xxx = \app\models\MHargaLog::find()->orderBy(['harga_id' => SORT_DESC])->one();

		return $this->render('/laporan/pricelistlog/index', ['model' => $model, 'modHarga' => $modHarga, 'xxx' => $xxx]);
	}

	public function actionSetTglDropdownLog()
    {
        if(Yii::$app->request->isAjax) {
            $selectedTanggal = Yii::$app->request->post('selected');
            $query = Yii::$app->db->createCommand(
                "SELECT SUM
                    ( harga_enduser ) AS total_harga,
                    harga_tanggal_penetapan,
                    kode,
                    status_approval 
                FROM
                    m_harga_log 
                GROUP BY
                    harga_tanggal_penetapan,
                    kode,
                    status_approval"
            )->queryAll();
    
            $html = '';
            foreach($query as $row) {
                if($row['status_approval'] == 'APPROVED') {
                    $style = "background-color: #fff; color: #5cb85c;";
                }else if($row['status_approval'] == 'REJECTED') {
                    $style = "background-color: #fff; color: #d9534f;";
                }else {
                    $style = "background-color: #fff; color: #000;";
                }
    
                $text   = Yii::t('app', 'Price List Tanggal : ')
                    .\app\components\DeltaFormatter::formatDateTimeForUser($row['harga_tanggal_penetapan'])
                    .' '.$row['status_approval'].' '.$row['total_harga'].' '.$row['kode'];
                $options= [
                    'style'=>$style,
                    'value'=>$row['harga_tanggal_penetapan'], 
                    'name'=>'harga_tanggal_penetapan', 
                    'label'=>$row['kode']
                ];

                if($selectedTanggal && $selectedTanggal == $row['harga_tanggal_penetapan']) {
                    $options['selected'] = true;
                }
                $html  .= \yii\bootstrap\Html::tag('option', $text, $options);
            }
            $data['html'] = $html;
            return $this->asJson($data);
        }
    }

	public function actionGetContentLog(){
        if(\Yii::$app->request->isAjax){
            $tgl                    = Yii::$app->request->post('tgl');
			$kode 					= Yii::$app->request->get('kode');
			$sql_tanggal = "select harga_tanggal_penetapan from m_harga_log where kode = '" . $kode . "' ";
			$harga_tanggal_penetapan = Yii::$app->db->createCommand($sql_tanggal)->queryScalar();

			$sql = " select b.kode, b.harga_tanggal_penetapan, a.log_id, a.log_kode, a.log_nama, a.range_awal, a.range_akhir, b.harga_enduser " .
				"   from m_brg_log a " .
				"   left join m_harga_log b on b.log_id = a.log_id " .
				"   and b.kode = '" . $kode . "' " .
				"   group by b.kode, b.harga_tanggal_penetapan, a.log_id, a.log_kode, a.log_nama, b.harga_enduser " .
				"   order by a.log_id asc " .
				"   ";
			$models = Yii::$app->db->createCommand($sql)->queryAll();
			$numrows = count($models);

			if ($numrows > 0) {
				return $this->renderAjax('/laporan/pricelistlog/_content', ['numrows' => $numrows, 'models' => $models, 'kode' => $kode, 'harga_tanggal_penetapan' => $harga_tanggal_penetapan]);
			} else {
				return $this->renderAjax('/laporan/pricelistlog/_content', ['numrows' => $numrows, 'sql' => $sql]);
			}			
        }
    }

	public function actionPenerimaanJasakdPrint()
	{
		$this->layout 			= '@views/layouts/metronic/print';
		$model 					= new \app\models\TOpKo();
		$caraprint 				= Yii::$app->request->get('caraprint');
		$model->attributes 		= $_GET['TOpKo'];
		$model->tgl_awal 		= !empty($_GET['TOpKo']['tgl_awal']) ? DeltaFormatter::formatDateTimeForDb($_GET['TOpKo']['tgl_awal']) : "";
		$model->tgl_akhir 		= !empty($_GET['TOpKo']['tgl_akhir']) ? DeltaFormatter::formatDateTimeForDb($_GET['TOpKo']['tgl_akhir']) : "";
		$model->cust_an_nama 	= !empty($_GET['TOpKo']['cust_an_nama']) ? $_GET['TOpKo']['cust_an_nama'] : "";
		$model->kode 			= !empty($_GET['TOpKo']['kode']) ? $_GET['TOpKo']['kode'] : "";
		
		if ($model->tgl_awal == $model->tgl_akhir) {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Jasa KD');
			$paramprint['judul2'] = "Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u><br>";
		} else {
			$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Jasa KD');
			$paramprint['judul2'] = "Periode Tanggal <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u><br>";
		}
		if($model->kode){
			$paramprint['judul2'] .= "Kode : " . $model->kode . "<br>";
		}
		if($model->cust_an_nama){
			$paramprint['judul2'] .= "Customer : " . $model->cust_an_nama;
		}

		if ($caraprint == 'PRINT') {
            return $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'paramprint' => $paramprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
	}

	/*public function actionPenerimaanJasaKDTotal()
    {
        $model = new \app\models\TOpKo();
        $param = Yii::$app->request->get('TOpKo');
        $model->attributes  	= $param;
        $model->tgl_awal		= $param['tgl_awal'];
		$model->tgl_akhir 		= $param['tgl_akhir'];
		$model->cust_an_nama 	= $param['cust_an_nama'];
		$model->kode 			= $param['kode'];
        $qtydok  = 0; $voldok = 0;
		$qtyact = 0; $volact = 0;
		$vols = 0;
        foreach($model->searchLaporanPenerimaanJasaKD()->createCommand()->query() as $row) {
			$qtydok += $row['qty_kecil'];
			$voldok += $row['kubikasi'];
			$qtyact += $row['qty_kecil_actual'];
			$volact += $row['kubikasi_actual'];
			if($row['kode_spm']){
				$vols += $row['kubikasi_actual'];
			}
        }
        return \yii\helpers\Json::encode(['qtydok' => $qtydok, 'voldok'=>$voldok, 'qtyact'=>$qtyact, 'volact'=>$volact, 'vols'=>$vols]);
    }

	public function actionPenerimaanJasakdPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$op_ko_id = Yii::$app->request->get('id');
		$model = \app\models\TOpKo::findOne($op_ko_id);
        $caraprint = 'EXCEL';
        $paramprint['judul'] = Yii::t('app', 'Penerimaan Jasa KD Detail');
        if ($caraprint == 'PRINT') {
            return $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'op_ko_id' => $op_ko_id, 'paramprint' => $paramprint, 'caraprint'=>$caraprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'op_ko_id' => $op_ko_id, 'paramprint' => $paramprint, 'caraprint'=>$caraprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/penerimaanJasaKD/print', ['model' => $model, 'op_ko_id' => $op_ko_id, 'paramprint' => $paramprint, 'caraprint'=>$caraprint]);
        }
	}*/
}
