<?php

namespace app\modules\gudang\controllers;

use app\components\DeltaFormatter;
use app\components\SSP;
use app\models\HPersediaanProduk;
use Yii;
use app\controllers\DeltaBaseController;
use yii\helpers\Json;

class AvailablestockprodukController extends DeltaBaseController
{
    
	public $defaultAction = 'index';

	public function actionIndex(){
        $model = new HPersediaanProduk();
        $model->produk_group = 'Plywood';
        $model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			/*$param['table']= \app\models\HPersediaanProduk::tableName();
			$param['pk']= \app\models\HPersediaanProduk::primaryKey()[0];
			$param['column'] = [$param['table'].'.produk_id',
								'm_brg_produk.produk_group',
								'm_brg_produk.produk_kode',
								'm_brg_produk.produk_nama',
								'sum(in_qty_palet-out_qty_palet) AS palet',
								'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
								'in_qty_kecil_satuan',
								'sum(in_qty_m3-out_qty_m3) AS kubikasi',
								];
            $param['group'] = 'GROUP BY m_brg_produk.produk_group, '.$param['table'].'.produk_id, m_brg_produk.produk_kode, m_brg_produk.produk_nama, in_qty_kecil_satuan';
			$param['join']= ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id'];
			$param['having'] = "HAVING SUM(in_qty_palet-out_qty_palet) > 0";
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));*/
            if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = isset($form_params['HPersediaanProduk']) ? $form_params['HPersediaanProduk'] : null;
				$model->nomor_produksi = isset($form_params['HPersediaanProduk']['nomor_produksi'])?$form_params['HPersediaanProduk']['nomor_produksi']:null;
				$model->produk_group = isset($form_params['HPersediaanProduk']['produk_group'])?$form_params['HPersediaanProduk']['produk_group']:null;
				$model->produk_nama = isset($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:null;
				$model->jenis_kayu = isset($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:null;
				$model->grade = isset($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:null;
				$model->glue = isset($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:null;
				$model->profil_kayu = isset($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:null;
				$model->per_tanggal = isset($form_params['HPersediaanProduk']['per_tanggal'])?$form_params['HPersediaanProduk']['per_tanggal']:null;
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('index',['model'=>$model]);
	}

    /**
     * @return string|void
     */
	
	public function actionStockPrint(){
        $this->layout = '@views/layouts/metronic/print';
        $model = new HPersediaanProduk();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes      = $_GET['HPersediaanProduk'];
        $model->produk_nama     = $_GET['HPersediaanProduk']['produk_nama'];
        $model->produk_group    = $_GET['HPersediaanProduk']['produk_group'];
        $model->per_tanggal     = $_GET['HPersediaanProduk']['per_tanggal'];
        $paramprint['judul']    = Yii::t('app', 'Laporan Persediaan Produk');
        $paramprint['judul2']   = "Per Tanggal " . DeltaFormatter::formatDateTimeForUser2(!empty($model->per_tanggal) ? $model->per_tanggal : date('d/m/Y'));
        
        if ($caraprint === 'PRINT') {
            return $this->renderPartial('/availablestockproduk/print', ['model' => $model, 'paramprint' => $paramprint]);
        }

        if ($caraprint === 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->renderPartial('/availablestockproduk/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        }

        if ($caraprint === 'EXCEL') {
            return $this->renderPartial('/availablestockproduk/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
    }
	
	// produk list untuk available stock
//	public function actionProduklistAS($produk_id=null,$satuan_kecil=null,$gudang_nm=null){
//		if(\Yii::$app->request->isAjax){
//			if(\Yii::$app->request->get('dt')=='table-produk'){
//				$param['table']= HPersediaanProduk::tableName();
//				$param['pk']= HPersediaanProduk::primaryKey()[0];
//				$param['column'] = [$param['table'].'.produk_id',
//									'm_brg_produk.produk_kode',
//									'm_brg_produk.produk_nama',
//									$param['table'].'.nomor_produksi',
//									't_produksi.tanggal_produksi',
//									't_produksi.plymill_shift',
//									't_produksi.sawmill_line',
//									'm_gudang.gudang_nm',
//									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
//									'in_qty_kecil_satuan',
//									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
//									'(select count(*) from t_terima_ko_kd where t_terima_ko_kd.tbko_id = t_terima_ko.tbko_id) as tot'
//									];
//				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id,
//									 m_brg_produk.produk_kode,
//									 m_brg_produk.produk_nama,
//									 in_qty_kecil_satuan,
//									 '.$param['table'].'.nomor_produksi,
//									 t_produksi.tanggal_produksi,
//									 t_produksi.plymill_shift,
//									 t_produksi.sawmill_line,
//									 m_gudang.gudang_nm,
//									 in_qty_kecil_satuan,
//									 tot
//									 ';
//				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
//								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi
//								  JOIN m_gudang ON m_gudang.gudang_id = h_persediaan_produk.gudang_id
//								  JOIN t_terima_ko on t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
//								  '];
//				if(!empty($produk_id)){
//					$param['where'] = $param['table'].".produk_id = ".$produk_id;
//				}
//				if(!empty($produk_id) && !empty($satuan_kecil) && !empty($gudang_nm)){
//					$param['where'] .= " AND in_qty_kecil_satuan = '$satuan_kecil' AND gudang_nm = '".$gudang_nm."' ";
//				}
//				$param['having'] = "HAVING SUM(in_qty_kecil-out_qty_kecil) > 0";
//				return Json::encode(SSP::complex( $param ));
//			}
//			return $this->renderAjax('produklistAS',['produk_id'=>$produk_id,'satuan_kecil'=>$satuan_kecil,'gudang_nm'=>$gudang_nm]);
//        }
//	}
	
	public function actionProduklist($produk_id=null,$satuan_kecil=null,$gudang_nm=null){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt') === 'table-produk'){
				$param['table']= HPersediaanProduk::tableName();
				$param['pk']= HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									$param['table'].'.nomor_produksi',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'm_gudang.gudang_nm',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 '.$param['table'].'.nomor_produksi,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 m_gudang.gudang_nm,
									 in_qty_kecil_satuan
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi
								  JOIN m_gudang ON m_gudang.gudang_id = '.$param['table'].'.gudang_id'];
				if(!empty($produk_id)){
					$param['where'] = $param['table'].".produk_id = ".$produk_id;
				}
				if(!empty($produk_id) && !empty($satuan_kecil) && !empty($gudang_nm)){
					$param['where'] .= " AND in_qty_kecil_satuan = '".$satuan_kecil."' AND gudang_nm = '".$gudang_nm."'";
				}
				$param['having'] = "HAVING SUM(in_qty_kecil-out_qty_kecil) > 0";
				return Json::encode(SSP::complex( $param ));
			}
			return $this->renderAjax('produklist',['produk_id'=>$produk_id,'satuan_kecil'=>$satuan_kecil,'gudang_nm'=>$gudang_nm]);
        }
    }
	
	public function actionProdukListOnModal($tr_seq=null,$jns_produk=null,$notin=null){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-produk'){
				$notinpost = json_decode( Yii::$app->request->get('notin') );
				$notin = "";
				if(!empty($notinpost)){
					$notin = "AND h_persediaan_produk.nomor_produksi NOT IN(";
					foreach($notinpost as $i => $not){
						$notin .= "'$not'";
						if( ($i+1)!=(count($notinpost)) ){
							$notin .= ",";
						}
					}
					$notin .= ")";
				}
				$param['table']= HPersediaanProduk::tableName();
				$param['pk']= HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									$param['table'].'.nomor_produksi',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'm_gudang.gudang_nm',
									'sum(in_qty_palet-out_qty_palet) AS qty_palet',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									$param['table'].'.gudang_id',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									'.$param['table'].'.nomor_produksi,
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 m_gudang.gudang_nm,
									 in_qty_kecil_satuan,
									 '.$param['table'].'.gudang_id
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi
								  JOIN m_gudang ON m_gudang.gudang_id = '.$param['table'].'.gudang_id'];
				$param['where'] = "m_brg_produk.produk_group = '".$jns_produk."' ".$notin;
				$param['having'] = "HAVING SUM(in_qty_palet-out_qty_palet) > 0";
				return Json::encode(SSP::complex( $param ));
			}
			return $this->renderAjax('listOnModal',['tr_seq'=>$tr_seq,'jns_produk'=>$jns_produk,'notin'=>$notin]);
		}
	}
	
	public function actionCurrentStock(){
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-produk'){
				$param['table']= HPersediaanProduk::tableName();
				$param['pk']= HPersediaanProduk::primaryKey()[0];
				$param['column'] = [$param['table'].'.produk_id',
									'm_brg_produk.produk_kode',
									'm_brg_produk.produk_nama',
									$param['table'].'.nomor_produksi',
									't_produksi.tanggal_produksi',
									't_produksi.plymill_shift',
									't_produksi.sawmill_line',
									'sum(in_qty_kecil-out_qty_kecil) AS qty_kecil',
									'in_qty_kecil_satuan',
									'sum(in_qty_m3-out_qty_m3) AS kubikasi',
									];
				$param['group'] = 'GROUP BY '.$param['table'].'.produk_id, 
									 m_brg_produk.produk_kode, 
									 m_brg_produk.produk_nama, 
									 in_qty_kecil_satuan,
									 '.$param['table'].'.nomor_produksi,
									 t_produksi.tanggal_produksi,
									 t_produksi.plymill_shift,
									 t_produksi.sawmill_line,
									 in_qty_kecil_satuan
									 ';
				$param['join'] = ['JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
								  JOIN t_produksi ON t_produksi.nomor_produksi = '.$param['table'].'.nomor_produksi'];
				$param['having'] = "HAVING SUM(in_qty_kecil-out_qty_kecil) > 0";
				return Json::encode(SSP::complex( $param ));
			}
			return $this->renderAjax('currentstock');
        }
    }
	
}
