<?php

namespace app\modules\gudang\controllers;

use app\components\SSP;
use app\models\HPersediaanProduk;
use Yii;
use app\controllers\DeltaBaseController;
use app\models\TPengajuanRepacking;
use app\models\TPengajuanRepackingDetail;
use app\models\TReturProdukDetail;
use yii\helpers\Json;

class LaporanController extends DeltaBaseController
{	
	public function actionMutasiGudangLogistik(){
		$model = new \app\models\TMutasiGudanglogistik();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TMutasiGudanglogistik'];
				$model->tgl_awal = $form_params['TMutasiGudanglogistik']['tgl_awal'];
				$model->tgl_akhir = $form_params['TMutasiGudanglogistik']['tgl_akhir'];
				$model->bhp_nm = $form_params['TMutasiGudanglogistik']['bhp_nm'];
				$model->kode = $form_params['TMutasiGudanglogistik']['kode'];
				$model->departement_id = $form_params['TMutasiGudanglogistik']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/mutasigudanglogistik/index',['model'=>$model]);
	}
	
	public function actionMutasiGudangLogistikPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TMutasiGudanglogistik();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TMutasiGudanglogistik'];
		$model->tgl_awal = !empty($_GET['TMutasiGudanglogistik']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TMutasiGudanglogistik']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TMutasiGudanglogistik']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TMutasiGudanglogistik']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TMutasiGudanglogistik']['bhp_nm'];
		$model->kode = $_GET['TMutasiGudanglogistik']['kode'];
		$model->departement_id = $_GET['TMutasiGudanglogistik']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Mutasi Barang Gudang Logistik');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/mutasigudanglogistik/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionStockProduk(){
		$model = new HPersediaanProduk();
		$model->produk_group = 'Plywood';
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->produk_nama = $form_params['HPersediaanProduk']['produk_nama'];
				$model->produk_group = $form_params['HPersediaanProduk']['produk_group'];
				$model->jenis_kayu = isset($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:null;
				$model->grade = isset($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:null;
				$model->glue = isset($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:null;
				$model->profil_kayu = isset($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:null;
				$model->per_tanggal = $form_params['HPersediaanProduk']['per_tanggal'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
        return $this->render('/laporan/stockProduk/index',['model'=>$model]);
	}
	
	public function actionStockProdukPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->produk_nama = $_GET['HPersediaanProduk']['produk_nama'];
		$model->produk_group = $_GET['HPersediaanProduk']['produk_group'];
		$model->per_tanggal = $_GET['HPersediaanProduk']['per_tanggal'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Produk');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockProduk/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionStockPalet(){
		$model = new HPersediaanProduk();
		$model->produk_group = 'Plywood';
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->nomor_produksi = isset($form_params['HPersediaanProduk']['nomor_produksi'])?$form_params['HPersediaanProduk']['nomor_produksi']:null;
				$model->produk_group = isset($form_params['HPersediaanProduk']['produk_group'])?$form_params['HPersediaanProduk']['produk_group']:null;
				$model->produk_nama = isset($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:null;
				$model->jenis_kayu = isset($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:null;
				$model->grade = isset($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:null;
				$model->glue = isset($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:null;
				$model->profil_kayu = isset($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:null;
				$model->per_tanggal = isset($form_params['HPersediaanProduk']['per_tanggal'])?$form_params['HPersediaanProduk']['per_tanggal']:null;
			}
			return Json::encode(SSP::complex( $model->searchLaporanPaletDt() ));
		}
		return $this->render('/laporan/stockPalet/index',['model'=>$model]);
	}

    public function actionStockPaletDetail(){
		$nomor_produksi = Yii::$app->request->get('id');
		$t_terima_ko = \app\models\TTerimaKo::find()->where(['nomor_produksi'=>$nomor_produksi])->one();
			$tbko_id = $t_terima_ko->tbko_id;
			$produk_id = $t_terima_ko->produk_id;
		$t_terima_ko_kd = \app\models\TTerimaKoKd::find()->where(['tbko_id'=>$tbko_id])->all();
		$m_brg_produk = \app\models\MBrgProduk::find()->where(['produk_id'=>$produk_id])->one();
		return $this->renderAjax('/laporan/stockPalet/_info',['nomor_produksi'=>$nomor_produksi, 't_terima_ko'=>$t_terima_ko, 'tbko_ko_id'=>$tbko_id, 't_terima_ko_kd'=>$t_terima_ko_kd, 'm_brg_produk'=>$m_brg_produk]);
	}
	
	public function actionStockPaletPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->nomor_produksi = isset($_GET['HPersediaanProduk']['nomor_produksi'])?$_GET['HPersediaanProduk']['nomor_produksi']:null;
		$model->produk_group = isset($_GET['HPersediaanProduk']['produk_group'])?$_GET['HPersediaanProduk']['produk_group']:null;
		$model->produk_nama = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		$model->jenis_kayu = isset($_GET['HPersediaanProduk']['jenis_kayu'])?$_GET['HPersediaanProduk']['jenis_kayu']:null;
		$model->grade = isset($_GET['HPersediaanProduk']['grade'])?$_GET['HPersediaanProduk']['grade']:null;
		$model->glue = isset($_GET['HPersediaanProduk']['glue'])?$_GET['HPersediaanProduk']['glue']:null;
		$model->profil_kayu = isset($_GET['HPersediaanProduk']['profil_kayu'])?$_GET['HPersediaanProduk']['profil_kayu']:null;
		$model->kondisi_kayu = isset($_GET['HPersediaanProduk']['kondisi_kayu'])?$_GET['HPersediaanProduk']['kondisi_kayu']:null;
		$model->per_tanggal = isset($_GET['HPersediaanProduk']['per_tanggal'])?$_GET['HPersediaanProduk']['per_tanggal']:null;
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Palet');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockPalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionProdukKeluar(){
		$model = new HPersediaanProduk();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['HPersediaanProduk'];
				$model->tgl_awal = $form_params['HPersediaanProduk']['tgl_awal'];
				$model->tgl_akhir = $form_params['HPersediaanProduk']['tgl_akhir'];
				$model->nomor_produksi = $form_params['HPersediaanProduk']['nomor_produksi'];
				$model->reff_no = $form_params['HPersediaanProduk']['reff_no'];
				$model->cara_keluar = $form_params['HPersediaanProduk']['cara_keluar'];
				$model->produk_nama = $form_params['HPersediaanProduk']['produk_nama'];
				$model->gudang_id = $form_params['HPersediaanProduk']['gudang_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanProdukKeluarDt() ));
		}
		return $this->render('/laporan/produkKeluar/index',['model'=>$model]);
	}
	
	public function actionProdukKeluarPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['HPersediaanProduk'];
		$model->tgl_awal = !empty($_GET['HPersediaanProduk']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['HPersediaanProduk']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['HPersediaanProduk']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['HPersediaanProduk']['tgl_akhir']):"";
		$model->nomor_produksi = $_GET['HPersediaanProduk']['nomor_produksi'];
		$model->cara_keluar = $_GET['HPersediaanProduk']['cara_keluar'];
		$model->produk_nama = $_GET['HPersediaanProduk']['produk_nama'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Produk Keluar');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/produkKeluar/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

    public function actionDetailRandom() {
		if(\Yii::$app->request->isAjax){
            $nomor_produksi = Yii::$app->request->get('nomor_produksi');
            $tgl_awal = Yii::$app->request->get('tgl_awal');
            $tgl_akhir = Yii::$app->request->get('tgl_akhir');

            $sql_nomor_dokumen = "select b.nomor_dokumen
                                    from t_dokumen_penjualan_detail a
                                    join t_dokumen_penjualan b on b.dokumen_penjualan_id = a.dokumen_penjualan_id 
                                    join t_spm_ko_detail c on c.spm_kod_id = a.spm_kod_id
                                    join t_spm_ko d on d.spm_ko_id = c.spm_ko_id
                                    join t_op_ko_random e on e.nomor_produksi = '".$nomor_produksi."'
                                    where e.nomor_produksi = '".$nomor_produksi."'
                                    ";
            $nomor_dokumen = Yii::$app->db->createCommand($sql_nomor_dokumen)->queryScalar();

            if (!empty($nomor_dokumen)) {
                $sql = "select d.produk_nama, b.tanggal, a.reff_no, b.cara_keluar,
                            c.qty_kecil, c.t, c.t_satuan, c.l, c.l_satuan, c.p, c.p_satuan, c.p, c.kubikasi, 
                            f.cust_an_nama
                        from h_persediaan_produk a
                        join t_produk_keluar b on b.nomor_produksi =  '".$nomor_produksi."'
                        join t_op_ko_random c on c.nomor_produksi =   '".$nomor_produksi."'
                        join m_brg_produk d on d.produk_id = a.produk_id                    
                        join t_spm_ko e on e.kode = b.reff_no
                        join m_customer f on f.cust_id = e.cust_id
                        where a.nomor_produksi = '".$nomor_produksi."'
                            and a.reff_no not ilike 'TKO%' 
                            and a.keterangan NOT ILIKE '%MUTASI DARI GUDANG%' 
                            and tgl_transaksi between '".$tgl_awal."' and '".$tgl_akhir."'
                        group by d.produk_nama, b.tanggal, a.reff_no, b.cara_keluar,
                            c.qty_kecil, c.t, c.t_satuan, c.l, c.l_satuan, c.p, c.p_satuan, c.p, c.kubikasi, 
                            f.cust_an_nama
                        ";
            } else {
                $sql = "select e.produk_nama, a.tgl_transaksi as tanggal, a.reff_no, a.keterangan as cara_keluar,
                            d.qty as qty_kecil, d.t, d.t_satuan, d.l, d.l_satuan, d.p, d.p_satuan, d.p, d.kapasitas_kubikasi as kubikasi, 
                            '' as cust_an_nama
                        from h_persediaan_produk a
                        join t_terima_ko c on c.nomor_produksi =   '".$nomor_produksi."'
                        join t_terima_ko_kd d on d.tbko_id = c.tbko_id
                        join m_brg_produk e on e.produk_id = a.produk_id                    
                        where a.nomor_produksi = '".$nomor_produksi."'
                            and c.nomor_produksi = '".$nomor_produksi."'
                            and a.keterangan NOT ILIKE '%MUTASI DARI GUDANG%' 
                            and tgl_transaksi between '".$tgl_awal."' and '".$tgl_akhir."'
                        and a.out_qty_palet > 0
                        group by e.produk_nama, a.tgl_transaksi, a.reff_no, cara_keluar,
                            d.qty, d.t, d.t_satuan, d.l, d.l_satuan, d.p, d.p_satuan, d.p, d.kapasitas_kubikasi, 
                            cust_an_nama
                        ";
            }
            $list = Yii::$app->db->createCommand($sql)->queryAll();
            
            if (!empty($nomor_dokumen)) { 
                $nomor_dokumen = $nomor_dokumen;
            } else {
                $nomor_dokumen = Yii::$app->db->createCommand("select reff_no from h_persediaan_produk where nomor_produksi = '".$nomor_produksi."' and out_qty_palet > 0")->queryScalar();
            }
            //$list = Yii::$app->db->createCommand("select * from t_op_ko_random where op_ko_detail_id = ".$op_ko_detail_id."")->queryAll();
			return $this->renderAjax('/laporan/produkKeluar/_detailRandom',['sql'=>$sql, 'nomor_produksi'=>$nomor_produksi, 'nomor_dokumen'=>$nomor_dokumen, 'list'=>$list]);
        }        
    }
	
	public function actionDeadStock(){
		$model = new HPersediaanProduk();
		$model->produk_group = "Plywood";
		if(\Yii::$app->request->isAjax){
			$data['html'] = '';
			$data['head'] = "";
			if((\Yii::$app->request->get('params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('params'),$form_params); $post = []; $where = [];
				$post['produk_group'] = !empty($form_params['HPersediaanProduk']['produk_group'])?$form_params['HPersediaanProduk']['produk_group']:"";
				$post['produk_nama'] = !empty($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:"";
				$post['jenis_kayu'] = !empty($form_params['HPersediaanProduk']['jenis_kayu'])?$form_params['HPersediaanProduk']['jenis_kayu']:"";
				$post['grade'] = !empty($form_params['HPersediaanProduk']['grade'])?$form_params['HPersediaanProduk']['grade']:"";
				$post['glue'] = !empty($form_params['HPersediaanProduk']['glue'])?$form_params['HPersediaanProduk']['glue']:"";
				$post['profil_kayu'] = !empty($form_params['HPersediaanProduk']['profil_kayu'])?$form_params['HPersediaanProduk']['profil_kayu']:"";
				$post['kondisi_kayu'] = !empty($form_params['HPersediaanProduk']['kondisi_kayu'])?$form_params['HPersediaanProduk']['kondisi_kayu']:"";
				$post['gudang_id'] = !empty($form_params['HPersediaanProduk']['gudang_id'])?$form_params['HPersediaanProduk']['gudang_id']:"";
				$post['produk_nama'] = !empty($form_params['HPersediaanProduk']['produk_nama'])?$form_params['HPersediaanProduk']['produk_nama']:"";
				if(count($post)>0){
					foreach($post as $ii => $w){
						if(!empty($w)){
							if($ii == "gudang_id"){
								$where[$ii] = "h_persediaan_produk.".$ii." = '".$w."'";
							}else{
								$where[$ii] = $ii." = '".$w."'";
							}
						}
					}
					$where = implode(" AND ", $where);
				}
				$sqlhead = "SELECT to_char(t_terima_ko.tanggal, 'YYYY-MM') AS periode, sum(in_qty_palet-out_qty_palet) AS palet, sum(in_qty_kecil-out_qty_kecil) AS pcs
							FROM h_persediaan_produk
							JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
							JOIN t_terima_ko ON t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
							WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
								".(!empty($where)?" AND ".$where:"")."
							GROUP BY 1
							HAVING SUM(in_qty_palet-out_qty_palet) > 0
							ORDER BY 1 DESC";
				$modHead = \Yii::$app->db->createCommand($sqlhead)->queryAll();
				if(!empty($modHead)){
					$data['head'] .= $this->renderPartial('/laporan/deadStock/_head',['modHead'=>$modHead]);
				}
				$sql = "SELECT h_persediaan_produk.produk_id, 
								m_brg_produk.produk_group, 
								m_brg_produk.produk_kode, 
								m_brg_produk.produk_nama, 
								m_brg_produk.produk_dimensi, 
								h_persediaan_produk.gudang_id,
								m_gudang.gudang_nm, 
								sum(in_qty_palet-out_qty_palet) AS palet, 
								sum(in_qty_kecil-out_qty_kecil) AS qty_kecil, 
								in_qty_kecil_satuan, 
								sum(in_qty_m3-out_qty_m3) AS kubikasi
						FROM h_persediaan_produk
						JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
						JOIN m_gudang ON m_gudang.gudang_id = h_persediaan_produk.gudang_id
						WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
							".(!empty($where)?" AND ".$where:"")."
						GROUP BY h_persediaan_produk.produk_id, 
								m_brg_produk.produk_group, 
								m_brg_produk.produk_kode, 
								m_brg_produk.produk_nama, 
								produk_dimensi, 
								h_persediaan_produk.gudang_id, 
								m_gudang.gudang_nm, 
								in_qty_kecil_satuan
						HAVING SUM(in_qty_palet-out_qty_palet) > 0
						ORDER BY h_persediaan_produk.produk_id ASC";
				$mods = \Yii::$app->db->createCommand($sql)->queryAll();
				if(count($mods)>0){
					foreach($mods as $i => $produk){
						$td = '';
						if(isset($modHead)){
							foreach($modHead as $ii => $head){
								$sql = "SELECT h_persediaan_produk.gudang_id, sum(in_qty_palet-out_qty_palet) AS palet, sum(in_qty_kecil-out_qty_kecil) AS qty_kecil FROM h_persediaan_produk 
										JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id
										JOIN t_terima_ko on t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
										WHERE h_persediaan_produk.produk_id = {$produk['produk_id']} AND h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%' AND h_persediaan_produk.gudang_id = {$produk['gudang_id']}
											AND to_char(t_terima_ko.tanggal, 'YYYY-MM') = '{$head['periode']}'
										GROUP BY h_persediaan_produk.gudang_id
										HAVING SUM(in_qty_palet-out_qty_palet) > 0";
								$mod = Yii::$app->db->createCommand($sql)->queryOne();
								$td .= '<td class="td-detail kolom-'.$head['periode'].' detail-palet" style="text-align:right; font-size: 1.1rem; padding-right: 10px;">';
								$td .= (!empty($mod))?$mod['palet']:"-";
								$td .= '</td>';
								$td .= '<td class="td-detail kolom-'.$head['periode'].' detail-pcs" style="text-align:right; font-size: 1.1rem; border-right: solid 1px #999;">';
								$td .= (!empty($mod['qty_kecil']))?\app\components\DeltaFormatter::formatNumberForUserFloat($mod['qty_kecil']):"-";
								$td .= '</td>';
							}
						}
						$data['html'] .= $this->renderPartial('/laporan/deadStock/_item',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where,'td'=>$td]);
					}
					$data['html'] .= $this->renderPartial('/laporan/deadStock/_itemtotal',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where]);
				}
			}
			return $this->asJson($data);
		}
		return $this->render('/laporan/deadStock/index',['model'=>$model]);
	}
	
	public function actionDeadStockPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new HPersediaanProduk();
		$caraprint = Yii::$app->request->get('caraprint');
		
		
		$post['produk_group'] = isset($_GET['HPersediaanProduk']['produk_group'])?$_GET['HPersediaanProduk']['produk_group']:null;
		$post['produk_nama'] = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		$post['jenis_kayu'] = isset($_GET['HPersediaanProduk']['jenis_kayu'])?$_GET['HPersediaanProduk']['jenis_kayu']:null;
		$post['grade'] = isset($_GET['HPersediaanProduk']['grade'])?$_GET['HPersediaanProduk']['grade']:null;
		$post['glue'] = isset($_GET['HPersediaanProduk']['glue'])?$_GET['HPersediaanProduk']['glue']:null;
		$post['profil_kayu'] = isset($_GET['HPersediaanProduk']['profil_kayu'])?$_GET['HPersediaanProduk']['profil_kayu']:null;
		$post['kondisi_kayu'] = isset($_GET['HPersediaanProduk']['kondisi_kayu'])?$_GET['HPersediaanProduk']['kondisi_kayu']:null;
		$post['gudang_id'] = isset($_GET['HPersediaanProduk']['gudang_id'])?$_GET['HPersediaanProduk']['gudang_id']:null;
		$post['produk_nama'] = isset($_GET['HPersediaanProduk']['produk_nama'])?$_GET['HPersediaanProduk']['produk_nama']:null;
		if(count($post)>0){
			foreach($post as $ii => $w){
				if(!empty($w)){
					if($ii == "gudang_id"){
						$where[$ii] = "h_persediaan_produk.".$ii." = '".$w."'";
					}else{
						$where[$ii] = $ii." = '".$w."'";
					}
				}
			}
			$where = implode(" AND ", $where);
		}
		$sqlhead = "SELECT to_char(t_terima_ko.tanggal, 'YYYY-MM') AS periode, sum(in_qty_palet-out_qty_palet) AS palet
					FROM h_persediaan_produk
					JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
					JOIN t_terima_ko ON t_terima_ko.nomor_produksi = h_persediaan_produk.nomor_produksi
					WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
						".(!empty($where)?" AND ".$where:"")."
					GROUP BY 1
					HAVING SUM(in_qty_palet-out_qty_palet) > 0
					ORDER BY 1 DESC";
		$modHead = \Yii::$app->db->createCommand($sqlhead)->queryAll();
        //		if(!empty($modHead)){
        //			$data['head'] .= $this->renderPartial('/laporan/deadStock/_head',['modHead'=>$modHead]);
        //		}
		$sql = "SELECT h_persediaan_produk.produk_id, 
						m_brg_produk.produk_group, 
						m_brg_produk.produk_kode, 
						m_brg_produk.produk_nama, 
						m_brg_produk.produk_dimensi, 
						h_persediaan_produk.gudang_id,
						m_gudang.gudang_nm, 
						sum(in_qty_palet-out_qty_palet) AS palet, 
						sum(in_qty_kecil-out_qty_kecil) AS qty_kecil, 
						in_qty_kecil_satuan, 
						sum(in_qty_m3-out_qty_m3) AS kubikasi
				FROM h_persediaan_produk
				JOIN m_brg_produk ON m_brg_produk.produk_id = h_persediaan_produk.produk_id 
				JOIN m_gudang ON m_gudang.gudang_id = h_persediaan_produk.gudang_id
				WHERE h_persediaan_produk.keterangan NOT ILIKE '%MUTASI DARI GUDANG%'
					".(!empty($where)?" AND ".$where:"")."
				GROUP BY h_persediaan_produk.produk_id, 
						m_brg_produk.produk_group, 
						m_brg_produk.produk_kode, 
						m_brg_produk.produk_nama, 
						produk_dimensi, 
						h_persediaan_produk.gudang_id, 
						m_gudang.gudang_nm, 
						in_qty_kecil_satuan
				HAVING SUM(in_qty_palet-out_qty_palet) > 0
				ORDER BY h_persediaan_produk.produk_id ASC";
		$mods = \Yii::$app->db->createCommand($sql)->queryAll();
        //		if(count($mods)>0){
        //			foreach($mods as $i => $produk){
        //				$data['html'] .= $this->renderPartial('/laporan/deadStock/_item',['model'=>$produk,'modHead'=>$modHead,'i'=>$i,'where'=>$where]);
        //			}
        //		}
                
		$paramprint['judul'] = Yii::t('app', 'Laporan Umur Stock');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2(date('d/m/Y'));
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/deadStock/print',['modHead'=>$modHead,'mods'=>$mods,'paramprint'=>$paramprint]);
		}
	}

	public function actionHvd(){
		$model = new \app\models\TStockopnameHasil();
		return $this->render('/laporan/hvd/index',['model'=>$model]);
	}

    public function actionRekapStockProduk() {
        $model = new \app\models\MBrgProduk();      
        if((\Yii::$app->request->get('laporan_params')) !== null){
            $form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
            $model->attributes = $form_params['MBrgProduk'];
            $model->produk_group = $form_params['MBrgProduk']['produk_group'];
            $data['html'] = $this->renderPartial('/laporan/rekapstockproduk/rekapContent',['model'=>$model]);
            return $this->asJson($data);
        }
        return $this->render('/laporan/rekapstockproduk/index',['model'=>$model]);
    }
    
    public function actionInfoStok($produk_group){
        if(\Yii::$app->request->isAjax){
                $model = $produk_group;
                return $this->renderAjax('/laporan/rekapstockproduk/rekapStock',['produk_group'=>produk_group]);

        }
    }
    
    public function actionRekapStockProdukPrint(){
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\MBrgProduk();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes = $_GET['MBrgProduk'];
        $model->produk_group = !empty($_GET['MBrgProduk']['produk_group'])? $_GET['MBrgProduk']['produk_group']:"";
        $paramprint['judul'] = Yii::t('app', 'Rekap Stock Produk');
        if((!empty($model->produk_group))){
                $paramprint['judul2'] = $model->produk_group;
        }
        if($caraprint == 'PRINT'){
                return $this->renderPartial('/laporan/rekapstockproduk/printRekap',['model'=>$model,'paramprint'=>$paramprint]);
        }else if($caraprint == 'PDF'){
                $pdf = Yii::$app->pdf;
                $pdf->options = ['title' => $paramprint['judul']];
                $pdf->filename = $paramprint['judul'].'.pdf';
                $pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
                $pdf->content = $this->renderPartial('/laporan/rekapstockproduk/printRekap',['model'=>$model,'paramprint'=>$paramprint]);
                return $pdf->render();
        }else if($caraprint == 'EXCEL'){
                return $this->renderPartial('/laporan/rekapstockproduk/printRekap',['model'=>$model,'paramprint'=>$paramprint]);
        }
    }  
	
	public function actionStockRetur(){
		$model = new TReturProdukDetail();
		$model->produk_group = 'Plywood';
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturProdukDetail'];
				$model->produk_nama = $form_params['TReturProdukDetail']['produk_nama'];
				$model->produk_group = $form_params['TReturProdukDetail']['produk_group'];
				$model->jenis_kayu = isset($form_params['TReturProdukDetail']['jenis_kayu'])?$form_params['TReturProdukDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TReturProdukDetail']['grade'])?$form_params['TReturProdukDetail']['grade']:null;
				$model->glue = isset($form_params['TReturProdukDetail']['glue'])?$form_params['TReturProdukDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TReturProdukDetail']['profil_kayu'])?$form_params['TReturProdukDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TReturProdukDetail']['kondisi_kayu'])?$form_params['TReturProdukDetail']['kondisi_kayu']:null;
				$model->per_tanggal = $form_params['TReturProdukDetail']['per_tanggal'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanStockDt() ));
		}
        return $this->render('/laporan/stockRetur/index',['model'=>$model]);
	}

	public function actionStockReturPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TReturProdukDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturProdukDetail'];
		$model->produk_nama = $_GET['TReturProdukDetail']['produk_nama'];
		$model->produk_group = $_GET['TReturProdukDetail']['produk_group'];
		$model->jenis_kayu = $_GET['TReturProdukDetail']['jenis_kayu'];
		$model->grade = $_GET['TReturProdukDetail']['grade'];
		$model->glue = $_GET['TReturProdukDetail']['glue'];
		$model->gudang_id = $_GET['TReturProdukDetail']['gudang_id'];
		$model->per_tanggal = $_GET['TReturProdukDetail']['per_tanggal'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Barang Retur');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );		
		if(!empty($model->produk_group)){
			$paramprint['judul2'] .= "<br>Jenis produk : " . $model->produk_group;
		}
		if(!empty($model->jenis_kayu)){
			$paramprint['judul2'] .= "<br>Jenis kayu : " . implode(", ", $model->jenis_kayu);
		}
		if(!empty($model->grade)){
			$paramprint['judul2'] .= "<br>Grade : " . implode(", ", $model->grade);
		}
		if(!empty($model->glue)){
			$paramprint['judul2'] .= "<br>Glue : " . implode(", ", $model->glue);
		}
		if(!empty($model->produk_nama)){
			$paramprint['judul2'] .= "<br>Nama Produk : " . $model->produk_nama;
		}
		if(!empty($model->gudang_id)){
			$modGudang = \app\models\MGudang::findOne($model->gudang_id);
			$paramprint['judul2'] .= "<br>Gudang : " . $modGudang->gudang_nm;
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionReturblmdikirimgudang(){
		$model = new TReturProdukDetail();
		$model->produk_group = 'Plywood';
		$model->tgl_awal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturProdukDetail'];
				$model->produk_nama = $form_params['TReturProdukDetail']['produk_nama'];
				$model->produk_group = $form_params['TReturProdukDetail']['produk_group'];
				$model->jenis_kayu = isset($form_params['TReturProdukDetail']['jenis_kayu'])?$form_params['TReturProdukDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TReturProdukDetail']['grade'])?$form_params['TReturProdukDetail']['grade']:null;
				$model->glue = isset($form_params['TReturProdukDetail']['glue'])?$form_params['TReturProdukDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TReturProdukDetail']['profil_kayu'])?$form_params['TReturProdukDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TReturProdukDetail']['kondisi_kayu'])?$form_params['TReturProdukDetail']['kondisi_kayu']:null;
				$model->tgl_awal = $form_params['TReturProdukDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TReturProdukDetail']['tgl_akhir'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanReturblmdikirimgudangDt() ));
		}
        return $this->render('/laporan/returblmdikirimgudang/index',['model'=>$model]);
	}
        
	public function actionReturblmdikirimgudangPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TReturProdukDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturProdukDetail'];
		$model->produk_nama = $_GET['TReturProdukDetail']['produk_nama'];
		$model->produk_group = $_GET['TReturProdukDetail']['produk_group'];
		$model->jenis_kayu = $_GET['TReturProdukDetail']['jenis_kayu'];
		$model->grade = $_GET['TReturProdukDetail']['grade'];
		$model->glue = $_GET['TReturProdukDetail']['glue'];
		$model->gudang_id = $_GET['TReturProdukDetail']['gudang_id'];
		$model->tgl_awal = $_GET['TReturProdukDetail']['tgl_awal'];
		$model->tgl_akhir = $_GET['TReturProdukDetail']['tgl_akhir'];
		// $paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Barang Retur Yang Belum Diterima');
		$paramprint['judul'] = Yii::t('app', 'Laporan Permintaan Penanganan Barang Retur Belum Dikirim Oleh Gudang');
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal);	
		} else {
			$paramprint['judul2'] = "Periode Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal) ." sd ". \app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_akhir);
		}	
		if(!empty($model->produk_group)){
			$paramprint['judul2'] .= "<br>Jenis produk : " . $model->produk_group;
		}
		if(!empty($model->jenis_kayu)){
			$paramprint['judul2'] .= "<br>Jenis kayu : " . implode(", ", $model->jenis_kayu);
		}
		if(!empty($model->grade)){
			$paramprint['judul2'] .= "<br>Grade : " . implode(", ", $model->grade);
		}
		if(!empty($model->glue)){
			$paramprint['judul2'] .= "<br>Glue : " . implode(", ", $model->glue);
		}
		if(!empty($model->produk_nama)){
			$paramprint['judul2'] .= "<br>Nama Produk : " . $model->produk_nama;
		}
		if(!empty($model->gudang_id)){
			$modGudang = \app\models\MGudang::findOne($model->gudang_id);
			$paramprint['judul2'] .= "<br>Gudang : " . $modGudang->gudang_nm;
		}
		
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/returblmdikirimgudang/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/returblmdikirimgudang/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/returblmdikirimgudang/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionPermintaanreturblmditerima(){
		$model = new TPengajuanRepackingDetail();
		$model->produk_group = 'Plywood';
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TPengajuanRepackingDetail'];
				$model->produk_nama = $form_params['TPengajuanRepackingDetail']['produk_nama'];
				$model->produk_group = $form_params['TPengajuanRepackingDetail']['produk_group'];
				$model->jenis_kayu = isset($form_params['TPengajuanRepackingDetail']['jenis_kayu'])?$form_params['TPengajuanRepackingDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TPengajuanRepackingDetail']['grade'])?$form_params['TPengajuanRepackingDetail']['grade']:null;
				$model->glue = isset($form_params['TPengajuanRepackingDetail']['glue'])?$form_params['TPengajuanRepackingDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TPengajuanRepackingDetail']['profil_kayu'])?$form_params['TPengajuanRepackingDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TPengajuanRepackingDetail']['kondisi_kayu'])?$form_params['TPengajuanRepackingDetail']['kondisi_kayu']:null;
				$model->gudang_id = isset($form_params['TPengajuanRepackingDetail']['gudang_id'])?$form_params['TPengajuanRepackingDetail']['gudang_id']:null;
				$model->tgl_awal = $form_params['TPengajuanRepackingDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanRepackingDetail']['tgl_akhir'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
        return $this->render('/laporan/permintaanreturblmditerima/index',['model'=>$model]);
	}

	public function actionPermintaanreturblmditerimaPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TPengajuanRepackingDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanRepackingDetail'];
		$model->produk_nama = $_GET['TPengajuanRepackingDetail']['produk_nama'];
		$model->produk_group = $_GET['TPengajuanRepackingDetail']['produk_group'];
		$model->gudang_id = $_GET['TPengajuanRepackingDetail']['gudang_id'];
		$model->tgl_awal = $_GET['TPengajuanRepackingDetail']['tgl_awal'];
		$model->tgl_akhir = $_GET['TPengajuanRepackingDetail']['tgl_akhir'];
		$model->jenis_kayu = $_GET['TPengajuanRepackingDetail']['jenis_kayu'];
		$model->grade = $_GET['TPengajuanRepackingDetail']['grade'];
		$model->glue = $_GET['TPengajuanRepackingDetail']['glue'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Permintaan Penanganan Barang Retur Yang Sudah Dikirim Gudang Belum Diterima PPIC');
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal);	
		} else {
			$paramprint['judul2'] = "Periode Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal) ." sd ". \app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_akhir);
		}
		if(!empty($model->produk_group)){
			$paramprint['judul2'] .= "<br>Jenis produk : " . $model->produk_group;
		}
		if(!empty($model->jenis_kayu)){
			$paramprint['judul2'] .= "<br>Jenis kayu : " . implode(", ", $model->jenis_kayu);
		}
		if(!empty($model->grade)){
			$paramprint['judul2'] .= "<br>Grade : " . implode(", ", $model->grade);
		}
		if(!empty($model->glue)){
			$paramprint['judul2'] .= "<br>Glue : " . implode(", ", $model->glue);
		}
		if(!empty($model->produk_nama)){
			$paramprint['judul2'] .= "<br>Nama Produk : " . $model->produk_nama;
		}
		if(!empty($model->gudang_id)){
			$modGudang = \app\models\MGudang::findOne($model->gudang_id);
			$paramprint['judul2'] .= "<br>Gudang : " . $modGudang->gudang_nm;
		}
			
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/permintaanreturblmditerima/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/permintaanreturblmditerima/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/permintaanreturblmditerima/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionStockreturperpalet(){
		$model = new TReturProdukDetail();
		$model->produk_group = 'Plywood';
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturProdukDetail'];
				$model->produk_nama = $form_params['TReturProdukDetail']['produk_nama'];
				$model->produk_group = $form_params['TReturProdukDetail']['produk_group'];
				$model->jenis_kayu = isset($form_params['TReturProdukDetail']['jenis_kayu'])?$form_params['TReturProdukDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TReturProdukDetail']['grade'])?$form_params['TReturProdukDetail']['grade']:null;
				$model->glue = isset($form_params['TReturProdukDetail']['glue'])?$form_params['TReturProdukDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TReturProdukDetail']['profil_kayu'])?$form_params['TReturProdukDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TReturProdukDetail']['kondisi_kayu'])?$form_params['TReturProdukDetail']['kondisi_kayu']:null;
				$model->per_tanggal = $form_params['TReturProdukDetail']['per_tanggal'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanStockPaletDt() ));
		}
        return $this->render('/laporan/stockreturperpalet/index',['model'=>$model]);
	}

	public function actionStockreturperpaletPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TReturProdukDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturProdukDetail'];
		$model->produk_nama = $_GET['TReturProdukDetail']['produk_nama'];
		$model->produk_group = $_GET['TReturProdukDetail']['produk_group'];
		$model->jenis_kayu = $_GET['TReturProdukDetail']['jenis_kayu'];
		$model->grade = $_GET['TReturProdukDetail']['grade'];
		$model->glue = $_GET['TReturProdukDetail']['glue'];
		$model->gudang_id = $_GET['TReturProdukDetail']['gudang_id'];
		$model->per_tanggal = $_GET['TReturProdukDetail']['per_tanggal'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Persediaan Barang Retur Per Palet');
		$paramprint['judul2'] = "Per Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2( !empty($model->per_tanggal)?$model->per_tanggal:date('d/m/Y') );		
		if(!empty($model->produk_group)){
			$paramprint['judul2'] .= "<br>Jenis produk : " . $model->produk_group;
		}
		if(!empty($model->jenis_kayu)){
			$paramprint['judul2'] .= "<br>Jenis kayu : " . implode(", ", $model->jenis_kayu);
		}
		if(!empty($model->grade)){
			$paramprint['judul2'] .= "<br>Grade : " . implode(", ", $model->grade);
		}
		if(!empty($model->glue)){
			$paramprint['judul2'] .= "<br>Glue : " . implode(", ", $model->glue);
		}
		if(!empty($model->produk_nama)){
			$paramprint['judul2'] .= "<br>Nama Produk : " . $model->produk_nama;
		}
		if(!empty($model->gudang_id)){
			$modGudang = \app\models\MGudang::findOne($model->gudang_id);
			$paramprint['judul2'] .= "<br>Gudang : " . $modGudang->gudang_nm;
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/stockreturperpalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/stockreturperpalet/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockreturperpalet/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionPenerimaanretur(){
		$model = new TReturProdukDetail();
		$model->produk_group = 'Plywood';
		$model->tgl_awal = date('d/m/Y');
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturProdukDetail'];
				$model->produk_nama = $form_params['TReturProdukDetail']['produk_nama'];
				$model->produk_group = $form_params['TReturProdukDetail']['produk_group'];
				$model->jenis_kayu = isset($form_params['TReturProdukDetail']['jenis_kayu'])?$form_params['TReturProdukDetail']['jenis_kayu']:null;
				$model->grade = isset($form_params['TReturProdukDetail']['grade'])?$form_params['TReturProdukDetail']['grade']:null;
				$model->glue = isset($form_params['TReturProdukDetail']['glue'])?$form_params['TReturProdukDetail']['glue']:null;
				$model->profil_kayu = isset($form_params['TReturProdukDetail']['profil_kayu'])?$form_params['TReturProdukDetail']['profil_kayu']:null;
				$model->kondisi_kayu = isset($form_params['TReturProdukDetail']['kondisi_kayu'])?$form_params['TReturProdukDetail']['kondisi_kayu']:null;
				$model->tgl_awal = $form_params['TReturProdukDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TReturProdukDetail']['tgl_akhir'];
				$model->status = isset($form_params['TReturProdukDetail']['status'])?$form_params['TReturProdukDetail']['status']:null;
			}
            return Json::encode(SSP::complex( $model->searchLaporanPenerimaanReturDt() ));
		}
        return $this->render('/laporan/penerimaanretur/index',['model'=>$model]);
	}

	public function actionPenerimaanreturPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TReturProdukDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturProdukDetail'];
		$model->produk_nama = $_GET['TReturProdukDetail']['produk_nama'];
		$model->produk_group = $_GET['TReturProdukDetail']['produk_group'];
		$model->jenis_kayu = $_GET['TReturProdukDetail']['jenis_kayu'];
		$model->grade = $_GET['TReturProdukDetail']['grade'];
		$model->glue = $_GET['TReturProdukDetail']['glue'];
		$model->gudang_id = $_GET['TReturProdukDetail']['gudang_id'];
		$model->tgl_awal = $_GET['TReturProdukDetail']['tgl_awal'];
		$model->tgl_akhir = $_GET['TReturProdukDetail']['tgl_akhir'];
		$model->status = $_GET['TReturProdukDetail']['status'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penerimaan Retur');
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal);	
		} else {
			$paramprint['judul2'] = "Periode Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal) ." sd ". \app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_akhir);
		}		
		if(!empty($model->produk_group)){
			$paramprint['judul2'] .= "<br>Jenis produk : " . $model->produk_group;
		}
		if(!empty($model->jenis_kayu)){
			$paramprint['judul2'] .= "<br>Jenis kayu : " . implode(", ", $model->jenis_kayu);
		}
		if(!empty($model->grade)){
			$paramprint['judul2'] .= "<br>Grade : " . implode(", ", $model->grade);
		}
		if(!empty($model->glue)){
			$paramprint['judul2'] .= "<br>Glue : " . implode(", ", $model->glue);
		}
		if(!empty($model->produk_nama)){
			$paramprint['judul2'] .= "<br>Nama Produk : " . $model->produk_nama;
		}
		if(!empty($model->gudang_id)){
			$modGudang = \app\models\MGudang::findOne($model->gudang_id);
			$paramprint['judul2'] .= "<br>Gudang : " . $modGudang->gudang_nm;
		}
		if(!empty($model->status)){
			$paramprint['judul2'] .= "<br>Status : " . $model->status;
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penerimaanretur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penerimaanretur/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penerimaanretur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionRekapPenangananRetur(){
		$model = new TPengajuanRepacking();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
        if(\Yii::$app->request->get('dt') === 'table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TPengajuanRepacking'];
				$model->tgl_awal = $form_params['TPengajuanRepacking']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanRepacking']['tgl_akhir'];
			}
            return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
        return $this->render('/laporan/rekapPenangananRetur/index',['model'=>$model]);
	}

	public function actionRekapPenangananReturPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new TPengajuanRepacking();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanRepacking'];
		$model->tgl_awal = $_GET['TPengajuanRepacking']['tgl_awal'];
		$model->tgl_akhir = $_GET['TPengajuanRepacking']['tgl_akhir'];
		$paramprint['judul'] = Yii::t('app', 'Rekap Penanganan Barang Retur');
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal);	
		} else {
			$paramprint['judul2'] = "Periode Tanggal ".\app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_awal) ." sd ". \app\components\DeltaFormatter::formatDateTimeForUser2($model->tgl_akhir);
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/rekapPenangananRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/rekapPenangananRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/rekapPenangananRetur/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

}
