<?php

namespace app\modules\gudang\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class PenerimaanreturController extends DeltaBaseController
{
	public $defaultAction = 'index';
	public function actionIndex(){
        $model = new \app\models\TReturProduk();
		if(\Yii::$app->request->isAjax){
			if(\Yii::$app->request->get('dt')=='table-laporan'){
				$param['table']= \app\models\TReturProduk::tableName();
				$param['pk']= \app\models\TReturProduk::primaryKey()[0];
				$param['column'] = ['retur_produk_id',
									$param['table'].'.kode',
									$param['table'].'.tanggal',
									'm_customer.cust_an_nama',
									$param['table'].'.alasan_retur',
									'penerima.pegawai_nama AS petugas_penerima',
									'waktu_terima',
									'security.pegawai_nama AS diperiksa_security',
									'status'];
				$param['where'] = "cancel_transaksi_id IS NULL";
				$param['join'] = "JOIN m_customer ON m_customer.cust_id = t_retur_produk.cust_id
								  LEFT JOIN m_pegawai AS penerima ON penerima.pegawai_id = t_retur_produk.petugas_penerima
								  LEFT JOIN m_pegawai AS security ON security.pegawai_id = t_retur_produk.diperiksa_security";
				$param['order'] = $param['table'].".tanggal DESC, ".$param['table'].".retur_produk_id DESC";
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
        }
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionTerimaRetur($retur_produk_id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\TReturProduk::findOne($retur_produk_id);
			$model->waktu_terima = date('d/m/Y H:i:s');
			$modDetails = \app\models\TReturProdukDetail::find()->where(['retur_produk_id'=>$retur_produk_id])->all();
			if( Yii::$app->request->post('TReturProduk')){
				$transaction = \Yii::$app->db->beginTransaction();
				try {
					$success_1 = FALSE; // t_retur_produk
					$model->load(\Yii::$app->request->post());
					if(!empty($model->waktu_terima)){
						$model->waktu_terima = explode(" ", $model->waktu_terima);
						$model->waktu_terima = $model->waktu_terima[0]." ".$model->waktu_terima[1];
					}
					$model->status = "SUDAH DITERIMA";
					if($model->validate()){
						if($model->save()){
							$success_1 = TRUE;

							foreach ($modDetails as $i => $detail){
								$detail->nomor_produksi = $model->kode . str_pad($i + 1, 4, '0', STR_PAD_LEFT);
								$detail->gudang_id = $_POST['TReturProduk']['gudang_id'];
								$detail->save();
							}
						}
					}
					if ($success_1) {
						$transaction->commit();
						$data['status'] = true;
						$data['callback'] = '$( "#close-btn-modal" ).click(); $("#table-laporan").dataTable().fnClearTable();';
						$data['message'] = Yii::t('app', "Data Berhasil di Simpan");
					} else {
						$transaction->rollback();
						$data['status'] = false;
						(!isset($data['message']) ? $data['message'] = Yii::t('app', \app\components\Params::DEFAULT_FAILED_TRANSACTION_MESSAGE) : '');
						(isset($data['message_validate']) ? $data['message'] = null : '');
					}
				} catch (\yii\db\Exception $ex) {
					$transaction->rollback();
					$data['message'] = $ex;
				}
				return $this->asJson($data);
			}
			return $this->renderAjax('terimaRetur',['model'=>$model,'actionname'=>'terimaRetur','modDetails'=>$modDetails]);
		}
	}
	
	public function actionInfoRetur($retur_produk_id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\TReturProduk::findOne($retur_produk_id);
			$modDetails = \app\models\TReturProdukDetail::find()->where(['retur_produk_id'=>$retur_produk_id])->all();
			return $this->renderAjax('infoRetur',['model'=>$model,'modDetails'=>$modDetails]);
		}
	}

	public function actionCetakLabel(){
		$this->layout = '@views/layouts/metronic/print';
		$modelDet = \app\models\TReturProdukDetail::findOne($_GET['id']);
		$model =  \app\models\TReturProduk::findOne($modelDet->retur_produk_id);
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'PRODUCT DETAILS');
		if($caraprint == 'PRINT'){
			return $this->render('@app/modules/gudang/views/penerimaanretur/cetakLabel',['model'=>$model,'paramprint'=>$paramprint, 'modelDet'=>$modelDet]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('@app/modules/gudang/views/penerimaanretur/cetakLabel',['model'=>$model,'paramprint'=>$paramprint, 'modelDet'=>$modelDet]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('@app/modules/gudang/views/penerimaanretur/cetakLabel',['model'=>$model,'paramprint'=>$paramprint, 'modelDet'=>$modelDet]);
		}
	}
}
