<?php
namespace app\components;

use Yii;

Class Params{
	
    const DEFAULT_LANGUAGE = 'id'; // Indonesia

	const DEFAULT_PPN = 0.11; // 11% per 1 april 2022
    const DEFAULT_LABEL_PPN = '11%';

    const DEFAULT_SUCCESS_TRANSACTION_MESSAGE = 'Transaksi Berhasil';
    const DEFAULT_FAILED_TRANSACTION_MESSAGE = 'Transaksi Gagal :(';
    const DEFAULT_CONFIRM_DELETE_MESSAGE = 'Apakah anda yakin akan menghapus ini ?';
    const DEFAULT_DELETE_RESTRICT_MESSAGE = 'Opss.. Untuk menjaga integritas data, data ini TIDAK dapat dihapus karena data ini masih dipakai di data lain';
	
	const USER_GROUP_ID_SUPER_USER = 1;
	const USER_GROUP_ID_ADMINISTRATOR = 2;
	const USER_GROUP_ID_KADEP_FINNACC = 31;
	const USER_GROUP_ID_STAFF_FINNACC = 32;
	const USER_GROUP_ID_KADIV_FINNACC = 47;
	const USER_GROUP_ID_OWNER = 63;
	const USER_GROUP_ID_PPIC_STAFF = 11;
	const USER_GROUP_ID_PPIC_KADEP = 10;
	const USER_GROUP_ID_PPIC_TALLY = 83;
	const USER_GROUP_ID_ADMIN_MKT = 77;
	const USER_GROUP_ID_KANIT_LOG_SENGON = 78;
	const USER_GROUP_ID_STAFF_LOG_SENGON = 41;
	const USER_GROUP_ID_KANIT_LOG_ALAM = 36;
	const USER_GROUP_ID_STAFF_LOG_ALAM = 26;
        const USER_GROUP_ID_KADEP_LOGISTIC = 61;
        const USER_GROUP_ID_KANIT_LOGISTIC = 99;
	const USER_GROUP_ID_STAFF_LOHISTIC = 39;
	const USER_GROUP_ID_KADEP_ACC = 75;
	const USER_GROUP_ID_DIREKTUR = 131;
	const USER_GROUP_ID_DIREKTUR_UTAMA = 42;
	const USER_GROUP_ID_GM_OPERASIONAL = 67;
	const USER_GROUP_ID_LAPORAN_MANAGEMENT = 92;    
	const USER_GROUP_ID_KADIV_QMS = 29;    
	const USER_GROUP_ID_STAFF_QMS = 30;
	const USER_GROUP_ID_STAFF_HRD = 24;
	const USER_GROUP_ID_KADEP_HRD = 62;
	const USER_GROUP_ID_KADIV_HRGA = 25;

	const MENU_GROUP_ID_KONFIGURASI = 5;
    
	const MODULE_ID_ADMINISTRATOR = 1;
	
	const DEPARTEMENT_ID_LOGISTIC = 107;
	const DEPARTEMENT_ID_MARKETING = 116;
	const DEPARTEMENT_ID_SECURITY = 115;
	const DEPARTEMENT_ID_GA = 105;
	const DEPARTEMENT_ID_QC_PLYMILL = 129;
	const DEPARTEMENT_ID_PURCH_LOG = 114;
	const DEPARTEMENT_ID_PCH = 113;
	const DEPARTEMENT_ID_PPIC = 110;
	const DEPARTEMENT_ID_FIN = 117;
	const DEPARTEMENT_ID_TOP_MANAGEMENT = 119;
	const DEPARTEMENT_ID_RND = 133;
	const DEPARTEMENT_ID_PLYMILL = 120;
        
    const DEFAULT_PRODUK_SATUAN_BESAR = 'Palet';
    const DEFAULT_PRODUK_SATUAN_KECIL = 'Pcs';
    const DEFAULT_PRODUK_SATUAN_DIMENSI = 'mm';
    const DEFAULT_DESTINASI_PENJUALAN = 'lokal';
    const DEFAULT_SATUAN_PENJUALAN_PRODUK = 'm3';
    
	const DEFAULT_COMPANY_PROFILE = 1;
	const DEFAULT_PEGAWAI_ID_DIREKTUR_UTAMA = 59;
	const DEFAULT_PEGAWAI_ID_DIREKTUR_MANUFAKTUR = 22;// 6 (AW) diganti 22(aseng)
	const DEFAULT_PEGAWAI_ID_KANIT_GRADER = 131;
	const DEFAULT_PEGAWAI_ID_PAK_WID = 56;
	const DEFAULT_PEGAWAI_ID_BU_ERA = 88;
	const DEFAULT_PEGAWAI_ID_ERNA = 63;
	const DEFAULT_PEGAWAI_ID_MBAK_ONNY = 71;
        const DEFAULT_PEGAWAI_ID_AGUNG_ENGINERING = 95;
	const DEFAULT_PEGAWAI_ID_ANNEKE = 14;
	const DEFAULT_PEGAWAI_ID_JENNY_CHANDRA = 123;
	const DEFAULT_PEGAWAI_ID_AGUS_SOEWITO = 59;
	const DEFAULT_PEGAWAI_ID_IWAN_SULISTYO = 19;
	const DEFAULT_PEGAWAI_ID_FINEKE_DEWI = 29;
	const DEFAULT_PEGAWAI_ID_EKO_NOWO = 58;
	const DEFAULT_PEGAWAI_ID_ELLY = 61;
	const DEFAULT_PEGAWAI_ID_FITRIYANAH = 8;
	const DEFAULT_PEGAWAI_ID_LINGGA = 10;
	const DEFAULT_PEGAWAI_ID_ALFI = 130;
	const DEFAULT_PEGAWAI_ID_RYA = 102;
	const DEFAULT_PEGAWAI_ID_BUDI_ADHI = 75;
	const DEFAULT_PEGAWAI_ID_NADLIM = 1481;
	const DEFAULT_PEGAWAI_ID_PRANOTO = 3006;
        
	const DEFAULT_PEGAWAI_ID_ILHAM = 18;
	const DEFAULT_PEGAWAI_ID_SEKAR = 25;
	const DEFAULT_PEGAWAI_ID_ASENG = 22;
	const DEFAULT_PEGAWAI_ID_AGUS_WIBOWO = 6; 
	const DEFAULT_PEGAWAI_ID_TATANG = 3364;
	const DEFAULT_PEGAWAI_ID_SUPRIYADI_INTERNALCONTROL = 3487;
        
    const DEFAULT_PEGAWAI_ID_AHMAD_SOBIRIN = 367;
    const DEFAULT_PEGAWAI_ID_JUMARI = 543;
    const DEFAULT_PEGAWAI_ID_TRI_HANDAYANTA = 2147;
    const DEFAULT_PEGAWAI_ID_ROSA_OKTAVIA_ARDANI = 1734;
    const DEFAULT_PEGAWAI_ID_ROCHANDRA = 21;
    const DEFAULT_PEGAWAI_ID_RUSDIANTO = 1616;
    const DEFAULT_PEGAWAI_ID_SONI_DWI = 132;
    const DEFAULT_PEGAWAI_ID_AGUSTINA_SRI_HARTATIK= 98; 
    const DEFAULT_PEGAWAI_ID_SRI_RAHAYUNINGSIH = 5; 
    const DEFAULT_PEGAWAI_ID_NAFIS = 1835;
	const DEFAULT_PEGAWAI_ID_YOSUA = 52;
	const DEFAULT_PEGAWAI_ID_SEAN_SUTRISNO = 5479;
	const DEFAULT_PEGAWAI_ID_UMAMI = 1409;

	const DEFAULT_GRADERLOG_ID_GRADER_JOKO_MULYONO = 14;
	
	const DEFAULT_SUPPLIER_ID_SPL = 10;
    
	const DEFAULT_KAYU_ID_SENGON = 29;
	const DEFAULT_KAYU_ID_JABON = 24;

	const DEFAULT_PEGAWAI_ID_KADEP_SAWMILL = 34;
	const DEFAULT_PEGAWAI_ID_KADEP_PPIC = 1835;
	const DEFAULT_PEGAWAI_ID_KADIV_OPERASIONAL = 18;
	const DEFAULT_PEGAWAI_ID_KADIV_MKT = 19;
	
        
//	====================== START AKUNTANSI ================================ //
	const ACCT_JURNAL_STATUS_UNPOSTED = "UNPOSTED";
	const ACCT_JURNAL_STATUS_POSTED = "POSTED";
	const ACCT_JURNAL_STATUS_CLOSED = "CLOSED";
	
	const ACCT_SETUP_PEMBELIAN_NON_PPN_ATK = 24;
	const ACCT_SETUP_PEMBELIAN_NON_PPN_BOP = 25;
	const ACCT_SETUP_PEMBELIAN_NON_PPN_CETAKAN = 26;
	const ACCT_SETUP_PEMBELIAN_NON_PPN_RT = 27;
	
	const ACCT_SETUP_PEMBELIAN_PPN_ATK = 31;
	const ACCT_SETUP_PEMBELIAN_PPN_BOP = 32;
	const ACCT_SETUP_PEMBELIAN_PPN_CETAKAN = 33;
	const ACCT_SETUP_PEMBELIAN_PPN_RT = 34;
	
	const ACCT_SETUP_PEMBAYARAN_BOP_TRANSFER = 58;
	const ACCT_SETUP_PEMBAYARAN_ATK_TRANSFER = 59;
	const ACCT_SETUP_PEMBAYARAN_PERLENGKAPAN_TUNAI = 68;
	
	const ACCT_REKENING_DEBET_ATK = 51;
	const ACCT_REKENING_DEBET_RT = 50;
	const ACCT_REKENING_DEBET_CETAKAN = 52;
	const ACCT_REKENING_DEBET_BP_BOP = 49;
	const ACCT_REKENING_DEBET_PPN_MASUKAN = 146;
	const ACCT_REKENING_DEBET_PPN_BELUM_FAKTUR = 148;
	
	const ACCT_REKENING_KREDIT_PEMBAYARAN_BP = 189;
	
	const DANA_TETAP_KAS_KECIL = 60000000; //Per tanggal 08 juli 2021 di tambah menjadi 100juta
    const DANA_TETAP_KAS_KECIL_TAMBAH_40JUTA = 40000000; //berkalu per tanggal 2021-07-08 di tambah menjadi 100juta
    const DANA_TETAP_KAS_KECIL_MINUS_40JUTA = 40000000; //berkalu per tanggal 2021-07-19 di Kurangi 40Jt menjadi 60juta lagi
//	====================== END AKUNTANSI ================================ //
	
	const NOMOR_SERTIFIKAT_FSC = "SCS-COC-009423";
	const PIC_TTD_SHIPPING = "Sean Sutrisno";

	
	// DEFAULT PEGAWAI ID UNTUK LAP. BUDGETING
	const DEFAULT_PEGAWAI_ID_ELIEN = 12;
	const DEFAULT_PEGAWAI_ID_LEGAWATI = 5803;
	const DEFAULT_PEGAWAI_ID_KADIV_QMS = 129;
	const DEFAULT_PEGAWAI_ID_SUPERUSER_DENNY = 84;
	const DEFAULT_PEGAWAI_ID_SUPERUSER_AGUS = 85;
	const DEFAULT_PEGAWAI_ID_SUPERUSER_WAHYU_A = 5699;

	const DEFAULT_PEGAWAI_ID_BUDGETING = [
					self::DEFAULT_PEGAWAI_ID_JENNY_CHANDRA,
					self::DEFAULT_PEGAWAI_ID_YOSUA,
					self::DEFAULT_PEGAWAI_ID_RUSDIANTO,
					self::DEFAULT_PEGAWAI_ID_EKO_NOWO,
					self::DEFAULT_PEGAWAI_ID_AGUS_SOEWITO,
					self::DEFAULT_PEGAWAI_ID_ASENG,
					self::DEFAULT_PEGAWAI_ID_LEGAWATI,
					self::DEFAULT_PEGAWAI_ID_ELIEN,
					self::DEFAULT_PEGAWAI_ID_KADIV_QMS,
					self::DEFAULT_PEGAWAI_ID_SUPERUSER_DENNY,
					self::DEFAULT_PEGAWAI_ID_SUPERUSER_AGUS,
					self::DEFAULT_PEGAWAI_ID_SUPERUSER_WAHYU_A,
				];
	
    public static function urlModal(){
        return \yii\helpers\Url::toRoute('apps/createmodals');
    }
}