<?php

namespace app\modules\qc\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionDefectswm(){
		$model = new \app\models\TDefectSwm();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TDefectSwm'];
				$model->tgl_awal = $form_params['TDefectSwm']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDefectSwm']['tgl_akhir'];
                $model->kategori_defect = $form_params['TDefectSwm']['kategori_defect'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/defectswm/index',['model'=>$model]);
	}

    public function actionDefectswmPrint(){
        $this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDefectSwm();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes      = $_GET['TDefectSwm'];
        $model->tgl_awal        = !empty($_GET['TDefectSwm']['tgl_awal'])?$_GET['TDefectSwm']['tgl_awal']:"";
        $model->tgl_akhir       = !empty($_GET['TDefectSwm']['tgl_akhir'])?$_GET['TDefectSwm']['tgl_akhir']:"";
        $model->kategori_defect = !empty($_GET['TDefectSwm']['kategori_defect'])?$_GET['TDefectSwm']['kategori_defect']:"";
		$paramprint['judul']    = Yii::t('app', 'Laporan Defect Sawmill');
        if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/defectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/defectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/defectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
    }

    public function actionLosstimeswm(){
		$model = new \app\models\TLosstimeSwm();
		$model->tgl_awal = date('d/m/Y');
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLosstimeSwm'];
				$model->tgl_awal = $form_params['TLosstimeSwm']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLosstimeSwm']['tgl_akhir'];
                $model->kategori_losstime = $form_params['TLosstimeSwm']['kategori_losstime'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/losstimeswm/index',['model'=>$model]);
	}

    public function actionLosstimeswmPrint(){
        $this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLosstimeSwm();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes      = $_GET['TLosstimeSwm'];
        $model->tgl_awal        = !empty($_GET['TLosstimeSwm']['tgl_awal'])?$_GET['TLosstimeSwm']['tgl_awal']:"";
        $model->tgl_akhir       = !empty($_GET['TLosstimeSwm']['tgl_akhir'])?$_GET['TLosstimeSwm']['tgl_akhir']:"";
        $model->kategori_losstime = !empty($_GET['TLosstimeSwm']['kategori_losstime'])?$_GET['TLosstimeSwm']['kategori_losstime']:"";
		$paramprint['judul']    = Yii::t('app', 'Laporan Losstime Sawmill');
        if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/losstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/losstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/losstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
    }

    public function actionRekapDefectswm(){
        $model = new \app\models\TDefectSwm();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TDefectSwm'];
                $model->tgl_awal = $form_params['TDefectSwm']['tgl_awal'];
                $model->tgl_akhir = $form_params['TDefectSwm']['tgl_akhir'];
                $model->kategori_defect = $form_params['TDefectSwm']['kategori_defect'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanRekapDt()));
		}
		return $this->render('/laporan/rekapDefectswm/index', ['model' => $model]);
    }

    public function actionRekapDefectswmPrint(){
        $this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDefectSwm();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes      = $_GET['TDefectSwm'];
        $model->tgl_awal        = !empty($_GET['TDefectSwm']['tgl_awal'])?$_GET['TDefectSwm']['tgl_awal']:"";
        $model->tgl_akhir       = !empty($_GET['TDefectSwm']['tgl_akhir'])?$_GET['TDefectSwm']['tgl_akhir']:"";
        $model->kategori_defect = !empty($_GET['TDefectSwm']['kategori_defect'])?$_GET['TDefectSwm']['kategori_defect']:"";
		$paramprint['judul']    = Yii::t('app', 'Rekap Defect Sawmill');
        if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/rekapDefectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/rekapDefectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/rekapDefectswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
    }

    public function actionRekapLosstimeswm(){
        $model = new \app\models\TLosstimeSwm();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TLosstimeSwm'];
                $model->tgl_awal = $form_params['TLosstimeSwm']['tgl_awal'];
                $model->tgl_akhir = $form_params['TLosstimeSwm']['tgl_akhir'];
                $model->kategori_losstime = $form_params['TLosstimeSwm']['kategori_losstime'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanRekapDt()));
		}
		return $this->render('/laporan/rekapLosstimeswm/index', ['model' => $model]);
    }

    public function actionRekapLosstimeswmPrint(){
        $this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLosstimeSwm();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes      = $_GET['TLosstimeSwm'];
        $model->tgl_awal        = !empty($_GET['TLosstimeSwm']['tgl_awal'])?$_GET['TLosstimeSwm']['tgl_awal']:"";
        $model->tgl_akhir       = !empty($_GET['TLosstimeSwm']['tgl_akhir'])?$_GET['TLosstimeSwm']['tgl_akhir']:"";
        $model->kategori_losstime = !empty($_GET['TLosstimeSwm']['kategori_losstime'])?$_GET['TLosstimeSwm']['kategori_losstime']:"";
		$paramprint['judul']    = Yii::t('app', 'Rekap Losstime Sawmill');
        if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u>";
		}else{
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u>";
		}
		if($caraprint == 'PRINT'){
			return $this->render('/laporan/rekapLosstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/rekapLosstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('/laporan/rekapLosstimeswm/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
    }
}