<?php

namespace app\modules\finance\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionPembayaranTbp(){
		$model = new \app\models\TTerimaBhp();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TTerimaBhp'];
				$model->tgl_awal = $form_params['TTerimaBhp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TTerimaBhp']['tgl_akhir'];
				$model->terimabhp_kode = $form_params['TTerimaBhp']['terimabhp_kode'];
				$model->kode_voucher = $form_params['TTerimaBhp']['kode_voucher'];
				$model->nofaktur = $form_params['TTerimaBhp']['nofaktur'];
				$model->suplier_id = $form_params['TTerimaBhp']['suplier_id'];
//				$model->payment_status = $form_params['TTerimaBhp']['payment_status'];
				$model->bhp_id = $form_params['TTerimaBhp']['bhp_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/pembayarantbp/index',['model'=>$model]);
	}
	
	public function actionPembayaranTbpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhp'];
		$model->tgl_awal = !empty($_GET['TTerimaBhp']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhp']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_akhir']):"";
		$model->terimabhp_kode = $_GET['TTerimaBhp']['terimabhp_kode'];
		$model->kode_voucher = $_GET['TTerimaBhp']['kode_voucher'];
		$model->nofaktur = $_GET['TTerimaBhp']['nofaktur'];
		$model->suplier_id = $_GET['TTerimaBhp']['suplier_id'];
//		$model->payment_status = $_GET['TTerimaBhp']['payment_status'];
		$model->bhp_id = $_GET['TTerimaBhp']['bhp_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pembayaran Bahan Pembantu Produksi');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionVoucherPengeluaran(){
		$model = new \app\models\TVoucherPengeluaran();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TVoucherPengeluaran'];
				$model->tgl_awal = $form_params['TVoucherPengeluaran']['tgl_awal'];
				$model->tgl_akhir = $form_params['TVoucherPengeluaran']['tgl_akhir'];
				$model->kode = $form_params['TVoucherPengeluaran']['kode'];
				$model->tipe = $form_params['TVoucherPengeluaran']['tipe'];
				$model->status_bayar = $form_params['TVoucherPengeluaran']['status_bayar'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/voucherPengeluaran/index',['model'=>$model]);
	}
	
	public function actionVoucherPengeluaranPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TVoucherPengeluaran();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TVoucherPengeluaran'];
		$model->tgl_awal = !empty($_GET['TVoucherPengeluaran']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TVoucherPengeluaran']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_akhir']):"";
		$model->kode = $_GET['TVoucherPengeluaran']['kode'];
		$model->tipe = $_GET['TVoucherPengeluaran']['tipe'];
		$model->status_bayar = $_GET['TVoucherPengeluaran']['status_bayar'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Voucher Pengeluaran');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionTagihanSuplier(){
		$model = new \app\models\TTerimaBhpDetail();
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TTerimaBhpDetail'];
				$model->per_tanggal = $form_params['TTerimaBhpDetail']['per_tanggal'];
				$model->suplier_id = $form_params['TTerimaBhpDetail']['suplier_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanTagihanSuplierDt() ));
		}
		if((\Yii::$app->request->post('getTotalSemua')) !== null){
			$form_params = []; parse_str(\Yii::$app->request->post('laporan_params'),$form_params); 
			$model->suplier_id = $form_params['TTerimaBhpDetail']['suplier_id'];
			$sql = $model->searchLaporanTagihanSuplier()->createCommand()->rawSql;
			$contents = Yii::$app->db->createCommand($sql)->queryAll();
			$data['totaltagihan'] = 0; $data['paid'] = 0; $data['hutang'] = 0;
			if(count($contents)>0){
				foreach($contents as $i => $content){
					$data['totaltagihan'] += $content['totaltagihan'];
					$data['paid'] += $content['paid'];
					$data['hutang'] += $content['hutang'];
				}
			}
			return $this->asJson($data);
		}
		if(\Yii::$app->request->get('show')=='tbp'){
			$suplier_id = \Yii::$app->request->get('suplier_id');
			$modSuplier = \app\models\MSuplier::findOne($suplier_id);
			if(\Yii::$app->request->get('dt')=='table-show'){
				$param['table']= \app\models\TTerimaBhp::tableName();
				$param['pk']= $param['table'].'.'.\app\models\TTerimaBhp::primaryKey()[0];
				$param['column'] = [ $param['table'].'.terima_bhp_id', 'tglterima','terimabhp_kode','spo_kode', 'nofaktur', 'totalbayar', 'status_bayar', 'tanggal_bayar', 't_spo.spo_id', 't_voucher_pengeluaran.kode', 't_terima_bhp.voucher_pengeluaran_id'];
				$param['join']= ['LEFT JOIN t_spo ON t_spo.spo_id = t_terima_bhp.spo_id
								  LEFT JOIN t_voucher_pengeluaran ON t_voucher_pengeluaran.voucher_pengeluaran_id = t_terima_bhp.voucher_pengeluaran_id
								'];
				$param['where'] = $param['table'].".cancel_transaksi_id IS NULL AND ".$param['table'].".spo_id IS NOT NULL AND ".$param['table'].".suplier_id = ".$suplier_id;
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('/laporan/tagihanSuplier/showTbp',['modSuplier'=>$modSuplier]);
		}
		return $this->render('/laporan/tagihanSuplier/index',['model'=>$model]);
	}
	
	public function actionTagihanSuplierPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhpDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhpDetail'];
		$model->tgl_awal = !empty($_GET['TTerimaBhpDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhpDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TTerimaBhpDetail']['suplier_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Tagihan Suplier BHP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionKuitansi(){
		$model = new \app\models\TKuitansi();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKuitansi'];
				$model->tgl_awal = $form_params['TKuitansi']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKuitansi']['tgl_akhir'];
				$model->cara_bayar = $form_params['TKuitansi']['cara_bayar'];
				$model->terima_dari = $form_params['TKuitansi']['terima_dari'];
				$model->untuk_pembayaran = $form_params['TKuitansi']['untuk_pembayaran'];
				
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/kuitansi/index',['model'=>$model]);
	}
	
	public function actionKuitansiPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKuitansi();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKuitansi'];
		$model->tgl_awal = !empty($_GET['TKuitansi']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKuitansi']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKuitansi']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKuitansi']['tgl_akhir']):"";
		$model->cara_bayar = $_GET['TKuitansi']['cara_bayar'];
		$model->terima_dari = $_GET['TKuitansi']['terima_dari'];
		$model->untuk_pembayaran = $_GET['TKuitansi']['untuk_pembayaran'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Kuitansi Penerimaan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
