<?php

namespace app\modules\exim\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{
    public function actionRekapPenjualan()
    {
        $model = new \app\models\TInvoice();
        $model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
        $model->tgl_akhir = date('d/m/Y');
        if (\Yii::$app->request->get('dt') == 'table-laporan') {
            if ((\Yii::$app->request->get('laporan_params')) !== null) {
                $form_params = [];
                parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
                $model->attributes = $form_params['TInvoice'];
                $model->tgl_awal = $form_params['TInvoice']['tgl_awal'];
                $model->tgl_akhir = $form_params['TInvoice']['tgl_akhir'];
                $model->term_of_price = $form_params['TInvoice']['term_of_price'];
                $model->payment_method = $form_params['TInvoice']['payment_method'];
                $model->cust_id = $form_params['TInvoice']['cust_id'];
            }
            return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
        }
        return $this->render('/laporan/rekapPenjualan/index', ['model' => $model]);
    }

    public function actionRekapPenjualanPrint()
    {
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\TInvoice();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes = $_GET['TInvoice'];
        $model->tgl_awal = !empty($_GET['TInvoice']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TInvoice']['tgl_awal']) : "";
        $model->tgl_akhir = !empty($_GET['TInvoice']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TInvoice']['tgl_akhir']) : "";
        $model->term_of_price = !empty($_GET['TInvoice']['term_of_price']) ? $_GET['TInvoice']['term_of_price'] : "";
        $model->cust_id = !empty($_GET['TInvoice']['cust_id']) ? $_GET['TInvoice']['cust_id'] : "";
        $model->payment_method = !empty($_GET['TInvoice']['payment_method']) ? $_GET['TInvoice']['payment_method'] : "";
        $paramprint['judul'] = Yii::t('app', 'Laporan Rekapitulasi Penjualan Export');
        if ($model->tgl_awal == $model->tgl_akhir) {
            $paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
        } else {
            $paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
        }
        if ($caraprint == 'PRINT') {
            return $this->render('/laporan/rekapPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/rekapPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/rekapPenjualan/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
    }


    public function actionMonitoringOrder()
    {
        $model = new \app\models\TOpExport();
        $model->year = date("Y");
        if (\Yii::$app->request->isAjax) {
            $form_params = [];
            parse_str(\Yii::$app->request->post('formData'), $form_params);
            $data['html'] = "";
            if (isset($form_params['TOpExport'])) {
                $tgl_awal = "";
                $tgl_akhir = "";
                if (!empty($form_params['TOpExport']['year'])) {
                    $tgl_awal = $form_params['TOpExport']['year'] . "-01-01";
                    $tgl_akhir = $form_params['TOpExport']['year'] . "-12-31";
                }
                $sqlop = "SELECT *,m_customer.cust_an_nama FROM t_op_export 
						JOIN m_customer ON m_customer.cust_id = t_op_export.cust_id
						WHERE cancel_transaksi_id IS NULL 
						" . ((!empty($tgl_awal) && !empty($tgl_akhir)) ? "AND tanggal BETWEEN '" . $tgl_awal . "' AND '" . $tgl_akhir . "'" : "") . " 
						" . (!empty($form_params['TOpExport']['cust_id']) ? "AND t_op_export.cust_id = " . $form_params['TOpExport']['cust_id'] : "") . " 
						ORDER BY tanggal DESC";
                $modOPs = \Yii::$app->db->createCommand($sqlop)->queryAll();
                if (count($modOPs) > 0) {
                    foreach ($modOPs as $i => $op) {
                        $sqldetail = "SELECT detail_order FROM t_op_export where op_export_id = " . $op['op_export_id'];
                        $modDetails = \Yii::$app->db->createCommand($sqldetail)->queryOne();
                        if (count($modDetails) > 0) {
                            $modDetails = \yii\helpers\Json::decode($modDetails['detail_order']);
                            foreach ($modDetails as $ii => $detail) {
                                $data['html'] .= $this->renderPartial('monitoringOrder/_item', [
                                    'op' => $op,
                                    'detail' => $detail,
                                    'modOPs' => $modOPs,
                                    'i' => $i, 'ii' => $ii
                                ]);
                            }
                        }
                    }
                }
            }
            return $this->asJson($data);
        }
        return $this->render('/laporan/monitoringOrder/index', ['model' => $model]);
    }

    public function actionMonitoringOrderPrint()
    {
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\TOpExport();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes = $_GET['TOpExport'];
        $model->year = !empty($_GET['TOpExport']['year']) ? $_GET['TOpExport']['year'] : "";
        $model->cust_id = $_GET['TOpExport']['cust_id'];
        if (!empty($model->year)) {
            $paramprint['judul2'] = "Tahun " . $model->year;
        }
        $tgl_awal = "";
        $tgl_akhir = "";
        if (!empty($_GET['TOpExport']['year'])) {
            $tgl_awal = $_GET['TOpExport']['year'] . "-01-01";
            $tgl_akhir = $_GET['TOpExport']['year'] . "-12-31";
        }
        $sqlop = "SELECT *,m_customer.cust_an_nama FROM t_op_export 
				JOIN m_customer ON m_customer.cust_id = t_op_export.cust_id
				WHERE cancel_transaksi_id IS NULL 
				" . ((!empty($tgl_awal) && !empty($tgl_akhir)) ? "AND tanggal BETWEEN '" . $tgl_awal . "' AND '" . $tgl_akhir . "'" : "") . " 
				" . (!empty($model->cust_id) ? "AND t_op_export.cust_id = " . $model->cust_id : "") . " 
				ORDER BY tanggal DESC";
        $model = \Yii::$app->db->createCommand($sqlop)->queryAll();
        $paramprint['judul'] = Yii::t('app', 'Laporan Monitoring Order Export');
        if ($caraprint == 'PRINT') {
            return $this->render('/laporan/monitoringOrder/print', ['model' => $model, 'paramprint' => $paramprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/monitoringOrder/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/monitoringOrder/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
    }

    public function actionStuffingExport()
    {
        $model = new \app\models\TSpmKo();
        $model->tgl_awal = "01/01/" . date('Y');
        $model->tgl_akhir = date('d/m/Y');
        if (\Yii::$app->request->get('dt') == 'table-laporan') {
            if ((\Yii::$app->request->get('laporan_params')) !== null) {
                $form_params = [];
                parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
                $model->attributes = $form_params['TSpmKo'];
                $model->tgl_awal = $form_params['TSpmKo']['tgl_awal'];
                $model->tgl_akhir = $form_params['TSpmKo']['tgl_akhir'];
                $model->cust_id = $form_params['TSpmKo']['cust_id'];
                $model->jenis_produk = $form_params['TSpmKo']['jenis_produk'];
                $model->no_inv = $form_params['TSpmKo']['no_inv'];
            }
            return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanStuffingDt()));
        }
        return $this->render('/laporan/stuffingExport/index', ['model' => $model]);
    }

    public function actionStuffingExportPrint()
    {
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\TSpmKo();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes = $_GET['TSpmKo'];
        $model->tgl_awal = !empty($_GET['TSpmKo']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpmKo']['tgl_awal']) : "";
        $model->tgl_akhir = !empty($_GET['TSpmKo']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpmKo']['tgl_akhir']) : "";
        $model->cust_id = !empty($_GET['TSpmKo']['cust_id']) ? $_GET['TSpmKo']['cust_id'] : "";
        $model->jenis_produk = !empty($_GET['TSpmKo']['jenis_produk']) ? $_GET['TSpmKo']['jenis_produk'] : "";
        $model->no_inv = !empty($_GET['TSpmKo']['no_inv']) ? $_GET['TSpmKo']['no_inv'] : "";
        $paramprint['judul'] = Yii::t('app', 'Laporan Stuffing Export');
        if ($model->tgl_awal == $model->tgl_akhir) {
            $paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
        } else {
            $paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
        }
        if ($caraprint == 'PRINT') {
            return $this->render('/laporan/stuffingExport/print', ['model' => $model, 'paramprint' => $paramprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/stuffingExport/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/stuffingExport/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
    }

    public function actionStuffingDetail()
    {
        $model = new \app\models\TSpmKoDetail();
        $model->tgl_awal = "01/01/" . date('Y');
        $model->tgl_akhir = date('d/m/Y');
        if (\Yii::$app->request->get('dt') == 'table-laporan') {
            if ((\Yii::$app->request->get('laporan_params')) !== null) {
                $form_params = [];
                parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
                $model->attributes = $form_params['TSpmKoDetail'];
                $model->tgl_awal = $form_params['TSpmKoDetail']['tgl_awal'];
                $model->tgl_akhir = $form_params['TSpmKoDetail']['tgl_akhir'];
                $model->cust_id = $form_params['TSpmKoDetail']['cust_id'];
                $model->jenis_produk = $form_params['TSpmKoDetail']['jenis_produk'];
                $model->no_inv = $form_params['TSpmKoDetail']['no_inv'];
            }
            return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanStuffingDetailDt()));
        }
        return $this->render('/laporan/stuffingDetail/index', ['model' => $model]);
    }

    public function actionStuffingDetailPrint()
    {
        $this->layout = '@views/layouts/metronic/print';
        $model = new \app\models\TSpmKoDetail();
        $caraprint = Yii::$app->request->get('caraprint');
        $model->attributes = $_GET['TSpmKoDetail'];
        $model->tgl_awal = !empty($_GET['TSpmKoDetail']['tgl_awal']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpmKoDetail']['tgl_awal']) : "";
        $model->tgl_akhir = !empty($_GET['TSpmKoDetail']['tgl_akhir']) ? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TSpmKoDetail']['tgl_akhir']) : "";
        $model->cust_id = !empty($_GET['TSpmKoDetail']['cust_id']) ? $_GET['TSpmKoDetail']['cust_id'] : "";
        $model->jenis_produk = !empty($_GET['TSpmKoDetail']['jenis_produk']) ? $_GET['TSpmKoDetail']['jenis_produk'] : "";
        $model->no_inv = !empty($_GET['TSpmKoDetail']['no_inv']) ? $_GET['TSpmKoDetail']['no_inv'] : "";
        $paramprint['judul'] = Yii::t('app', 'Laporan Detail Stuffing Export');
        if ($model->tgl_awal == $model->tgl_akhir) {
            $paramprint['judul2'] = "Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u>";
        } else {
            $paramprint['judul2'] = "Periode Tanggal <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal) . "</u> sd <u>" . \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir) . "</u>";
        }
        if ($caraprint == 'PRINT') {
            return $this->render('/laporan/stuffingDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
        } else if ($caraprint == 'PDF') {
            $pdf = Yii::$app->pdf;
            $pdf->options = ['title' => $paramprint['judul']];
            $pdf->filename = $paramprint['judul'] . '.pdf';
            $pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
            $pdf->content = $this->render('/laporan/stuffingDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
            return $pdf->render();
        } else if ($caraprint == 'EXCEL') {
            return $this->render('/laporan/stuffingDetail/print', ['model' => $model, 'paramprint' => $paramprint]);
        }
    }

    public function actionPencapaianExport()
    {
        $model = new \app\models\TTargetPenjualan();
        $model->periode = date('Y');

        if ((\Yii::$app->request->get('laporan_params')) !== null) {
            $form_params = [];
            parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
            $model->attributes = $form_params['TTargetPenjualan'];
            $model->periode = $form_params['TTargetPenjualan']['periode'];
            $data['html'] = $this->renderPartial('/laporan/pencapaianExport/rekapContent', ['model' => $model]);
            return $this->asJson($data);
        }
        return $this->render('/laporan/pencapaianExport/index', ['model' => $model]);
    }

    public function actionInfoPenjualan($periode)
    {
        if (\Yii::$app->request->isAjax) {
            $model = $periode;
            return $this->renderAjax('/laporan/pencapaianExport/infoPenjualan', ['periode' => $periode]);
        }
    }

    public function actionInfo($id)
    {
        if (\Yii::$app->request->isAjax) {
            $model = \app\models\TInvoice::findOne($id);
            return $this->renderAjax('/laporan/rekapPenjualan/info', ['id' => $id, 'model' => $model]);
        }
    }

    public function actionOpexportblmproforma()
    {
        $model              = new \app\models\TOpExport();
        $model->tgl_awal    = date('d/m/Y', strtotime('first day of this month'));
        $model->tgl_akhir   = date('d/m/Y');
        if (\Yii::$app->request->get('dt') == 'table-laporan' && \Yii::$app->request->get('laporan_params') != null) {
            $form_params = [];
            parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
            $model->attributes  = $form_params['TOpExport'];
            $model->tgl_awal    = \app\components\DeltaFormatter::formatDateTimeForDb($form_params['TOpExport']['tgl_awal']);
            $model->tgl_akhir   = \app\components\DeltaFormatter::formatDateTimeForDb($form_params['TOpExport']['tgl_akhir']);
            $model->jns_produk  = $form_params['TOpExport']['jns_produk'];
            $param              = $this->_query_op_export_blm_proforma($model);
            return \yii\helpers\Json::encode(\app\components\SSP::complex($param));
        }
        return $this->render('/laporan/opexportblmproforma/index', ['model' => $model]);
    }

    public function actionOpexportblmproformaprint()
    {
        $this->layout       = '@views/layouts/metronic/print';
        $caraprint          = Yii::$app->request->get('caraprint');
        $paramprint['judul']= Yii::t('app', 'Laporan OP Export belum Proforma Packing List');
        $model              = new \app\models\TOpExport();
        $request            = Yii::$app->request->get('TOpExport');
        $model->attributes  = $request;
        $model->tgl_awal    = \app\components\DeltaFormatter::formatDateTimeForDb($request['tgl_awal']);
        $model->tgl_akhir   = \app\components\DeltaFormatter::formatDateTimeForDb($request['tgl_akhir']);
        $model->jns_produk  = $request['jns_produk'];

        $param              = $this->_query_op_export_blm_proforma($model);

        $query              = "SELECT ";
        foreach($param['column'] as $key => $col) {
            if($key < count($param['column']) - 1) {
                $query .= $col . ", ";
            }else {
                $query .= $col;
            }
        }
        $query .= " FROM {$param['table']} ";
        foreach($param['join'] as $join) {
            $query .= $join;
        }
        $query .= " WHERE {$param['where']} ";

        $model  = Yii::$app->db->createCommand($query)->queryAll();
        if($caraprint === 'EXCEL') {
            return $this->renderPartial('/laporan/opexportblmproforma/print', compact('model', 'paramprint'));
        }
    }

    private function _query_op_export_blm_proforma($model)
    {
        $param = [
            'table'     => 't_op_export',
            'pk'        => 't_op_export.op_export_id',
            'column'    => [
                't_op_export.op_export_id',
                't_op_export.kode',
                't_op_export.nomor_kontrak',
                't_op_export.jenis_produk',
                't_op_export.tanggal',
                'applicant.cust_an_nama',
                'applicant.cust_an_alamat',
                'notify.cust_an_nama AS notify_nama',
                'notify.cust_an_alamat AS notify_alamat',
                't_op_export.payment_method',
                't_op_export.term_of_price',
                't_op_export.hs_code',
                't_op_export.svlk_no',
                't_op_export.cancel_transaksi_id',
                't_cancel_transaksi.cancel_reason'
            ],
            'join'      => ['
                LEFT JOIN m_customer AS applicant ON applicant.cust_id = t_op_export.cust_id
                LEFT JOIN m_customer AS notify ON notify.cust_id = t_op_export.notify_party
                LEFT JOIN t_packinglist ON t_packinglist.op_export_id = t_op_export.op_export_id
                LEFT JOIN t_cancel_transaksi ON t_cancel_transaksi.cancel_transaksi_id = t_op_export.cancel_transaksi_id
            '],
            'where'     => " t_packinglist.op_export_id IS NULL" 
                        .  " AND ( t_op_export.tanggal BETWEEN '{$model->tgl_awal}' AND '{$model->tgl_akhir}')" 
        ];

        if(!empty($model->jns_produk)) {
            $param['where'] = $param['where'] . " AND t_op_export.jenis_produk = '{$model->jns_produk}'";
        }

        return $param;
    }
}
