<?php

namespace app\modules\tuk\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionDokumenPenjualan(){
		$model = new \app\models\TDokumenPenjualan();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualan'];
				$model->jenis_produk = $form_params['TDokumenPenjualan']['jenis_produk'];
				$model->tgl_awal = $form_params['TDokumenPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualan']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/dokumenPenjualan/index',['model'=>$model]);
	}
	
	public function actionDokumenPenjualanPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualan'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualan']['jenis_produk'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenPenjualan/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionDokumenDetail(){
		$model = new \app\models\TDokumenPenjualanDetail();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualanDetail'];
				$model->tgl_awal = $form_params['TDokumenPenjualanDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualanDetail']['tgl_akhir'];
				$model->jenis_produk = $form_params['TDokumenPenjualanDetail']['jenis_produk'];
				$model->cust_id = $form_params['TDokumenPenjualanDetail']['cust_id'];
                $model->dokumen_penjualan_id = $form_params['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/dokumenDetail/index',['model'=>$model]);
	}

	public function actionDokumenDetailPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualanDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualanDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualanDetail']['jenis_produk'];
		$model->cust_id = $_GET['TDokumenPenjualanDetail']['cust_id'];
		$model->dokumen_penjualan_id = $_GET['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}	

    public function actionDetailRandom() {
		if(\Yii::$app->request->isAjax){
            //dokumen_penjualan_detail_id, tanggal, nomor_dokumen, jenis_produk, customer, produk, total_palet
            $dokumen_penjualan_detail_id = Yii::$app->request->get('dokumen_penjualan_detail_id');
            $tanggal = Yii::$app->request->get('tanggal');
            $nomor_dokumen = Yii::$app->request->get('nomor_dokumen');
            $jenis_produk = Yii::$app->request->get('jenis_produk');
            $customer = Yii::$app->request->get('customer');
            $produk = Yii::$app->request->get('produk');
            $total_palet = Yii::$app->request->get('total_palet');
            $spm_kod_id = Yii::$app->db->createCommand("select spm_kod_id from t_dokumen_penjualan_detail where dokumen_penjualan_detail_id = ".$dokumen_penjualan_detail_id."")->queryScalar();
            $produk_id = Yii::$app->db->createCommand("select produk_id from t_dokumen_penjualan_detail where dokumen_penjualan_detail_id = ".$dokumen_penjualan_detail_id."")->queryScalar();
            $spm_ko_id = Yii::$app->db->createCommand("select spm_ko_id from t_spm_ko_detail where spm_kod_id = ".$spm_kod_id."")->queryScalar();
            $op_ko_id = Yii::$app->db->createCommand("select op_ko_id from t_spm_ko where spm_ko_id = ".$spm_ko_id."")->queryScalar();
            $op_ko_detail_id = Yii::$app->db->createCommand("select op_ko_detail_id from t_op_ko_detail where op_ko_id = ".$op_ko_id." and produk_id = ".$produk_id." and is_random = 'true' ")->queryScalar();

            $sql_list = "select * from t_op_ko_random where op_ko_detail_id = ".$op_ko_detail_id."";
            $sql_kod_id = "select spm_kod_id from t_dokumen_penjualan_detail where dokumen_penjualan_detail_id = ".$dokumen_penjualan_detail_id."";
            $sql_spm_ko_id = "select spm_ko_id from t_spm_ko_detail where spm_kod_id = ".$spm_kod_id."";
            $sql_op_ko_id = "select op_ko_id from t_spm_ko where spm_ko_id = ".$spm_ko_id."";
            $sql_op_ko_detail_id = "select op_ko_detail_id from t_op_ko_detail where op_ko_id = ".$op_ko_id." and is_random = 'true' ";

            $list = Yii::$app->db->createCommand("select * from t_op_ko_random where op_ko_detail_id = ".$op_ko_detail_id."")->queryAll();
			return $this->renderAjax('/laporan/dokumenPenjualan/_detailRandom',['produk_id'=>$produk_id,'sql_list'=>$sql_list, 'sql_kod_id'=>$sql_kod_id, 'sql_spm_ko_id'=>$sql_spm_ko_id, 'sql_op_ko_id'=>$sql_op_ko_id, 'sql_list'=>$sql_list, 'sql_op_ko_detail_id'=>$sql_op_ko_detail_id, 'list'=>$list, 'tanggal'=>$tanggal, 'nomor_dokumen'=>$nomor_dokumen, 'jenis_produk'=>$jenis_produk, 'customer'=>$customer, 'produk'=>$produk, 'total_palet'=>$total_palet]);
        }        
    }

	public function actionDokumenDetailJasaKD(){
		$model = new \app\models\TDokumenPenjualanDetail();
		if(\Yii::$app->request->isAjax){
			$form_params = []; parse_str(\Yii::$app->request->post('formData'),$form_params);
			$data['html'] = "";
			$total['html'] = "";

			$tgl_awal = Yii::$app->request->post('tgl_awal');
			$tgl_akhir = Yii::$app->request->post('tgl_akhir');
			$jenis_produk = Yii::$app->request->post('jenis_produk');
			$cust_id = Yii::$app->request->post('cust_id');
			$dokumen_penjualan_id = Yii::$app->request->post('dokumen_penjualan_id');

			$tgl_awal == "" ? $tgl_awal = date('d-m-Y') : $tgl_awal = $tgl_awal;
			$tgl_akhir == "" ? $tgl_awal = date('d-m-Y') : $tgl_akhir = $tgl_akhir;

			if ($cust_id != "") {
				$and_cust_id = "and t_dokumen_penjualan.cust_id = ".$cust_id."";
			} else {
				$and_cust_id = "";
			}

			if ($dokumen_penjualan_id != "") {
				$and_dokumen_penjualan_id = "and t_dokumen_penjualan.dokumen_penjualan_id = ".$dokumen_penjualan_id."";
			} else {
				$and_dokumen_penjualan_id = "";
			}

			$sql_x = "select t_dokumen_penjualan.nomor_dokumen, t_spm_ko.op_ko_id, t_spm_ko_detail.keterangan
						from t_dokumen_penjualan_detail 
						join t_dokumen_penjualan on t_dokumen_penjualan.dokumen_penjualan_id = t_dokumen_penjualan_detail.dokumen_penjualan_id
						join t_spm_ko_detail on t_spm_ko_detail.spm_kod_id = t_dokumen_penjualan_detail.spm_kod_id
						join t_spm_ko on t_spm_ko.spm_ko_id = t_spm_ko_detail.spm_ko_id
						where t_dokumen_penjualan.tanggal between '".$tgl_awal."' and '".$tgl_akhir."'
						and t_dokumen_penjualan.jenis_produk = 'JasaKD'
						".$and_cust_id."
						".$and_dokumen_penjualan_id."
						group by t_dokumen_penjualan.nomor_dokumen, t_spm_ko.op_ko_id, t_spm_ko_detail.keterangan
						order by t_dokumen_penjualan.nomor_dokumen desc
						";
						
			$query_x = \Yii::$app->db->createCommand($sql_x)->queryAll();
			$numrows_x = count($query_x);
			$total_baris = 0;
			$i = 0;
			if (count($query_x) > 0){
				foreach($query_x as $kolom){
					$i % 2 == 0 ? $color = '#edfff2' :  $color = '#fffcf5'; 
					$nomor_dokumen = $kolom['nomor_dokumen'];
					$op_ko_id = $kolom['op_ko_id'];
					$keterangan = $kolom['keterangan'];
					$sql_y = "select t_dokumen_penjualan.tanggal, 
								t_dokumen_penjualan.nomor_dokumen, 
								t_dokumen_penjualan.jenis_produk, 
								m_customer.cust_an_nama, 
								m_produk_jasa.nama as produk_nama, 
								t_terima_jasa.t, 
								t_terima_jasa.l, 
								t_terima_jasa.p, 
								t_terima_jasa.t_satuan, 
								t_terima_jasa.l_satuan, 
								t_terima_jasa.p_satuan, 
								t_terima_jasa.qty_kecil, 
								t_terima_jasa.kubikasi, 
								t_terima_jasa.terima_jasa_id,
								count(*) OVER() AS total_count 
								from t_dokumen_penjualan_detail 
								join t_dokumen_penjualan on t_dokumen_penjualan.dokumen_penjualan_id = t_dokumen_penjualan_detail.dokumen_penjualan_id
								join t_spm_ko on t_spm_ko.spm_ko_id = t_dokumen_penjualan.spm_ko_id
								join t_spm_ko_detail on t_spm_ko_detail.spm_ko_id = t_spm_ko.spm_ko_id
								join m_customer on m_customer.cust_id = t_spm_ko.cust_id
								join t_op_ko on t_op_ko.op_ko_id = t_spm_ko.op_ko_id
								join t_op_ko_detail on t_op_ko_detail.op_ko_id = t_op_ko.op_ko_id
								join t_terima_jasa on t_terima_jasa.op_ko_id = t_op_ko.op_ko_id
								join m_produk_jasa on m_produk_jasa.produk_jasa_id = t_terima_jasa.produk_jasa_id
								where t_dokumen_penjualan.tanggal between '".$tgl_awal."' and '".$tgl_akhir."'
								and t_dokumen_penjualan.nomor_dokumen = '".$nomor_dokumen."'
								and t_terima_jasa.nomor_palet in (".$keterangan.")
								and t_terima_jasa.op_ko_id in ($op_ko_id)
								".$and_cust_id."
								".$and_dokumen_penjualan_id."
								group by t_dokumen_penjualan.nomor_dokumen,
								t_dokumen_penjualan.tanggal,
								t_dokumen_penjualan.jenis_produk,
								m_customer.cust_an_nama,
								m_produk_jasa.nama,
								t_terima_jasa.t, 
								t_terima_jasa.l, 
								t_terima_jasa.p, 
								t_terima_jasa.qty_kecil, 
								t_terima_jasa.kubikasi,
								t_terima_jasa.terima_jasa_id					
								order by t_terima_jasa.terima_jasa_id asc
								";
					$query_y = \Yii::$app->db->createCommand($sql_y)->queryAll();
					$numrows_y = count($query_y);
					$j = 0;
					foreach ($query_y as $detail) {
						$tanggal = $detail['tanggal'];
						$nomor_dokumen = $detail['nomor_dokumen'];
						$jenis_produk = $detail['jenis_produk'];
						$nama = $detail['cust_an_nama'];
						$customer = $detail['cust_an_nama'];
						$produk_nama = $detail['produk_nama'];
						$t = $detail['t'];
						$l = $detail['l'];
						$p = $detail['p'];
						$t_satuan = $detail['t_satuan'];
						$l_satuan = $detail['l_satuan'];
						$p_satuan = $detail['p_satuan'];
						$qty_kecil = $detail['qty_kecil'];
						$kubikasi = $detail['kubikasi'];
						$terima_jasa_id = $detail['terima_jasa_id'];

						$data['html'] .= $this->renderPartial('dokumenDetailJasaKD/_content',['model'=>$model, 'sql_x'=>$sql_x, 'sql_y'=>$sql_y, 'i'=>$i, 'j'=>$j
																							, 'numrows_y'=>$numrows_y, 'tanggal'=>$tanggal
																							, 'nomor_dokumen'=>$nomor_dokumen, 'jenis_produk'=>$jenis_produk, 'nama'=>$nama
																							, 'customer'=>$customer, 'produk_nama'=>$produk_nama
																							, 't'=>$t, 'l'=>$l, 'p'=>$p
																							, 't_satuan'=>$t_satuan, 'l_satuan'=>$l_satuan, 'p_satuan'=>$p_satuan
																							, 'qty_kecil'=>$qty_kecil, 'kubikasi'=>$kubikasi
																							, 'terima_jasa_id'=>$terima_jasa_id, 'color'=>$color
																							]);

						$j++;				
					}
					$i++;

				}
			}
			return $this->asJson($data,$total);
		}
		return $this->render('/laporan/dokumenDetailJasaKD/index',['model'=>$model]);
	}

	public function actionDokumenDetailJasaKDPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualanDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualanDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_akhir']):"";
		$model->jenis_produk = 'JasaKD';
		$model->cust_id = $_GET['TDokumenPenjualanDetail']['cust_id'];
		$model->dokumen_penjualan_id = $_GET['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
		
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan JasaKD');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenDetailJasaKD/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenDetailJasaKD/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenDetailJasaKD/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}	

	public function actionPenerbitanDokumen(){
		$model = new \app\models\TDokumenPenjualan();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualan'];
				$model->tgl_awal = $form_params['TDokumenPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualan']['tgl_akhir'];
				$model->jenis_produk = $form_params['TDokumenPenjualan']['jenis_produk'];
				$model->cust_id = $form_params['TDokumenPenjualan']['cust_id'];
				$model->provinsi = $form_params['TDokumenPenjualan']['provinsi'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPenerbitanKoDt() ));
		}
		return $this->render('/laporan/penerbitanDokumen/index',['model'=>$model]);
	}
	
	public function actionPenerbitanDokumenPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualan'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_akhir']):"";
		$model->jenis_produk = $_GET['TDokumenPenjualan']['jenis_produk'];
		$model->cust_id = $_GET['TDokumenPenjualan']['cust_id'];
		$model->provinsi = $_GET['TDokumenPenjualan']['provinsi'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penerbitanDokumen/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionDokumenPenjualanKb(){
		$model = new \app\models\TDokumenPenjualan();
//		$model->tgl_awal = date('d/m/Y');
//		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualan'];
				// $model->jenis_produk = $form_params['TDokumenPenjualan']['jenis_produk'];
				$model->tgl_awal = $form_params['TDokumenPenjualan']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualan']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPenjualanKbDt() ));
		}
		return $this->render('/laporan/dokumenPenjualanKb/index',['model'=>$model]);
	}

	public function actionDokumenPenjualanKbPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualan();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualan'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualan']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualan']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualan']['tgl_akhir']):"";
		// $model->jenis_produk = $_GET['TDokumenPenjualan']['jenis_produk'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan Kayu Bulat');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenPenjualanKb/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenPenjualanKb/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenPenjualanKb/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionDokumenDetailKb(){
		$model = new \app\models\TDokumenPenjualanDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TDokumenPenjualanDetail'];
				$model->tgl_awal = $form_params['TDokumenPenjualanDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenPenjualanDetail']['tgl_akhir'];
				// $model->jenis_produk = $form_params['TDokumenPenjualanDetail']['jenis_produk'];
				$model->cust_id = $form_params['TDokumenPenjualanDetail']['cust_id'];
                $model->dokumen_penjualan_id = $form_params['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanKbDt() ));
		}
		return $this->render('/laporan/dokumenDetailKb/index',['model'=>$model]);
	}

	public function actionDokumenDetailKbPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenPenjualanDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TDokumenPenjualanDetail'];
		$model->tgl_awal = !empty($_GET['TDokumenPenjualanDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TDokumenPenjualanDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TDokumenPenjualanDetail']['tgl_akhir']):"";
		// $model->jenis_produk = $_GET['TDokumenPenjualanDetail']['jenis_produk'];
		$model->cust_id = $_GET['TDokumenPenjualanDetail']['cust_id'];
		$model->dokumen_penjualan_id = $_GET['TDokumenPenjualanDetail']['dokumen_penjualan_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Dokumen Penjualan Kayu Bulat');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/dokumenDetailKb/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/dokumenDetailKb/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/dokumenDetailKb/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
