<?php

namespace app\assets\logistik\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionReturBHP(){
		$model = new \app\models\TReturBhp();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturBhp'];
				$model->tgl_awal = $form_params['TReturBhp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TReturBhp']['tgl_akhir'];
				$model->bhp_nm = $form_params['TReturBhp']['bhp_nm'];
				$model->kode = $form_params['TReturBhp']['kode'];
				$model->terimabhp_kode = $form_params['TReturBhp']['terimabhp_kode'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/returBHP/index',['model'=>$model]);
	}
	
	public function actionReturBHPPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TReturBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturBhp'];
		$model->tgl_awal = !empty($_GET['TReturBhp']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TReturBhp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TReturBhpTReturBhp']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TReturBhp']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TReturBhp']['bhp_nm'];
		$model->kode = $_GET['TReturBhp']['kode'];
		$model->terimabhp_kode = $_GET['TReturBhp']['terimabhp_kode'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Retur Penerimaan BHP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
        public function actionStockBHP(){
		$model = new \app\models\HPersediaanBhp();
		$model->tgl_awal = (empty($tgl_awal))? $model->tgl_awal = date('d/m/Y',strtotime("-30 day")) : $tgl_awal;
		$model->tgl_akhir = (empty($tgl_akhir))? $model->tgl_akhir = date('d/m/Y') : $tgl_akhir;
		if(!empty($bhp_id)){
			$model->bhp_id = $bhp_id;
			$modPersediaan = \app\models\HPersediaanBhp::find()->where(['bhp_id'=>$bhp_id])->orderBy(['created_at'=>SORT_DESC])->all();
		}
		return $this->render('/laporan/stockBHP/index',['model'=>$model]);
	}
}
