<?php

namespace app\modules\logistik\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class BahanpembantuController extends DeltaBaseController
{
    
	public $defaultAction = 'index';
    
	public function actionIndex(){
		$model = new \app\models\MBrgBhp();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['MBrgBhp'];
				$model->bhp_nm = $form_params['MBrgBhp']['bhp_nm'];
				$model->bhp_group = $form_params['MBrgBhp']['bhp_group'];
				$model->active = $form_params['MBrgBhp']['active'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MBrgBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['MBrgBhp'];
		$model->bhp_nm = $_GET['MBrgBhp']['bhp_nm'];
		$model->bhp_group = $_GET['MBrgBhp']['bhp_group'];
		$paramprint['judul'] = Yii::t('app', 'Master Bahan Pembantu');
		if($caraprint == 'PRINT'){
			return $this->renderPartial('print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionList(){
        if(\Yii::$app->request->get('dt')=='table-bahanpembantu'){
			$param['table']= \app\models\MBrgBhp::tableName();
			$param['pk']= \app\models\MBrgBhp::primaryKey()[0];
			$param['column'] = ['bhp_id','bhp_kode','bhp_group','bhp_nm',$param['table'].'.active'];
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
		}
        
		return $this->render('list');
	}
	
	public function actionCreate(){
		if(\Yii::$app->request->isAjax){
			$model = new \app\models\MBrgBhp();
			$model->active = true;
			if( Yii::$app->request->post('MBrgBhp')){
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    $success_1 = false;
                    $model->load(\Yii::$app->request->post());
                    $model->file1 = \yii\web\UploadedFile::getInstance($model, 'bhp_gbr');
                    if($model->validate()){
                        if(!empty($model->file1)){
                            $randomstring = Yii::$app->getSecurity()->generateRandomString(4);
                            $dir_path = Yii::$app->basePath.'/web/uploads/log/bahanpembantu';
                            if(!is_dir($dir_path)){
                                mkdir($dir_path);
                            }
                            $file_path = $dir_path.'/'.date('Ymd_His').'-'.$model->bhp_group.'-'.$randomstring.'.' . $model->file1->extension;
                            $model->file1->saveAs($file_path,false);
                            $model->bhp_gbr = date('Ymd_His').'-'.$model->bhp_group.'-'.$randomstring.'.' .$model->file1->extension;
                        }
                        if($model->save()){
                            $success_1 = true;
                        }
                    }else{
                        $data['message_validate']=\yii\widgets\ActiveForm::validate($model); 
                    }
                    if ($success_1) {
                        $transaction->commit();
                        $data['status'] = true;
                        $data['message'] = Yii::t('app', \app\components\Params::DEFAULT_SUCCESS_TRANSACTION_MESSAGE);
                    } else {
                        $transaction->rollback();
                        $data['status'] = false;
                        (!isset($data['message']) ? $data['message'] = Yii::t('app', \app\components\Params::DEFAULT_FAILED_TRANSACTION_MESSAGE) : '');
                        (isset($data['message_validate']) ? $data['message'] = null : '');
                    }
                } catch (\yii\db\Exception $ex) {
                    $transaction->rollback();
                    $data['message'] = $ex;
                }
                return $this->asJson($data);
			}
			return $this->renderAjax('create',['model'=>$model]);
		}
	}

    public function actionInfo($id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\MBrgBhp::findOne($id);
			return $this->renderAjax('info',['model'=>$model]);
		}
	}
	
	public function actionEdit($id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\MBrgBhp::findOne($id);
			if( Yii::$app->request->post('MBrgBhp')){
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    $success_1 = false;
                    $file_old = $model->bhp_gbr;
                    $model->load(\Yii::$app->request->post());
                    $model->file1 = \yii\web\UploadedFile::getInstance($model, 'bhp_gbr');
                    $model->bhp_gbr = !empty($model->bhp_gbr)?$model->bhp_gbr:$file_old;
                    if($model->validate()){
                        if(!empty($model->file1)){
                            $randomstring = Yii::$app->getSecurity()->generateRandomString(4);
                            $dir_path = Yii::$app->basePath.'/web/uploads/log/bahanpembantu';
                            if(!is_dir($dir_path)){
                                mkdir(Yii::$app->basePath.'/web/uploads/log');
                                mkdir($dir_path);
                            }
                            $file_path = $dir_path.'/'.date('Ymd_His').'-'.$model->bhp_group.'-'.$randomstring.'.' . $model->file1->extension;
                            $model->file1->saveAs($file_path,false);
                            $model->bhp_gbr = date('Ymd_His').'-'.$model->bhp_group.'-'.$randomstring.'.' .$model->file1->extension;
                            if($file_old != null){
                                if (file_exists(Yii::$app->basePath.'/web/uploads/log/bahanpembantu/'.$file_old)) {
                                    unlink(Yii::$app->basePath.'/web/uploads/log/bahanpembantu/'.$file_old);
                                }
                            }
                        }
                        if($model->save()){
                            $success_1 = true;
                        }
                    }else{
                        $data['message_validate']=\yii\widgets\ActiveForm::validate($model); 
                    }
                    if ($success_1) {
                        $transaction->commit();
                        $data['status'] = true;
                        $data['message'] = Yii::t('app', 'Data Bahan Pembantu Berhasil Diupdate');
                    } else {
                        $transaction->rollback();
                        $data['status'] = false;
                        (!isset($data['message']) ? $data['message'] = Yii::t('app', \app\components\Params::DEFAULT_FAILED_TRANSACTION_MESSAGE) : '');
                        (isset($data['message_validate']) ? $data['message'] = null : '');
                    }
                } catch (\yii\db\Exception $ex) {
                    $transaction->rollback();
                    $data['message'] = $ex;
                }
                return $this->asJson($data);
			}
			return $this->renderAjax('edit',['model'=>$model]);
		}
	}
	
	public function actionDelete($id){
		if(\Yii::$app->request->isAjax){
            $tableid = Yii::$app->request->get('tableid');
			$model = \app\models\MBrgBhp::findOne($id);
            $file_old = $model->bhp_gbr;
            if( Yii::$app->request->post('deleteRecord')){
                $transaction = \Yii::$app->db->beginTransaction();
                try {
                    $success_1 = false;
                    if($model->delete()){
                        if($file_old != null){
                            if (file_exists(Yii::$app->basePath.'/web/uploads/log/bahanpembantu/'.$file_old)) {
                                unlink(Yii::$app->basePath.'/web/uploads/log/bahanpembantu/'.$file_old);
                            }
                        }
                        $success_1 = true;
                    }else{
                        $data['message'] = Yii::t('app', 'Data Bahan Pembantu Gagal dihapus');
                    }
                    if ($success_1) {
                        $transaction->commit();
                        $data['status'] = true;
                        $data['message'] = Yii::t('app', '<i class="icon-check"></i> Data Bahan Pembantu Berhasil Dihapus');
                    } else {
                        $transaction->rollback();
                        $data['status'] = false;
                        (!isset($data['message']) ? $data['message'] = Yii::t('app', \app\components\Params::DEFAULT_FAILED_TRANSACTION_MESSAGE) : '');
                        (isset($data['message_validate']) ? $data['message'] = null : '');
                    }
                } catch (\yii\db\Exception $ex) {
                    $transaction->rollback();
                    $data['message'] = $ex;
                }
                return $this->asJson($data);
			}
			return $this->renderAjax('@views/apps/partial/_deleteRecordConfirm',['id'=>$id,'tableid'=>$tableid]);
		}
	}
	
}
