<?php

namespace app\modules\logistik\controllers;

// use app\components\DeltaFormatter;
// use app\components\SSP;
// use app\models\MDepartement;
// use app\models\TBpb;
// use app\models\TmpAnalisaSpb;
// use app\models\TSpl;
// use app\models\TSpo;
// use app\models\TTerimaBhp;
// use Yii;
// use app\controllers\DeltaBaseController;
// use yii\base\InvalidConfigException;
// use yii\db\Exception;
// use yii\helpers\ArrayHelper;
// use yii\helpers\Json;

use app\components\DeltaFormatter;
use app\components\SSP;
use app\models\MDepartement;
use app\models\TBpb;
use app\models\TmpAnalisaSpb;
use app\models\TSpl;
use app\models\TSpo;
use app\models\TTerimaBhp;
use Yii;
use app\controllers\DeltaBaseController;
use app\models\MBrgBhp;
use app\models\TTerimaBhpSub;
use yii\base\InvalidConfigException;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

class LaporanController extends DeltaBaseController
{	
	public function actionReturBHP(){
		$model = new \app\models\TReturBhp();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TReturBhp'];
				$model->tgl_awal = $form_params['TReturBhp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TReturBhp']['tgl_akhir'];
				$model->bhp_nm = $form_params['TReturBhp']['bhp_nm'];
				$model->kode = $form_params['TReturBhp']['kode'];
				$model->terimabhp_kode = $form_params['TReturBhp']['terimabhp_kode'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/returBHP/index',['model'=>$model]);
	}

	public function actionReturBHPPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TReturBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TReturBhp'];
		$model->tgl_awal = !empty($_GET['TReturBhp']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TReturBhp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TReturBhpTReturBhp']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TReturBhp']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TReturBhp']['bhp_nm'];
		$model->kode = $_GET['TReturBhp']['kode'];
		$model->terimabhp_kode = $_GET['TReturBhp']['terimabhp_kode'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Retur Penerimaan Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/returBHP/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

    public function actionStockBHP(){
		$model = new \app\models\HPersediaanBhp();
		$model->tgl_awal = (empty($tgl_awal))? $model->tgl_awal = date('d/m/Y',strtotime("-30 day")) : $tgl_awal;
		$model->tgl_akhir = (empty($tgl_akhir))? $model->tgl_akhir = date('d/m/Y') : $tgl_akhir;
		if(!empty($bhp_id)){
			$model->bhp_id = $bhp_id;
			$modPersediaan = \app\models\HPersediaanBhp::find()->where(['bhp_id'=>$bhp_id])->orderBy(['created_at'=>SORT_DESC])->all();
		}
		return $this->render('/laporan/stockBHP/index',['model'=>$model]);
	}

	public function actionTerimaBHP(){
		$tgl_awal = Yii::$app->request->post('tgl_awal');
		$tgl_akhir = Yii::$app->request->post('tgl_akhir');
		$cari_kode = Yii::$app->request->post('cari_kode');

		isset($tgl_awal) ? $tgl_awal = $tgl_awal : $tgl_awal = date('d/m/Y');
		isset($tgl_akhir) ? $tgl_akhir = $tgl_akhir : $tgl_akhir = date('d/m/Y');
		isset($cari_kode) ? $cari_kode = $cari_kode : $cari_kode = '';

		$sql = "select tglterima from t_terima_bhp ".
				"	where 1=1 ".
				"	and tglterima between '".$tgl_awal."' and '".$tgl_akhir."' ".
				"	and terimabhp_kode ilike '%".$cari_kode."%' ".
				"	limit 100";
				"	";
		$model = Yii::$app->db->createCommand($sql)->queryAll();

		return $this->render('/laporan/terimaBHP/index',['model'=>$model,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir, 'cari_kode'=>$cari_kode]);
	}

	public function actionTerimaBHPAjax() {
		$data = [];
		$tgl_awal = Yii::$app->request->post('tgl_awal');
		$tgl_akhir = Yii::$app->request->post('tgl_akhir');
		$cari_kode = Yii::$app->request->post('cari_kode');

		isset($tgl_awal) ? $tgl_awal = $tgl_awal : $tgl_awal = date('d/m/Y');
		isset($tgl_akhir) ? $tgl_akhir = $tgl_akhir : $tgl_akhir = date('d/m/Y');
		isset($cari_kode) ? $cari_kode = $cari_kode : $cari_kode = '';

		$data['tgl_awal'] = $tgl_awal;
		$data['tgl_akhir'] = $tgl_akhir;
		$data['cari_kode'] = $cari_kode;
		return $this->asJson($data);
	}

	public function actionTerimaBHPShow(){
		$tgl_awal = Yii::$app->request->post('tgl_awal');
		$tgl_akhir = Yii::$app->request->post('tgl_akhir');
		$cari_kode = Yii::$app->request->post('cari_kode');

		isset($tgl_awal) ? $tgl_awal = $tgl_awal : $tgl_awal = date('d/m/Y');
		isset($tgl_akhir) ? $tgl_akhir = $tgl_akhir : $tgl_akhir = date('d/m/Y');
		isset($cari_kode) ? $cari_kode = $cari_kode : $cari_kode = '';

		$sql = "select tglterima from t_terima_bhp ".
				"	where 1=1 ".
				"	and tglterima between '".$tgl_awal."' and '".$tgl_akhir."' ".
				"	and terimabhp_kode ilike '%".$cari_kode."%' ".
				"	limit 100";
				"	";
		$model = Yii::$app->db->createCommand($sql)->queryAll();

		return $this->render('/laporan/terimaBHP/_show',['model'=>$model,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir, 'cari_kode'=>$cari_kode]);
	}

    /**
     * @throws Exception
     */
    public function actionTerimaBHPPrint(){
		$this->layout   = '@views/layouts/metronic/print';
		$tgl_awal       = Yii::$app->request->get('tgl_awal');
		$tgl_akhir      = Yii::$app->request->get('tgl_akhir');
		$cari_kode      = Yii::$app->request->post('cari_kode');

        $tgl_awal       = isset($tgl_awal) ? $tgl_awal : date('d/m/Y');
        $tgl_akhir      = isset($tgl_akhir) ? $tgl_akhir : date('d/m/Y');
        $cari_kode      = isset($cari_kode) ? $cari_kode : '';

		$sql = "select tglterima from t_terima_bhp ".
				"	where 1=1 ".
				"	and tglterima between '".$tgl_awal."' and '".$tgl_akhir."' ".
				"	and terimabhp_kode ilike '%".$cari_kode."%' ".
				"	limit 100";
        $model = Yii::$app->db->createCommand($sql)->queryAll();

		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Laporan Terima Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/terimaBHP/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir, 'cari_kode' => $cari_kode]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/terimaBHP/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir, 'cari_kode' => $cari_kode]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/terimaBHP/print',['model'=>$model,'paramprint'=>$paramprint,'tgl_awal'=>$tgl_awal,'tgl_akhir'=>$tgl_akhir, 'cari_kode'=>$cari_kode]);
		}
	}

    /**
     * @return string
     * @throws Exception
     * @throws InvalidConfigException
     */
    public function actionLaporanSPB()
    {
        $model              = new TmpAnalisaSpb();
        $model->tgl_awal    = date('d/m/Y');
        $model->tgl_akhir   = date('d/m/Y');

        $dt                 = Yii::$app->request->get('dt');
	    $lap_params         = Yii::$app->request->get('lap_params');

        // var_dump($_GET);die;
        if($dt === 'table-list') {
            $form_params = []; parse_str($lap_params, $form_params);
            $model->attributes      = $form_params['TmpAnalisaSpb'];
            $model->tgl_awal        = $form_params['TmpAnalisaSpb']['tgl_awal'];
            $model->tgl_akhir       = $form_params['TmpAnalisaSpb']['tgl_akhir'];
            $model->nama_departement= $form_params['TmpAnalisaSpb']['nama_departement'];
            $start_date             = $form_params['start_date'];
            $end_date               = $form_params['end_date'];
            $departement            = $form_params['departement'];
            $generate               = false;

            if($model->tgl_awal !== $start_date || $model->tgl_akhir !== $end_date || $model->nama_departement !== $departement) {
                $generate   = true;
                $tgl_awal   = DeltaFormatter::formatDateTimesForDb($model->tgl_awal);
                $tgl_akhir  = DeltaFormatter::formatDateTimesForDb($model->tgl_akhir);
                $dept = MDepartement::find()->where(['departement_nama' => $model->nama_departement])->one();
                $departement = $dept ? $dept->departement_id : 0;
                $user_id = Yii::$app->user->id;
                $command = Yii::$app->db->createCommand("SELECT gen_analisa_spb(:tglawal, :tglakhir, :userid, :departementid)");
                $command->bindParam(':tglawal', $tgl_awal);
                $command->bindParam(':tglakhir', $tgl_akhir);
                $command->bindParam(':userid', $user_id);
                $command->bindParam(':departementid', $departement);
                $command->query();
            }

            $result                 = SSP::complex($model->searchLaporanDt());
            $result['start_date']   = $model->tgl_awal;
            $result['end_date']     = $model->tgl_akhir;
            $result['departement']  = $model->nama_departement;
            $result['is_generate']  = $generate;
            $result['request']      = $form_params;
            return Json::encode($result);
        }

        return $this->render('/laporan/laporanSPB/index', compact('model'));     
    }

//    private function _generateSPB(TmpAnalisaSpb $model)
//    {
//        $TSpb       = \app\models\TSpb::find()->with('spbDiminta');
//        $TSpb
//        ->andWhere([
//            '>=',
//            'spb_tanggal',
//            DeltaFormatter::formatDateTimesForDb($model->tgl_awal),
//        ])
//        ->andWhere([
//            '<=',
//            'spb_tanggal',
//            DeltaFormatter::formatDateTimesForDb($model->tgl_akhir),
//        ]);
//        $dept = MDepartement::find()->where(['departement_nama' => $model->nama_departement])->one();
//        if($dept) {
//            $TSpb->andWhere([
//                'departement_id' => $dept->departement_id
//            ]);
//        }
//
//        foreach($TSpb->all() as $key => $spb) { // loop data dari spb
//            $SpbDetail  = \app\models\TSpbDetail::find()->where(['spb_id' => $spb->spb_id])->all();
//            $spp_kode       = '';
//            $reff_no        = '';
//            $spp_tanggal    = '';
//            foreach($SpbDetail as $spb_detail) { // loop untuk mencari kode spp & reff_no
//                $MapSppDetail  = \app\models\MapSpbDetailSppDetail::find()->where(['spbd_id' => $spb_detail->spbd_id])->all();
//                if($MapSppDetail) {
//                    foreach($MapSppDetail as $map) {
//                        $TSppDetail = \app\models\TSppDetail::find()->where(['sppd_id' => $map->sppd_id])->all();
//                        if($TSppDetail) {
//                            foreach($TSppDetail as $spp_detail) {
//                                $Spp            = \app\models\TSpp::find()->where(['spp_id' => $spp_detail->spp_id])->one();
//                                $map_spl_spo    = \app\models\MapSppDetailReff::find()->where(['sppd_id' => $spp_detail->sppd_id])->all();
//                                foreach($map_spl_spo as $reff) {
//                                    if($reff->reff_no) {
//                                        $reff_no = $reff->reff_no;
//                                    }
//                                }
//                                if($Spp) {
//                                    $spp_kode       = $Spp->spp_kode;
//                                    $spp_tanggal    = $Spp->spp_tanggal;
//                                }
//                            }
//                        }
//                    }
//                }
//            }
//            // akhir mencari data spp dan reff_no
//
//            // mencari kode bhp
//            $bhp_kode           = '';
//            $spl_spo_tanggal    = '';
//            $bhp_tanggal_cek    = '';
//            $bhp_approval       = '';
//            $bhp_tanggal        = '';
//            $pegawai_checker    = '';
//            $command            = new yii\db\Query();
//            if($reff_no) {
//                if(strpos($reff_no, 'SPO') !== false) {
//                    $spo = $command
//                        ->select(['t_spo.*', 't_terima_bhp.*', 'm_pegawai.*'])
//                        ->from('t_terima_bhp')
//                        ->innerJoin('t_spo', 't_terima_bhp.spo_id = t_spo.spo_id AND t_terima_bhp.terima_bhp_id = t_spo.terima_bhp_id')
//                        ->innerJoin('m_pegawai', 't_terima_bhp.pegawai_checker = m_pegawai.pegawai_id')
//                        ->where(['t_spo.spo_kode' => $reff_no])
//                        ->one();
//                    if($spo) {
//                        $bhp_kode           = $spo['terimabhp_kode'];
//                        $spl_spo_tanggal    = $spo['spo_tanggal'];
//                        $bhp_tanggal_cek    = $spo['tanggal_jam_checker'];
//                        $bhp_approval       = $spo['status_approval'];
//                        $bhp_tanggal        = $spo['tglterima'];
//                        $pegawai_checker    = $spo['pegawai_nama'];
//                    }
//                }else {
//                    $spl = $command
//                        ->select(['t_spl.*', 't_terima_bhp.*', 'm_pegawai.*'])
//                        ->from('t_terima_bhp')
//                        ->innerJoin('t_spl', 't_terima_bhp.spl_id = t_spl.spl_id AND t_terima_bhp.terima_bhp_id = t_spl.terima_bhp_id')
//                        ->innerJoin('m_pegawai', 't_terima_bhp.pegawai_checker = m_pegawai.pegawai_id')
//                        ->where(['t_spl.spl_kode' => $reff_no])
//                        ->one();
//                    if($spl) {
//                        $bhp_kode           = $spl['terimabhp_kode'];
//                        $spl_spo_tanggal    = $spl['spl_tanggal'];
//                        $bhp_tanggal_cek    = $spl['tanggal_jam_checker'];
//                        $bhp_approval       = $spl['status_approval'];
//                        $bhp_tanggal        = $spl['tglterima'];
//                        $pegawai_checker    = $spl['pegawai_nama'];
//                    }
//                }
//            }
//
//            $bpb_kode           = '';
//            $bpb_status         = '';
//            $bpb_tgl_keluar     = '';
//            $bpb_tgl_terima     = '';
//            $bpb_pegawai_keluar = '';
//            $bpb_pegawai_terima = '';
//            if($spb->spb_id && $spb->departement_id) {
//                $bpb = \app\models\TBpb::find()
//                    ->where(['spb_id' => $spb->spb_id])
//                    ->andWhere(['departement_id' => $spb->departement_id])
//                    ->one();
//                if($bpb) {
//                    $bpb_kode           = $bpb->bpb_kode;
//                    $bpb_status         = $bpb->bpb_status;
//                    $bpb_tgl_keluar     = $bpb->created_at;
//                    $bpb_tgl_terima     = $bpb->updated_at;
//                    $pegawai1           = \app\models\MPegawai::find()->where(['pegawai_id' => $bpb->bpb_dikeluarkan])->one();
//                    $pegawai2           = \app\models\MPegawai::find()->where(['pegawai_id' => $bpb->bpb_diterima])->one();
//                    $bpb_pegawai_keluar = $pegawai1['pegawai_nama'];
//                    $bpb_pegawai_terima = $pegawai2['pegawai_nama'];
//                }
//            }
//            // akhir mencari kode bhp
//
//            // get approval spb
//            $spb_approval = \app\models\TApproval::find()->with(['approvedBy', 'assignedTo'])->where(['reff_no' => $spb->spb_kode])->all();
//            $spb_approval = array_map(function($arr) {
//                return [
//                    'master' => $arr,
//                    'detail' => $arr->relatedRecords
//                ];
//            }, $spb_approval);
//            // akhir approval spb
//
//            $tmpAnalisaSpb = new TmpAnalisaSpb();
//            $tmpAnalisaSpb->nour                = $key + 1;
//            $tmpAnalisaSpb->spb_kode            = $spb->spb_kode;
//            $tmpAnalisaSpb->spb_tanggal         = $spb->spb_tanggal;
//            $tmpAnalisaSpb->spb_status          = $spb->spb_status;
//            $tmpAnalisaSpb->spb_approval        = Json::encode($spb_approval);
//            $tmpAnalisaSpb->spb_pegawai_nama    = $spb->spbDiminta->pegawai_nama;
//            $tmpAnalisaSpb->spb_approve_status  = $spb->approve_status;
//            $tmpAnalisaSpb->spp_kode            = $spp_kode;
//            $tmpAnalisaSpb->spp_tanggal         = $spp_tanggal;
//            $tmpAnalisaSpb->reff_no             = $reff_no;
//            $tmpAnalisaSpb->reff_tanggal        = $spl_spo_tanggal;
//            $tmpAnalisaSpb->bhp_kode            = $bhp_kode;
//            $tmpAnalisaSpb->bhp_tanggal_cek     = $bhp_tanggal_cek;
//            $tmpAnalisaSpb->bhp_approval        = $bhp_approval;
//            $tmpAnalisaSpb->bhp_tanggal         = $bhp_tanggal;
//            $tmpAnalisaSpb->bhp_pegawai_cek     = $pegawai_checker;
//            $tmpAnalisaSpb->bpb_kode            = $bpb_kode;
//            $tmpAnalisaSpb->bpb_status          = $bpb_status;
//            $tmpAnalisaSpb->bpb_tgl_keluar      = $bpb_tgl_keluar;
//            $tmpAnalisaSpb->bpb_tgl_terima      = $bpb_tgl_terima;
//            $tmpAnalisaSpb->bpb_pegawai_keluar  = $bpb_pegawai_keluar;
//            $tmpAnalisaSpb->bpb_pegawai_terima  = $bpb_pegawai_terima;
//            $tmpAnalisaSpb->departement_nama    = $spb->departement->departement_nama;
//            $tmpAnalisaSpb->user_id             = Yii::$app->user->id;
//            $tmpAnalisaSpb->save();
//        }
//    }

    public function actionLaporanSPBPrint() 
    {
        $this->layout       = '@views/layouts/metronic/print';
        $caraprint          = Yii::$app->request->get('caraprint');
        $paramprint['judul']= Yii::t('app', 'Analisa Pembelian SPB');
        $model              = TmpAnalisaSpb::find()->where(['user_id' => Yii::$app->user->id])->orderBy('spb_tanggal')->all();
        if($caraprint === 'EXCEL') {
            return $this->renderPartial('/laporan/laporanSPB/print', compact('model', 'paramprint'));
        }
    }

    public function actionInfoSpb()
    {
        $kode       = Yii::$app->request->get('kode');
        $model      = \app\models\TSpb::find()->with('tSpbDetails')->where(['spb_kode' => $kode])->one();
        return $this->renderAjax('laporanSPB/info/infoSpb',['model'=>$model]);
    }

    public function actionInfoSpp()
    {
        $kode       = Yii::$app->request->get('kode');
        $model      = \app\models\TSpp::find()->with('tSppDetails')->where(['spp_kode' => $kode])->one();
        return $this->renderAjax('laporanSPB/info/infoSpp',['model'=>$model]);
    }

    public function actionInfoBpb()
    {
        $kode       = Yii::$app->request->get('kode');
        $model      = TBpb::find()->with('tBpbDetails')->where(['bpb_kode' => $kode])->one();
        return $this->renderAjax('laporanSPB/info/infoBpb',['model'=>$model]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionInfoTbp()
    {
        $kode       = Yii::$app->request->get('kode');
        $spb_kode = Yii::$app->request->get('spb_kode');
        $sql = "SELECT C
                    .terima_bhpd_id 
                FROM
                    t_terima_bhp_detail
                    C INNER JOIN t_terima_bhp d ON C.terima_bhp_id = d.terima_bhp_id 
                WHERE
                    d.terimabhp_kode = '$kode' 
                    AND C.bhp_id IN ( SELECT A.bhp_id FROM t_spb_detail A INNER JOIN t_spb b ON A.spb_id = b.spb_id WHERE b.spb_kode = '$spb_kode' )";
        $query = Yii::$app->db->createCommand($sql)->queryAll();
        $mark_spb = [];
        if(count($query) > 0) {
            foreach ($query as $el) {
                $mark_spb[] = $el['terima_bhpd_id'];
            }
        }
        $model      = TTerimaBhp::find()->with('tTerimaBhpDetails')->where(['terimabhp_kode' => $kode])->one();
        return $this->renderAjax('laporanSPB/info/infoTbp', compact('model', 'mark_spb'));
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionInfoSplSpo()
    {
        $kode   = Yii::$app->request->get('kode');
        $spb_kode = Yii::$app->request->get('spb_kode');
        if(strpos($kode, 'SPO') !== false) {
            $sql = "SELECT
                        map_spp_detail_reff.reff_detail_id 
                    FROM
                        map_spp_detail_reff
                        INNER JOIN map_spb_detail_spp_detail ON map_spp_detail_reff.sppd_id = map_spb_detail_spp_detail.sppd_id
                        INNER JOIN t_spb_detail ON map_spb_detail_spp_detail.spbd_id = t_spb_detail.spbd_id
                        INNER JOIN t_spb ON t_spb.spb_id = t_spb_detail.spb_id 
                    WHERE
                        t_spb.spb_kode = '$spb_kode' 
                        AND map_spp_detail_reff.reff_no = '$kode' 
                    GROUP BY
                        map_spp_detail_reff.reff_detail_id";
            $query = Yii::$app->db->createCommand($sql)->queryAll();
            $mark_spb = [];
            if(count($query) > 0) {
                foreach ($query as $el) {
                    $mark_spb[] = $el['reff_detail_id'];
                }
            }
            $model      = TSpo::find()->with('tSpoDetails')->where(['spo_kode' => $kode])->one();
            return $this->renderAjax('laporanSPB/info/infoSpo',['model' => $model, 'mark_spb' => $mark_spb]);
        }

        $sql_map = "SELECT
                        map_spb_detail_spp_detail.sppd_id
                    FROM
                        t_spb
                        INNER JOIN t_spb_detail ON t_spb.spb_id = t_spb_detail.spb_id
                        INNER JOIN map_spb_detail_spp_detail ON map_spb_detail_spp_detail.spbd_id = t_spb_detail.spbd_id
                    WHERE
                        t_spb.spb_kode = '$spb_kode'";
        $query = Yii::$app->db->createCommand($sql_map)->queryAll();
        $mark_spb = [];
        if(count($query) > 0) {
            foreach ($query as $el) {
                $mark_spb[] = $el['sppd_id'];
            }
        }

        $model      = TSpl::find()->with('tSplDetails')->where(['spl_kode' => $kode])->one();
        return $this->renderAjax('laporanSPB/info/infoSpl',['model' => $model, 'mark_spb' => $mark_spb]);
    }



    ################################################################################################################################
    public function actionBudgetPenerimaanBhp()
    {
        $model = new \app\models\TTerimaBhpSub();
        $model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TTerimaBhpSub'];
				$model->tgl_awal = $form_params['TTerimaBhpSub']['tgl_awal'];
				$model->tgl_akhir = $form_params['TTerimaBhpSub']['tgl_akhir'];
				$model->bhp_nm = $form_params['TTerimaBhpSub']['bhp_nm'];
				$model->target_plan = $form_params['TTerimaBhpSub']['target_plan'];
                $model->target_peruntukan = $form_params['TTerimaBhpSub']['target_peruntukan'];
				$model->departement_id = $form_params['TTerimaBhpSub']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('budgetPenerimaanBhp/index',['model'=>$model]);  
    }

	public function actionBudgetPenerimaanBhpTotal()
    {
        $model = new \app\models\TTerimaBhpSub();
        $param = Yii::$app->request->get('TTerimaBhpSub');
        $model->attributes              = $param;
        $model->tgl_awal                = $param['tgl_awal'];
        $model->tgl_akhir               = $param['tgl_akhir'];
		$model->bhp_nm               	= $param['bhp_nm'];
        $model->target_plan 			= $param['target_plan'];
        $model->target_peruntukan 		= $param['target_peruntukan'];
		$model->departement_id 			= $param['departement_id'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
            // $total += $row['total'];
			$total += ($row['qty'] * $row['harga_peritem']);
        }
        return Json::encode(['total' => $total]);
    }

    public function actionBudgetPenerimaanBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhpSub();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhpSub'];
		$model->tgl_awal = !empty($_GET['TTerimaBhpSub']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpSub']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhpSub']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpSub']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TTerimaBhpSub']['bhp_nm'];
		$model->target_plan = $_GET['TTerimaBhpSub']['target_plan'];
        $model->target_peruntukan = $_GET['TTerimaBhpSub']['target_peruntukan'];
		$model->departement_id = $_GET['TTerimaBhpSub']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Budget Penerimaan Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/budgetPenerimaanBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/budgetPenerimaanBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/budgetPenerimaanBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

    public function actionGetPeruntukan($departement_id)
    {
        $departement_id = Yii::$app->request->get('departement_id');
        $query = "
					SELECT name FROM m_default_value 
					WHERE type = 'peruntukan-".$departement_id."'
					ORDER BY sequence_number ASC
					;
			 	";
        $target_peruntukan = Yii::$app->db->createCommand($query)->queryAll();
        if(!empty($target_peruntukan)){
            echo "<option value=''>All</option>";
            foreach($target_peruntukan as $peruntukan){
                echo "<option value='".$peruntukan['name']."'>".$peruntukan['name']."</option>";
            }
        } else {
            echo "<option value=''>All</option>";
        }
    }

    public function actionBudgetPemakaianBhp()
    {
        $model = new \app\models\TPemakaianBhpsub();
        $model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TPemakaianBhpsub'];
				$model->tgl_awal = $form_params['TPemakaianBhpsub']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPemakaianBhpsub']['tgl_akhir'];
				$model->bhp_nm = $form_params['TPemakaianBhpsub']['bhp_nm'];
				$model->target_plan = $form_params['TPemakaianBhpsub']['target_plan'];
                $model->target_peruntukan = $form_params['TPemakaianBhpsub']['target_peruntukan'];
				$model->departement_id = $form_params['TPemakaianBhpsub']['departement_id'];
				$model->asset_peruntukan = $form_params['TPemakaianBhpsub']['asset_peruntukan'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('budgetPemakaianBhp/index',['model'=>$model]);  
    }

	public function actionBudgetPemakaianBhpTotal()
    {
        $model = new \app\models\TPemakaianBhpsub();
        $param = Yii::$app->request->get('TPemakaianBhpsub');
        $model->attributes              = $param;
        $model->tgl_awal                = $param['tgl_awal'];
        $model->tgl_akhir               = $param['tgl_akhir'];
		$model->bhp_nm 					= $param['bhp_nm'];
        $model->target_plan 			= $param['target_plan'];
        $model->target_peruntukan 		= $param['target_peruntukan'];
		$model->departement_id 			= $param['departement_id'];
		$model->asset_peruntukan 		= $param['asset_peruntukan'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
            // $total += $row['total'];
			$total += ($row['qty'] * $row['harga_peritem']);
        }
        return Json::encode(['total' => $total]);
    }

    public function actionBudgetPemakaianBhpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPemakaianBhpsub();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPemakaianBhpsub'];
		$model->tgl_awal = !empty($_GET['TPemakaianBhpsub']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TPemakaianBhpsub']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPemakaianBhpsub']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TPemakaianBhpsub']['tgl_akhir']):"";
		$model->bhp_nm = $_GET['TPemakaianBhpsub']['bhp_nm'];
		$model->target_plan = $_GET['TPemakaianBhpsub']['target_plan'];
        $model->target_peruntukan = $_GET['TPemakaianBhpsub']['target_peruntukan'];
		$model->departement_id = $_GET['TPemakaianBhpsub']['departement_id'];
		$model->asset_peruntukan = $_GET['TPemakaianBhpsub']['asset_peruntukan'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Budget Pemakaian Bahan Pembantu');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/budgetPemakaianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/budgetPemakaianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/budgetPemakaianBhp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

    public function actionStockBudgeting()
    {
        $model = new \app\models\ViewStockItemsub();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['ViewStockItemsub'];
				$model->target_plan = $form_params['ViewStockItemsub']['target_plan'];
                $model->target_peruntukan = $form_params['ViewStockItemsub']['target_peruntukan'];
				$model->departement_id = $form_params['ViewStockItemsub']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('stockBudgeting/index',['model'=>$model]);  
    }

	public function actionStockBudgetingTotal()
    {
        $model = new \app\models\ViewStockItemsub();
        $param = Yii::$app->request->get('ViewStockItemsub');
        $model->attributes              = $param;
        $model->target_plan 			= $param['target_plan'];
        $model->target_peruntukan 		= $param['target_peruntukan'];
		$model->departement_id 			= $param['departement_id'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
            // $total += $row['total'];
			$total += ($row['jumlah'] * $row['harga_peritem']);
        }
        return Json::encode(['total' => $total]);
    }

	public function actionStockBudgetingPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\ViewStockItemsub();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['ViewStockItemsub'];
		$model->target_plan = $_GET['ViewStockItemsub']['target_plan'];
        $model->target_peruntukan = $_GET['ViewStockItemsub']['target_peruntukan'];
		$model->departement_id = $_GET['ViewStockItemsub']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Stock Budgeting');
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/StockBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/StockBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/stockBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionCompareBudgeting()
    {
        $model = new \app\models\ViewCompareItemsub();
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['ViewCompareItemsub'];
				$model->target_plan = $form_params['ViewCompareItemsub']['target_plan'];
                $model->target_peruntukan = $form_params['ViewCompareItemsub']['target_peruntukan'];
				$model->departement_id = $form_params['ViewCompareItemsub']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('compareBudgeting/index',['model'=>$model]);  
    }
	public function actionCompareBudgetingPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\ViewCompareItemsub();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['ViewCompareItemsub'];
		$model->target_plan = $_GET['ViewCompareItemsub']['target_plan'];
        $model->target_peruntukan = $_GET['ViewCompareItemsub']['target_peruntukan'];
		$model->departement_id = $_GET['ViewCompareItemsub']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Compare Budgeting (Terima VS Realisasi Pemakaian)');
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/CompareBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/CompareBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/CompareBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	public function actionInfoTraceStock($reff_detail_id){
		if(Yii::$app->request->isAjax){
			$reff_detail_id = $reff_detail_id;
			$view_stock = Yii::$app->db->createCommand(
				'select a.reff_detail_id, b.kode, c.bhp_nm, jumlah, b.target_plan, b.target_peruntukan, e.departement_nama as dept_peruntukan, 
				b.departement_id, b.keterangan
				from view_stock_itemsub a
				join t_terima_bhp_sub b on b.terima_bhp_sub_id = a.reff_detail_id
				join m_brg_bhp c on c.bhp_id = a.bhp_id
				left join t_pemakaian_bhpsub_detail d on d.terima_bhp_sub_id = b.terima_bhp_sub_id
				left join m_departement e on e.departement_id = d.dept_peruntukan
				where a.reff_detail_id = '.$reff_detail_id
				)->queryAll();
			
            return $this->renderAjax('/laporan/stockBudgeting/infoTraceStock', ['reff_detail_id'=>$reff_detail_id, 'view_stock'=>$view_stock]);
		}
	}

	public function actionInfoTraceStockDep($reff_detail_id, $dept_id){
		if(Yii::$app->request->isAjax){
			$reff_detail_id = $reff_detail_id;
			$view_stock = Yii::$app->db->createCommand(
				'select a.reff_detail_id, b.kode, c.bhp_nm, jumlah, b.target_plan, b.target_peruntukan, e.departement_nama as dept_peruntukan, 
				b.departement_id, b.keterangan
				from view_stock_itemsub a
				join t_terima_bhp_sub b on b.terima_bhp_sub_id = a.reff_detail_id
				join m_brg_bhp c on c.bhp_id = a.bhp_id
				left join t_pemakaian_bhpsub_detail d on d.terima_bhp_sub_id = b.terima_bhp_sub_id
				left join m_departement e on e.departement_id = d.dept_peruntukan
				where a.reff_detail_id = '.$reff_detail_id.'and d.dept_peruntukan = '. $dept_id
				)->queryAll();
			
            return $this->renderAjax('/laporan/stockBudgeting/infoTraceStock', ['reff_detail_id'=>$reff_detail_id, 'view_stock'=>$view_stock]);
		}
	}
	public function actionPenyerapanBudgeting()
    {
		$model = new \app\models\ViewPenyerapanBudget();
		$today = date('Y-m-d');
		$periodeSekarang = date('F Y', strtotime($today));
        $model->tgl_awal = $periodeSekarang;
		$model->tgl_akhir = $periodeSekarang;
        $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
		
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['ViewPenyerapanBudget'];
				$model->tgl_awal = $form_params['ViewPenyerapanBudget']['tgl_awal'];
				$model->tgl_akhir = $form_params['ViewPenyerapanBudget']['tgl_akhir'];
				$model->target_plan = $form_params['ViewPenyerapanBudget']['target_plan'];
                $model->target_peruntukan = $form_params['ViewPenyerapanBudget']['target_peruntukan'];
				$model->departement_id = $form_params['ViewPenyerapanBudget']['departement_id'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('penyerapanBudgeting/index',['model'=>$model]); 
    }
	public function actionPenyerapanBudgetingPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\ViewPenyerapanBudget();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['ViewPenyerapanBudget'];
		$model->tgl_awal = !empty($_GET['ViewPenyerapanBudget']['tgl_awal'])? $_GET['ViewPenyerapanBudget']['tgl_awal']:"";
		$model->tgl_akhir = !empty($_GET['ViewPenyerapanBudget']['tgl_akhir'])? $_GET['ViewPenyerapanBudget']['tgl_akhir']:"";
		$model->target_plan = $_GET['ViewPenyerapanBudget']['target_plan'];
        $model->target_peruntukan = $_GET['ViewPenyerapanBudget']['target_peruntukan'];
		$model->departement_id = $_GET['ViewPenyerapanBudget']['departement_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Penyerapan Budget');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode ". $model->tgl_awal." s/d ". $model->tgl_akhir;
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/penyerapanBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/penyerapanBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/penyerapanBudgeting/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	public function actionGetAssetPeruntukan($departement_id)
    {
        $departement_id = Yii::$app->request->get('departement_id');
		if(!empty($departement_id)){
			$query = "
					SELECT inventaris_id, kode, inventaris_nama FROM m_inventaris 
					WHERE peruntukan_dept = $departement_id
					ORDER BY kode ASC
					;";
		} else {
			$query = "
					SELECT inventaris_id, kode, inventaris_nama FROM m_inventaris 
					ORDER BY kode ASC
					;";
		}
        
        $asset_peruntukan = Yii::$app->db->createCommand($query)->queryAll();
        if(!empty($asset_peruntukan)){
            echo "<option value=''></option>";
            foreach($asset_peruntukan as $peruntukan){
                echo "<option value='".$peruntukan['inventaris_id']."'>".$peruntukan['kode'] ." - ".$peruntukan['inventaris_nama']."</option>";
            }
        } else {
            echo "<option value=''></option>";
        }
    }

	public function actionRekapBiayaAsset()
    {
        $model = new \app\models\TPemakaianBhpsub();
        $model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        $model->departement_id = Yii::$app->user->identity->pegawai->departement_id;
        if(Yii::$app->request->get('dt')=='table-laporan'){
			if((Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TPemakaianBhpsub'];
				$model->tgl_awal = $form_params['TPemakaianBhpsub']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPemakaianBhpsub']['tgl_akhir'];
				$model->target_plan = $form_params['TPemakaianBhpsub']['target_plan'];
				$model->departement_id = $form_params['TPemakaianBhpsub']['departement_id'];
				$model->asset_peruntukan = $form_params['TPemakaianBhpsub']['asset_peruntukan'];
			}
			return Json::encode(SSP::complex( $model->searchLaporanRekapAssetDt() ));
		}
		return $this->render('rekapBiayaAsset/index',['model'=>$model]);  
    }

	public function actionRekapBiayaAssetTotal()
    {
        $model = new \app\models\TPemakaianBhpsub();
        $param = Yii::$app->request->get('TPemakaianBhpsub');
        $model->attributes              = $param;
        $model->tgl_awal                = $param['tgl_awal'];
        $model->tgl_akhir               = $param['tgl_akhir'];
        $model->target_plan 			= $param['target_plan'];
		$model->departement_id 			= $param['departement_id'];
		$model->asset_peruntukan 		= $param['asset_peruntukan'];
        $total  = 0;
		foreach ($model->searchLaporanRekapAsset()->createCommand()->queryAll() as $row) {
			$total += $row['total']; 
		}
        return Json::encode(['total' => $total]);
    }

	public function actionRekapBiayaAssetPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPemakaianBhpsub();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPemakaianBhpsub'];
		$model->tgl_awal = !empty($_GET['TPemakaianBhpsub']['tgl_awal'])? DeltaFormatter::formatDateTimeForDb($_GET['TPemakaianBhpsub']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPemakaianBhpsub']['tgl_akhir'])? DeltaFormatter::formatDateTimeForDb($_GET['TPemakaianBhpsub']['tgl_akhir']):"";
		$model->target_plan = $_GET['TPemakaianBhpsub']['target_plan'];
		$model->departement_id = $_GET['TPemakaianBhpsub']['departement_id'];
		$model->asset_peruntukan = $_GET['TPemakaianBhpsub']['asset_peruntukan'];
		$paramprint['judul'] = Yii::t('app', 'Rekap Biaya Asset');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/rekapBiayaAsset/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/rekapBiayaAsset/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/rekapBiayaAsset/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}