<?php

namespace app\modules\qms\controllers;

use Yii;
use app\controllers\DeltaBaseController;
use app\models\MDokumen;

class LaporanController extends DeltaBaseController
{
	public function actionDokumen()
	{
		$model = new \app\models\MDokumen();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['MDokumen'];
                $model->kategori_dokumen = $form_params['MDokumen']['kategori_dokumen'];
				$model->jenis_dokumen = $form_params['MDokumen']['jenis_dokumen'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/dokumen/index', ['model' => $model]);
	}

    public function actionDokumenPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MDokumen();
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Laporan Master Dokumen');
		$paramprint['judul2'] = "";
		$model->attributes = $_GET['MDokumen'];
		$model->kategori_dokumen = !empty($_GET['MDokumen']['kategori_dokumen']) ? $_GET['MDokumen']['kategori_dokumen'] : "";
		$model->jenis_dokumen = !empty($_GET['MDokumen']['jenis_dokumen']) ? $_GET['MDokumen']['jenis_dokumen'] : "";
        if($model->kategori_dokumen){
            $paramprint['judul2'] .= "Kategori Dokumen " . $model->kategori_dokumen .'<br>';
        }
		if($model->jenis_dokumen){
            $paramprint['judul2'] .= "Jenis Dokumen " . $model->jenis_dokumen;
        }
		// $maxTanggal = $model->searchLaporan()
		// 				->select('MAX(t_dokumen_revisi.tanggal_berlaku) AS max_tanggal')
		// 				->groupBy('m_dokumen.dokumen_id')
		// 				->orderBy(['max_tanggal' => SORT_DESC])
		// 				->asArray()
		// 				->all();
		// $paramprint['judul2'] .= '<br>Update : '.\app\components\DeltaFormatter::formatDateTimeId($maxTanggal[0]['max_tanggal']);

		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/dokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/dokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/dokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionDokumenrevisi()
	{
		$model = new \app\models\TDokumenRevisi();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TDokumenRevisi'];
				$model->kategori_dokumen = $form_params['TDokumenRevisi']['kategori_dokumen'];
				$model->nomor_dokumen = $form_params['TDokumenRevisi']['nomor_dokumen'];
				$model->jenis_dokumen = $form_params['TDokumenRevisi']['jenis_dokumen'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/dokumenrevisi/index', ['model' => $model]);
	}

	public function actionDokumenrevisiPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenRevisi();
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Laporan Revisi Dokumen');
		$paramprint['judul2'] = "";
		$model->attributes = $_GET['TDokumenRevisi'];
		$model->kategori_dokumen = !empty($_GET['TDokumenRevisi']['kategori_dokumen']) ? $_GET['TDokumenRevisi']['kategori_dokumen'] : "";
		$model->nomor_dokumen = !empty($_GET['TDokumenRevisi']['nomor_dokumen']) ? $_GET['TDokumenRevisi']['nomor_dokumen'] : "";
		$model->jenis_dokumen = !empty($_GET['TDokumenRevisi']['jenis_dokumen']) ? $_GET['TDokumenRevisi']['jenis_dokumen'] : "";
        if($model->kategori_dokumen){
            $paramprint['judul2'] .= "Kategori Dokumen " . $model->kategori_dokumen ."<br>";
        }
		if($model->nomor_dokumen){
            $paramprint['judul2'] .= "Nomor Dokumen " . $model->nomor_dokumen ."<br>";
        }
		if($model->jenis_dokumen){
            $paramprint['judul2'] .= "Jenis Dokumen " . $model->jenis_dokumen;
        }

		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/dokumenrevisi/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/dokumenrevisi/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/dokumenrevisi/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionDokumendistribusi()
	{
		$model = new \app\models\TDokumenDistribusi();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				$model->attributes = $form_params['TDokumenDistribusi'];
				$model->tgl_awal = $form_params['TDokumenDistribusi']['tgl_awal'];
				$model->tgl_akhir = $form_params['TDokumenDistribusi']['tgl_akhir'];
				$model->kategori_dokumen = $form_params['TDokumenDistribusi']['kategori_dokumen'];
				$model->nomor_dokumen = $form_params['TDokumenDistribusi']['nomor_dokumen'];
				$model->jenis_dokumen = $form_params['TDokumenDistribusi']['jenis_dokumen'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanDt()));
		}
		return $this->render('/laporan/dokumendistribusi/index', ['model' => $model]);
	}

	public function actionDokumendistribusiPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TDokumenDistribusi();
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Laporan Distribusi Dokumen');
		$paramprint['judul2'] = "";
		$model->attributes = $_GET['TDokumenDistribusi'];
		$model->tgl_awal = !empty($_GET['TDokumenDistribusi']['tgl_awal']) ? $_GET['TDokumenDistribusi']['tgl_awal'] : "";
		$model->tgl_akhir = !empty($_GET['TDokumenDistribusi']['tgl_akhir']) ? $_GET['TDokumenDistribusi']['tgl_akhir'] : "";
		$model->kategori_dokumen = !empty($_GET['TDokumenDistribusi']['kategori_dokumen']) ? $_GET['TDokumenDistribusi']['kategori_dokumen'] : "";
		$model->nomor_dokumen = !empty($_GET['TDokumenDistribusi']['nomor_dokumen']) ? $_GET['TDokumenDistribusi']['nomor_dokumen'] : "";
		$model->jenis_dokumen = !empty($_GET['TDokumenDistribusi']['jenis_dokumen']) ? $_GET['TDokumenDistribusi']['jenis_dokumen'] : "";
		if($model->tgl_awal == $model->tgl_akhir){
			$paramprint['judul2'] = "Tanggal <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u><br>";
		}else{
			$paramprint['judul2'] = "Periode Tanggal <u>". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)."</u> sd <u>".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir)."</u><br>";
		}
        if($model->kategori_dokumen){
            $paramprint['judul2'] .= "Kategori Dokumen " . $model->kategori_dokumen ."<br>";
        }
		if($model->nomor_dokumen){
            $paramprint['judul2'] .= "Nomor Dokumen " . $model->nomor_dokumen ."<br>";
        }
		if($model->jenis_dokumen){
            $paramprint['judul2'] .= "Jenis Dokumen " . $model->jenis_dokumen;
        }

		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/dokumendistribusi/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/dokumendistribusi/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/dokumendistribusi/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionIndukdokumen(){
		$model = new \app\models\MDokumen();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				// $model->attributes = $form_params['MDokumen'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanIndukDt()));
		}
		return $this->render('/laporan/indukdokumen/index', ['model' => $model]);
	}

	public function actionIndukdokumenPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MDokumen();
		$departement_id = Yii::$app->user->identity->pegawai->departement_id;
		$modDep = \app\models\MDepartement::findOne($departement_id);
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Daftar Induk Dokumen');
		$paramprint['judul2'] = "Bagian : " . $modDep->departement_nama ."<br>";
		$maxTanggal = $model->searchLaporanInduk()
						->select('MAX(t_dokumen_revisi.tanggal_berlaku) AS max_tanggal')
						->groupBy('m_dokumen.dokumen_id')
						->orderBy(['max_tanggal' => SORT_DESC])
						->asArray()
						->all();
		if($maxTanggal){
			$max_tgl = $maxTanggal[0]['max_tanggal'];
		} else {
			$max_tgl = date('Y-m-d');
		}
		$paramprint['judul2'] .= 'Update : '.\app\components\DeltaFormatter::formatDateTimeId($max_tgl);
		// $model->attributes = $_GET['MDokumen'];

		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/indukdokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/indukdokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/indukdokumen/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}

	public function actionIndukdokumenall(){
		$model = new \app\models\MDokumen();
		if (\Yii::$app->request->get('dt') == 'table-laporan') {
			if ((\Yii::$app->request->get('laporan_params')) !== null) {
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'), $form_params);
				// $model->attributes = $form_params['MDokumen'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex($model->searchLaporanIndukAllDt()));
		}
		return $this->render('/laporan/indukdokumenall/index', ['model' => $model]);
	}

	public function actionIndukdokumenallPrint()
	{
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\MDokumen();
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'Daftar Induk Dokumen');
		$maxTanggal = $model->searchLaporanIndukAll()
						->select('MAX(t_dokumen_revisi.tanggal_berlaku) AS max_tanggal')
						->groupBy('m_dokumen.dokumen_id')
						->orderBy(['max_tanggal' => SORT_DESC])
						->asArray()
						->all();
		if($maxTanggal){
			$max_tgl = $maxTanggal[0]['max_tanggal'];
		} else {
			$max_tgl = date('Y-m-d');
		}
		$paramprint['judul2'] = 'Update : '.\app\components\DeltaFormatter::formatDateTimeId($max_tgl);
		// $model->attributes = $_GET['MDokumen'];

		if ($caraprint == 'PRINT') {
			return $this->render('/laporan/indukdokumenall/print', ['model' => $model, 'paramprint' => $paramprint]);
		} else if ($caraprint == 'PDF') {
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'] . '.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: ' . Yii::$app->user->getIdentity()->userProfile->fullname . '||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('/laporan/indukdokumenall/print', ['model' => $model, 'paramprint' => $paramprint]);
			return $pdf->render();
		} else if ($caraprint == 'EXCEL') {
			return $this->render('/laporan/indukdokumenall/print', ['model' => $model, 'paramprint' => $paramprint]);
		}
	}
}
