<?php

namespace app\modules\finance\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class LaporanController extends DeltaBaseController
{	
	public function actionPembayaranTbp(){
		$model = new \app\models\TTerimaBhp();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TTerimaBhp'];
				$model->tgl_awal = $form_params['TTerimaBhp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TTerimaBhp']['tgl_akhir'];
				$model->terimabhp_kode = $form_params['TTerimaBhp']['terimabhp_kode'];
				$model->kode_voucher = $form_params['TTerimaBhp']['kode_voucher'];
				$model->nofaktur = $form_params['TTerimaBhp']['nofaktur'];
				$model->suplier_id = $form_params['TTerimaBhp']['suplier_id'];
				// $model->payment_status = $form_params['TTerimaBhp']['payment_status'];
				$model->bhp_id = $form_params['TTerimaBhp']['bhp_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/pembayarantbp/index',['model'=>$model]);
	}
	
	public function actionPembayaranTbpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhp'];
		$model->tgl_awal = !empty($_GET['TTerimaBhp']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhp']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhp']['tgl_akhir']):"";
		$model->terimabhp_kode = $_GET['TTerimaBhp']['terimabhp_kode'];
		$model->kode_voucher = $_GET['TTerimaBhp']['kode_voucher'];
		$model->nofaktur = $_GET['TTerimaBhp']['nofaktur'];
		$model->suplier_id = $_GET['TTerimaBhp']['suplier_id'];
		// $model->payment_status = $_GET['TTerimaBhp']['payment_status'];
		$model->bhp_id = $_GET['TTerimaBhp']['bhp_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pembayaran Bahan Pembantu Produksi');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pembayarantbp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionVoucherPengeluaran(){
		$model = new \app\models\TVoucherPengeluaran();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TVoucherPengeluaran'];
				$model->tgl_awal = $form_params['TVoucherPengeluaran']['tgl_awal'];
				$model->tgl_akhir = $form_params['TVoucherPengeluaran']['tgl_akhir'];
				$model->kode = $form_params['TVoucherPengeluaran']['kode'];
				$model->tipe = $form_params['TVoucherPengeluaran']['tipe'];
				$model->status_bayar = $form_params['TVoucherPengeluaran']['status_bayar'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/voucherPengeluaran/index',['model'=>$model]);
	}
	
	public function actionVoucherPengeluaranPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TVoucherPengeluaran();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TVoucherPengeluaran'];
		$model->tgl_awal = !empty($_GET['TVoucherPengeluaran']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TVoucherPengeluaran']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_akhir']):"";
		$model->kode = $_GET['TVoucherPengeluaran']['kode'];
		$model->tipe = $_GET['TVoucherPengeluaran']['tipe'];
		$model->status_bayar = $_GET['TVoucherPengeluaran']['status_bayar'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Voucher Pengeluaran');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/voucherPengeluaran/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionTagihanSuplier(){
		$model = new \app\models\TTerimaBhpDetail();
		$model->per_tanggal = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['TTerimaBhpDetail'];
				$model->per_tanggal = $form_params['TTerimaBhpDetail']['per_tanggal'];
				$model->suplier_id = $form_params['TTerimaBhpDetail']['suplier_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanTagihanSuplierDt() ));
		}
		if((\Yii::$app->request->post('getTotalSemua')) !== null){
			$form_params = []; parse_str(\Yii::$app->request->post('laporan_params'),$form_params); 
			$model->suplier_id = $form_params['TTerimaBhpDetail']['suplier_id'];
			$sql = $model->searchLaporanTagihanSuplier()->createCommand()->rawSql;
			$contents = Yii::$app->db->createCommand($sql)->queryAll();
			$data['totaltagihan'] = 0; $data['paid'] = 0; $data['hutang'] = 0;
			if(count($contents)>0){
				foreach($contents as $i => $content){
					$data['totaltagihan'] += $content['totaltagihan'];
					$data['paid'] += $content['paid'];
					$data['hutang'] += $content['hutang'];
				}
			}
			return $this->asJson($data);
		}
		if(\Yii::$app->request->get('show')=='tbp'){
			$suplier_id = \Yii::$app->request->get('suplier_id');
			$modSuplier = \app\models\MSuplier::findOne($suplier_id);
			if(\Yii::$app->request->get('dt')=='table-show'){
				$param['table']= \app\models\TTerimaBhp::tableName();
				$param['pk']= $param['table'].'.'.\app\models\TTerimaBhp::primaryKey()[0];
				$param['column'] = [ $param['table'].'.terima_bhp_id', 'tglterima','terimabhp_kode','spo_kode', 'nofaktur', 'totalbayar', 'status_bayar', 'tanggal_bayar', 't_spo.spo_id', 't_voucher_pengeluaran.kode', 't_terima_bhp.voucher_pengeluaran_id','t_voucher_pengeluaran.total_nominal'];
				$param['join']= ['LEFT JOIN t_spo ON t_spo.spo_id = t_terima_bhp.spo_id
								  LEFT JOIN t_voucher_pengeluaran ON t_voucher_pengeluaran.voucher_pengeluaran_id = t_terima_bhp.voucher_pengeluaran_id
								'];
				$param['where'] = $param['table'].".cancel_transaksi_id IS NULL AND ".$param['table'].".spo_id IS NOT NULL AND ".$param['table'].".suplier_id = ".$suplier_id;
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('/laporan/tagihanSuplier/showTbp',['modSuplier'=>$modSuplier]);
		}
		return $this->render('/laporan/tagihanSuplier/index',['model'=>$model]);
	}
	
	public function actionTagihanSuplierPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TTerimaBhpDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TTerimaBhpDetail'];
		$model->tgl_awal = !empty($_GET['TTerimaBhpDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TTerimaBhpDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TTerimaBhpDetail']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TTerimaBhpDetail']['suplier_id'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Tagihan Suplier BHP');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/tagihanSuplier/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
        public function actionTagihanSuplierBB(){
		$model = new \app\models\ViewTagihanBahanBaku(); //ViewTagihanBahanBaku
		$model->per_tanggal = date('d/m/Y');
                if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params);
				$model->attributes = $form_params['ViewTagihanBahanBaku'];
				$model->per_tanggal = $form_params['ViewTagihanBahanBaku']['per_tanggal'];
				$model->penerima_reff_id = $form_params['ViewTagihanBahanBaku']['penerima_reff_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanTagihanSuplierBBDt() ));
		}
		if((\Yii::$app->request->post('getTotalSemua')) !== null){
			$form_params = []; parse_str(\Yii::$app->request->post('laporan_params'),$form_params); 
			$model->penerima_reff_id = $form_params['ViewTagihanBahanBaku']['penerima_reff_id'];
			$sql = $model->searchLaporanTagihanSuplierBB()->createCommand()->rawSql;
			$contents = Yii::$app->db->createCommand($sql)->queryAll();
			$data['totaltagihan'] = 0; $data['dibayar'] = 0; $data['hutang'] = 0;
			if(count($contents)>0){
				foreach($contents as $i => $content){
					$data['totaltagihan'] += $content['totaltagihan'];
					$data['dibayar'] += $content['dibayar'];
					$data['hutang'] += $content['hutang'];
				}
			}
			return $this->asJson($data);
		}
		if(\Yii::$app->request->get('show')=='tagihan'){
			$suplier_id = \Yii::$app->request->get('suplier_id');
			$modSuplier = \app\models\MSuplier::findOne($suplier_id);
			if(\Yii::$app->request->get('dt')=='table-show'){
				$param['table']= \app\models\TOpenVoucher::tableName();
				$param['pk']= $param['table'].'.'. \app\models\TOpenVoucher::primaryKey()[0];
				$param['column'] = [ $param['table'].'.open_voucher_id', 't_open_voucher.tanggal','t_open_voucher.kode as kode_tagihan','t_open_voucher.reff_no', 't_open_voucher.tipe', 't_open_voucher.total_pembayaran', 't_voucher_pengeluaran.status_bayar', 'tanggal_bayar', 't_voucher_pengeluaran.kode as kode_bayar', 't_open_voucher.voucher_pengeluaran_id','t_voucher_pengeluaran.total_pembayaran'];
				$param['join']= ['LEFT JOIN t_voucher_pengeluaran ON t_voucher_pengeluaran.voucher_pengeluaran_id = t_open_voucher.voucher_pengeluaran_id
								'];
				$param['where'] = $param['table'].".cancel_transaksi_id IS NULL AND ".$param['table'].".status_bayar ='UNPAID' AND ".$param['table'].".penerima_reff_id = ".$suplier_id;
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $param ));
			}
			return $this->renderAjax('/laporan/tagihanSuplierBB/showTbp',['modSuplier'=>$modSuplier]);
		}
		return $this->render('/laporan/tagihanSuplierBB/index',['model'=>$model]);
	}
        
	public function actionKuitansi(){
		$model = new \app\models\TKuitansi();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TKuitansi'];
				$model->tgl_awal = $form_params['TKuitansi']['tgl_awal'];
				$model->tgl_akhir = $form_params['TKuitansi']['tgl_akhir'];
				$model->cara_bayar = $form_params['TKuitansi']['cara_bayar'];
				$model->terima_dari = $form_params['TKuitansi']['terima_dari'];
				$model->untuk_pembayaran = $form_params['TKuitansi']['untuk_pembayaran'];
				
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('/laporan/kuitansi/index',['model'=>$model]);
	}
	
	public function actionKuitansiPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TKuitansi();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TKuitansi'];
		$model->tgl_awal = !empty($_GET['TKuitansi']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKuitansi']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TKuitansi']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TKuitansi']['tgl_akhir']):"";
		$model->cara_bayar = $_GET['TKuitansi']['cara_bayar'];
		$model->terima_dari = $_GET['TKuitansi']['terima_dari'];
		$model->untuk_pembayaran = $_GET['TKuitansi']['untuk_pembayaran'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Kuitansi Penerimaan');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kuitansi/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionPbb(){
		$model = new \app\models\TVoucherPengeluaran();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = [];
				parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TVoucherPengeluaran'];
				$model->tgl_awal = $form_params['TVoucherPengeluaran']['tgl_awal'];
				$model->tgl_akhir = $form_params['TVoucherPengeluaran']['tgl_akhir'];
				$model->kode = $form_params['TVoucherPengeluaran']['kode'];
				$model->tipe = $form_params['TVoucherPengeluaran']['tipe'];
				$model->status_bayar = $form_params['TVoucherPengeluaran']['status_bayar'];
			}
			$tipe = $form_params['TVoucherPengeluaran']['tipe'];
			if ($tipe == "DP LOG SENGON" || $tipe == "PEMBAYARAN LOG ALAM" || $tipe == "PELUNASAN LOG SENGON") {
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPbbDt() ));
			} else if ($tipe == "Pembelian BHP" || $tipe == "Pembayaran DP BHP") {
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
			} else {
				return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanPbbDt() ));
			}
			
		}
		return $this->render('/laporan/pbb/index',['model'=>$model]);
	}

	public function actionPiutangCustomer(){
        $model = new \app\models\TPiutangPenjualan();
		$model->tanggal = date('d/m/Y');
		if(\Yii::$app->request->get('getLaporan')){
			$data['html'] = "";
			$tgl = \Yii::$app->request->get('tgl');
			$data['tgl'] = \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
			$sql = "SELECT t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode ,t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang, sum(t_piutang_penjualan.bayar) AS terbayar, 'lokal' AS tipe 
					FROM t_nota_penjualan 
					JOIN m_customer ON m_customer.cust_id = t_nota_penjualan.cust_id
					LEFT JOIN t_piutang_penjualan ON t_piutang_penjualan.bill_reff = t_nota_penjualan.kode
					WHERE t_nota_penjualan.tanggal <= '$tgl' AND t_nota_penjualan.cancel_transaksi_id IS NULL
					GROUP BY t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode, t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang
					ORDER BY m_customer.cust_an_nama ASC, t_nota_penjualan.tanggal ASC, t_nota_penjualan.kode ASC
					";
			$mods = \Yii::$app->db->createCommand($sql)->queryAll();
			$sql2 = "SELECT t_invoice.cust_id,m_customer.cust_an_nama, t_invoice.nomor AS kode ,t_invoice.tanggal, t_invoice.mata_uang, sum(t_piutang_penjualan.bayar) AS terbayar, 'export' AS tipe
                    FROM t_invoice 
                    JOIN m_customer ON m_customer.cust_id = t_invoice.cust_id
                    LEFT JOIN t_piutang_penjualan ON t_piutang_penjualan.bill_reff = t_invoice.nomor
                    WHERE t_invoice.peb_tanggal IS NOT NULL AND t_invoice.peb_tanggal <= '$tgl' AND t_invoice.cancel_transaksi_id IS NULL AND piutang_active IS TRUE
                    GROUP BY t_invoice.cust_id,m_customer.cust_an_nama, t_invoice.nomor, t_invoice.tanggal, t_invoice.mata_uang
                    ORDER BY m_customer.cust_an_nama ASC, t_invoice.nomor ASC
					";
			$mods2 = \Yii::$app->db->createCommand($sql2)->queryAll();
            if(count($mods2)>0){
                $jmllokal = count($mods);
                foreach($mods2 as $i => $mod2){
                    $mods[ ($jmllokal+$i) ] = $mod2;
                }
            }
			$data['html'] = $this->renderPartial('_contentPiutang',['mods'=>$mods,'tgl'=>$tgl]);
			return $this->asJson($data);
		}		
                return $this->render('/laporan/piutangcustomer/index',['model'=>$model]);
	}	

	public function actionRekapDrp(){
		$model = new \app\models\TPengajuanDrp();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
		$model->status_approve = "APPROVED";
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TPengajuanDrp'];
				$model->tgl_awal = $form_params['TPengajuanDrp']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanDrp']['tgl_akhir'];
				// $model->kategori = $form_params['TPengajuanDrp']['kategori'];
				$model->status_approve = $form_params['TPengajuanDrp']['status_approve'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('rekapDrp/index',['model'=>$model]);
	}

	public function actionRekapDrpTotal()
    {
        $model = new \app\models\TPengajuanDrp();
        $param = Yii::$app->request->get('TPengajuanDrp');
        $model->attributes  	= $param;
        $model->tgl_awal		= $param['tgl_awal'];
		$model->tgl_akhir 		= $param['tgl_akhir'];
		// $model->kategori 		= $param['kategori'];
		$model->status_approve 	= $param['status_approve'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
			$total += $row['total_jml'];
        }
        return \yii\helpers\Json::encode(['total' => $total]);
    }

	public function actionRekapDrpPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPengajuanDrp();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanDrp'];
		$model->tgl_awal = !empty($_GET['TPengajuanDrp']['tgl_awal'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrp']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPengajuanDrp']['tgl_akhir'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrp']['tgl_akhir']):"";
		// $model->kategori = $_GET['TPengajuanDrp']['kategori'];
		$model->status_approve = $_GET['TPengajuanDrp']['status_approve'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Rekap Rencana Pembayaran');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/rekapDrp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/rekapDrp/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/rekapDrp/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionDrpDetail(){
		$model = new \app\models\TPengajuanDrpDetail();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
		$model->status_approve = "APPROVED";
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TPengajuanDrpDetail'];
				$model->tgl_awal = $form_params['TPengajuanDrpDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanDrpDetail']['tgl_akhir'];
				$model->kategori = $form_params['TPengajuanDrpDetail']['kategori'];
				$model->status_approve = $form_params['TPengajuanDrpDetail']['status_approve'];
				$model->kode = $form_params['TPengajuanDrpDetail']['kode'];
				$model->status_bayar = $form_params['TPengajuanDrpDetail']['status_bayar'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('drpDetail/index',['model'=>$model]);
	}

	public function actionDrpDetailTotal()
    {
        $model = new \app\models\TPengajuanDrpDetail();
        $param = Yii::$app->request->get('TPengajuanDrpDetail');
        $model->attributes  	= $param;
        $model->tgl_awal		= $param['tgl_awal'];
		$model->tgl_akhir 		= $param['tgl_akhir'];
		$model->kategori 		= $param['kategori'];
		$model->status_approve 	= $param['status_approve'];
		$model->kode 			= $param['kode'];
		$model->status_bayar 	= $param['status_bayar'];
        $total  = 0; 
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
			$total += $row['total_nominal'];
        }
        return \yii\helpers\Json::encode(['total' => $total]);
    }

	public function actionDrpDetailPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model 		= new \app\models\TPengajuanDrpDetail();
		$caraprint 	= Yii::$app->request->get('caraprint');
		$model->attributes 		= $_GET['TPengajuanDrpDetail'];
		$model->tgl_awal 		= !empty($_GET['TPengajuanDrpDetail']['tgl_awal'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrpDetail']['tgl_awal']):"";
		$model->tgl_akhir 		= !empty($_GET['TPengajuanDrpDetail']['tgl_akhir'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrpDetail']['tgl_akhir']):"";
		$model->kategori 		= $_GET['TPengajuanDrpDetail']['kategori'];
		$model->status_approve 	= $_GET['TPengajuanDrpDetail']['status_approve'];
		$model->kode 			= $_GET['TPengajuanDrpDetail']['kode'];
		$model->status_bayar 	= $_GET['TPengajuanDrpDetail']['status_bayar'];
		$paramprint['judul'] 	= Yii::t('app', 'Laporan Daftar Rencana Pembayaran');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/drpDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/drpDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/drpDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionOpenVoucher(){
		$model = new \app\models\TOpenVoucher();
		$model->tgl_awal = date('d/m/Y', strtotime('first day of this month'));
		$model->tgl_akhir = date('d/m/Y');
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params 			= []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes 		= $form_params['TOpenVoucher'];
				$model->tgl_awal 		= $form_params['TOpenVoucher']['tgl_awal'];
				$model->tgl_akhir 		= $form_params['TOpenVoucher']['tgl_akhir'];
				$model->tipe 			= $form_params['TOpenVoucher']['tipe'];
				$model->departement_id 	= $form_params['TOpenVoucher']['departement_id'];
				$model->cara_bayar 		= $form_params['TOpenVoucher']['cara_bayar'];
				$model->status_bayar 	= $form_params['TOpenVoucher']['status_bayar'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('openVoucher/index',['model'=>$model]);
	}

	public function actionOpenVoucherTotal()
    {
        $model = new \app\models\TOpenVoucher();
        $param = Yii::$app->request->get('TOpenVoucher');
        $model->attributes  	= $param;
        $model->tgl_awal		= $param['tgl_awal'];
		$model->tgl_akhir 		= $param['tgl_akhir'];
		$model->tipe 			= $param['tipe'];
		$model->departement_id 	= $param['departement_id'];
		$model->cara_bayar 		= $param['cara_bayar'];
		$model->status_bayar 	= $param['status_bayar'];
        $total  = 0;
        foreach($model->searchLaporan()->createCommand()->query() as $row) {
			$total += $row['total_pembayaran'];
        }
        return \yii\helpers\Json::encode(['total' => $total]);
    }

	public function actionOpenVoucherPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model 		= new \app\models\TOpenVoucher();
		$caraprint 	= Yii::$app->request->get('caraprint');
		$model->attributes 		= $_GET['TOpenVoucher'];
		$model->tgl_awal 		= !empty($_GET['TOpenVoucher']['tgl_awal'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TOpenVoucher']['tgl_awal']):"";
		$model->tgl_akhir 		= !empty($_GET['TOpenVoucher']['tgl_akhir'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TOpenVoucher']['tgl_akhir']):"";
		$model->tipe 			= $_GET['TOpenVoucher']['tipe'];
		$model->departement_id 	= $_GET['TOpenVoucher']['departement_id'];
		$model->cara_bayar 		= $_GET['TOpenVoucher']['cara_bayar'];
		$model->status_bayar 	= $_GET['TOpenVoucher']['status_bayar'];
		$paramprint['judul'] 	= Yii::t('app', 'Laporan Open Voucher');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/openVoucher/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/openVoucher/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/openVoucher/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionDrpDetailPrintRelease(){
		$this->layout = '@views/layouts/metronic/print';
		$model 		= new \app\models\TPengajuanDrpDetail();
		$caraprint 	= Yii::$app->request->get('caraprint');
		$model->attributes 		= $_GET['TPengajuanDrpDetail'];
		$model->tgl_awal 		= !empty($_GET['TPengajuanDrpDetail']['tgl_awal'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrpDetail']['tgl_awal']):"";
		$model->tgl_akhir 		= !empty($_GET['TPengajuanDrpDetail']['tgl_akhir'])? \app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanDrpDetail']['tgl_akhir']):"";
		$model->kategori 		= $_GET['TPengajuanDrpDetail']['kategori'];
		$model->status_approve 	= $_GET['TPengajuanDrpDetail']['status_approve'];
		$model->kode 			= $_GET['TPengajuanDrpDetail']['kode'];
		$model->status_bayar 	= $_GET['TPengajuanDrpDetail']['status_bayar'];
		$paramprint['judul'] 	= Yii::t('app', 'Laporan Daftar Rencana Pembayaran');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/drpDetail/printRelease',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/drpDetail/printRelease',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/drpDetail/printRelease',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionPbbPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TVoucherPengeluaran();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TVoucherPengeluaran'];
		$model->tgl_awal = !empty($_GET['TVoucherPengeluaran']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TVoucherPengeluaran']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TVoucherPengeluaran']['tgl_akhir']):"";
		$model->kode = $_GET['TVoucherPengeluaran']['kode'];
		$model->tipe = $_GET['TVoucherPengeluaran']['tipe'];
		$model->status_bayar = $_GET['TVoucherPengeluaran']['status_bayar'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Pembelian Bahan Baku');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		$tipe = $_GET['TVoucherPengeluaran']['tipe'];
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/pbb/print',['model'=>$model,'paramprint'=>$paramprint, 'tipe'=>$tipe]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/pbb/print',['model'=>$model,'paramprint'=>$paramprint, 'tipe'=>$tipe]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/pbb/print',['model'=>$model,'paramprint'=>$paramprint, 'tipe'=>$tipe]);
		}
	}

}
