<?php

namespace app\modules\finance\controllers;

use Yii;
use app\controllers\DeltaBaseController;

class PiutangcustomerController extends DeltaBaseController
{
	public $defaultAction = 'index';
	public function actionIndex(){
        $model = new \app\models\TPiutangPenjualan();
		$model->tanggal = date('d/m/Y');
		if(\Yii::$app->request->get('getLaporan')){
			$data['html'] = "";
			$tgl = \Yii::$app->request->get('tgl');
			$data['tgl'] = \app\components\DeltaFormatter::formatDateTimeForUser($tgl);
			$sql = "SELECT t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode ,t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang, sum(t_piutang_penjualan.bayar) AS terbayar, 'lokal' AS tipe 
					FROM t_nota_penjualan 
					JOIN m_customer ON m_customer.cust_id = t_nota_penjualan.cust_id
					LEFT JOIN t_piutang_penjualan ON t_piutang_penjualan.bill_reff = t_nota_penjualan.kode
					WHERE t_nota_penjualan.tanggal <= '$tgl' AND t_nota_penjualan.cancel_transaksi_id IS NULL
					GROUP BY t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode, t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang
					ORDER BY m_customer.cust_an_nama ASC, t_nota_penjualan.tanggal ASC, t_nota_penjualan.kode ASC
					";
			$mods = \Yii::$app->db->createCommand($sql)->queryAll();
			$sql2 = "SELECT t_invoice.cust_id,m_customer.cust_an_nama, t_invoice.nomor AS kode ,t_invoice.tanggal, t_invoice.mata_uang, sum(t_piutang_penjualan.bayar) AS terbayar, 'export' AS tipe
                    FROM t_invoice 
                    JOIN m_customer ON m_customer.cust_id = t_invoice.cust_id
                    LEFT JOIN t_piutang_penjualan ON t_piutang_penjualan.bill_reff = t_invoice.nomor
                    WHERE t_invoice.peb_tanggal IS NOT NULL AND t_invoice.peb_tanggal <= '$tgl' AND t_invoice.cancel_transaksi_id IS NULL AND piutang_active IS TRUE
                    GROUP BY t_invoice.cust_id,m_customer.cust_an_nama, t_invoice.nomor, t_invoice.tanggal, t_invoice.mata_uang
                    ORDER BY m_customer.cust_an_nama ASC, t_invoice.nomor ASC
					";
			$mods2 = \Yii::$app->db->createCommand($sql2)->queryAll();
            if(count($mods2)>0){
                $jmllokal = count($mods);
                foreach($mods2 as $i => $mod2){
                    $mods[ ($jmllokal+$i) ] = $mod2;
                }
            }
			$data['html'] = $this->renderPartial('_contentPiutang',['mods'=>$mods,'tgl'=>$tgl]);
			return $this->asJson($data);
		}
		return $this->render('index',['model'=>$model]);
	}
	
	public function actionPrintout(){
		$this->layout = '@views/layouts/metronic/print';
		$tgl = \Yii::$app->request->get('tgl');
		$sql = "SELECT t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode ,t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang, sum(t_piutang_penjualan.bayar) AS terbayar 
				FROM t_nota_penjualan 
				JOIN m_customer ON m_customer.cust_id = t_nota_penjualan.cust_id
				LEFT JOIN t_piutang_penjualan ON t_piutang_penjualan.bill_reff = t_nota_penjualan.kode
				WHERE t_nota_penjualan.tanggal <= '$tgl' AND t_nota_penjualan.cancel_transaksi_id IS NULL
				GROUP BY t_nota_penjualan.cust_id,m_customer.cust_an_nama, t_nota_penjualan.kode, t_nota_penjualan.tanggal, t_nota_penjualan.mata_uang
				ORDER BY m_customer.cust_an_nama ASC, t_nota_penjualan.tanggal ASC, t_nota_penjualan.kode ASC
				";
		$model = \Yii::$app->db->createCommand($sql)->queryAll();
		$caraprint = Yii::$app->request->get('caraprint');
		$paramprint['judul'] = Yii::t('app', 'LAPORAN PIUTANG CUSTOMER');
		$paramprint['judul2'] = Yii::t('app', 'Per Tanggal '.\app\components\DeltaFormatter::formatDateTimeForUser($tgl));
		if($caraprint == 'PRINT'){
			return $this->render('printout',['model'=>$model,'paramprint'=>$paramprint,'tgl'=>$tgl]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->render('printout',['model'=>$model,'paramprint'=>$paramprint,'tgl'=>$tgl]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->render('printout',['model'=>$model,'paramprint'=>$paramprint,'tgl'=>$tgl]);
		}
	}
	
}
