<?php

namespace app\modules\purchasinglog\controllers;

use Yii;
use app\controllers\DeltaBaseController;
use app\models\MKayu;
use app\models\TLogKontrak;

class LaporanController extends DeltaBaseController
{
	
	public function actionBiayaGrader(){
		$model = new \app\models\TBiayaGraderDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TBiayaGraderDetail'];
				$model->tgl_awal = $form_params['TBiayaGraderDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TBiayaGraderDetail']['tgl_akhir'];
				$model->biaya_grader_kode = $form_params['TBiayaGraderDetail']['biaya_grader_kode'];
				$model->status = $form_params['TBiayaGraderDetail']['status'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('biayaGrader/index',['model'=>$model]);
	}
	public function actionBiayaGraderPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TBiayaGraderDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TBiayaGraderDetail'];
		$model->tgl_awal = !empty($_GET['TBiayaGraderDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBiayaGraderDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TBiayaGraderDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TBiayaGraderDetail']['tgl_akhir']):"";
		$model->biaya_grader_kode = $_GET['TBiayaGraderDetail']['biaya_grader_kode'];
		$model->status = $_GET['TBiayaGraderDetail']['status'];
		$paramprint['judul'] = Yii::t('app', 'Laporan Biaya Grader');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/biayaGrader/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionKontraklog(){
		$model = new \app\models\TLogKontrak();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLogKontrak'];
				$model->tgl_awal = $form_params['TLogKontrak']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLogKontrak']['tgl_akhir'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('kontraklog/index',['model'=>$model]);
	}
	public function actionKontraklogPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLogKontrak();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLogKontrak'];
		$model->tgl_awal = !empty($_GET['TLogKontrak']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogKontrak']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLogKontrak']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLogKontrak']['tgl_akhir']):"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Kontrak Log');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/kontraklog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	
	public function actionMonitoringPembelianLog(){
		$model = new \app\models\TPengajuanPembelianlog();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TPengajuanPembelianlog'];
				$model->tgl_awal = $form_params['TPengajuanPembelianlog']['tgl_awal'];
				$model->tgl_akhir = $form_params['TPengajuanPembelianlog']['tgl_akhir'];
				$model->suplier_id = $form_params['TPengajuanPembelianlog']['suplier_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('monitoringPembelianLog/index',['model'=>$model]);
	}

	public function actionMonitoringPembelianLogPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TPengajuanPembelianlog();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TPengajuanPembelianlog'];
		$model->tgl_awal = !empty($_GET['TPengajuanPembelianlog']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanPembelianlog']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TPengajuanPembelianlog']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TPengajuanPembelianlog']['tgl_akhir']):"";
		$model->suplier_id = $_GET['TPengajuanPembelianlog']['suplier_id'];
		$paramprint['judul'] = Yii::t('app', 'Monitoring Pembelian Log');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/monitoringPembelianLog/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
	
	public function actionMonitoringPembelianLogDetail($id){
		if(\Yii::$app->request->isAjax){
			$model = \app\models\TPengajuanPembelianlog::findOne($id);
			$modMonitoring = \app\models\TMonitoringPembelianlog::find()->where("pengajuan_pembelianlog_id = ".$model->pengajuan_pembelianlog_id)->all();
			return $this->renderAjax('/laporan/monitoringPembelianLog/detailMonitoring',['model'=>$model,'modMonitoring'=>$modMonitoring]);
        }
    }

    public function actionLoglistDetail(){
		$model = new \app\models\TLoglistDetail();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLoglistDetail'];
				$model->tgl_awal = $form_params['TLoglistDetail']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLoglistDetail']['tgl_akhir'];
				$model->pihak1_perusahaan = $form_params['TLoglistDetail']['pihak1_perusahaan'];
				$model->log_kontrak_id = $form_params['TLoglistDetail']['log_kontrak_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanDt() ));
		}
		return $this->render('loglistDetail/index',['model'=>$model]);
	}
    
	public function actionLoglistDetailPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLoglistDetail();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLoglistDetail'];
		$model->tgl_awal = !empty($_GET['TLoglistDetail']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLoglistDetail']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglistDetail']['tgl_akhir']):"";
		$model->pihak1_perusahaan = !empty($_GET['TLoglistDetail']['pihak1_perusahaan'])?$_GET['TLoglistDetail']['pihak1_perusahaan']:"";
		$model->log_kontrak_id = !empty($_GET['TLoglistDetail']['log_kontrak_id'])?$_GET['TLoglistDetail']['log_kontrak_id']:"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Loglist');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if(!empty($model->nomor_produksi)){
			$paramprint['judul2'] .= "<br>No. Produksi " . $model->nomor_produksi;
		}
		if(!empty($model->nomor_batang)){
			$paramprint['judul2'] .= "<br>No. Batang " . $model->nomor_batang;
		}
		if(!empty($model->kayu_id)){
			$modKayu = MKayu::findOne($model->kayu_id);
			$paramprint['judul2'] .= "<br>Jenis Kayu " . $modKayu->kayu_nama;
		}
		if(!empty($model->volume_range)){
			$paramprint['judul2'] .= "<br>Diameter " . $model->volume_range;
		}
		if(!empty($model->is_freshcut)){
			$freshcut = $model->is_freshcut=='true'?"Fresh Cut":"Non Fresh Cut";
			$paramprint['judul2'] .= "<br>" . $freshcut;
		}
		if(!empty($model->pihak1_perusahaan)){
			$paramprint['judul2'] .= "<br>Nama Perusahaan " . $model->pihak1_perusahaan;
		}
		if(!empty($model->log_kontrak_id)){
			$modKontrak = TLogKontrak::findOne($model->log_kontrak_id);
			$paramprint['judul2'] .= "<br>No. Kontrak " . $modKontrak->nomor;
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/loglistDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/loglistDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/loglistDetail/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}

	public function actionSetNoKontrak(){
		$perusahaan = Yii::$app->request->post('perusahaan');
		$model = [];
		
		if($perusahaan){
			$model = TLogKontrak::find()->where(['pihak1_perusahaan'=>$perusahaan])->all();
		} else {
			$model = TLogKontrak::find()->all();
		}

		if($model){
			$arraymap = \yii\helpers\ArrayHelper::map($model, 'log_kontrak_id', 'nomor');
			$html = \yii\bootstrap\Html::tag('option', 'All', ['value' => '']);;
			foreach($arraymap as $i => $val){
				$html .= \yii\bootstrap\Html::tag('option',$val,['value'=>$i]);
			}
			$data['html']= $html;
			return $this->asJson($data);
		}
	}

	public function actionLoglist(){
		$model = new \app\models\TLoglist();
        if(\Yii::$app->request->get('dt')=='table-laporan'){
			if((\Yii::$app->request->get('laporan_params')) !== null){
				$form_params = []; parse_str(\Yii::$app->request->get('laporan_params'),$form_params); 
				$model->attributes = $form_params['TLoglist'];
				$model->tgl_awal = $form_params['TLoglist']['tgl_awal'];
				$model->tgl_akhir = $form_params['TLoglist']['tgl_akhir'];
				$model->kayu_id = $form_params['TLoglist']['kayu_id'];
				$model->volume_range = $form_params['TLoglist']['volume_range'];
				$model->pihak1_perusahaan = $form_params['TLoglist']['pihak1_perusahaan'];
				$model->log_kontrak_id = $form_params['TLoglist']['log_kontrak_id'];
			}
			return \yii\helpers\Json::encode(\app\components\SSP::complex( $model->searchLaporanRekapDt() ));
		}
		return $this->render('rekapLoglist/index',['model'=>$model]);
	}

	public function actionRekapLoglistPrint(){
		$this->layout = '@views/layouts/metronic/print';
		$model = new \app\models\TLoglist();
		$caraprint = Yii::$app->request->get('caraprint');
		$model->attributes = $_GET['TLoglist'];
		$model->tgl_awal = !empty($_GET['TLoglist']['tgl_awal'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglist']['tgl_awal']):"";
		$model->tgl_akhir = !empty($_GET['TLoglist']['tgl_akhir'])?\app\components\DeltaFormatter::formatDateTimeForDb($_GET['TLoglist']['tgl_akhir']):"";
		$model->kayu_id = !empty($_GET['TLoglist']['kayu_id'])?$_GET['TLoglist']['kayu_id']:"";
		$model->volume_range = !empty($_GET['TLoglist']['volume_range'])?$_GET['TLoglist']['volume_range']:"";
		$model->pihak1_perusahaan = !empty($_GET['TLoglist']['pihak1_perusahaan'])?$_GET['TLoglist']['pihak1_perusahaan']:"";
		$model->log_kontrak_id = !empty($_GET['TLoglist']['log_kontrak_id'])?$_GET['TLoglist']['log_kontrak_id']:"";
		$paramprint['judul'] = Yii::t('app', 'Laporan Rekap Loglist');
		if((!empty($model->tgl_awal)) && (!empty($model->tgl_akhir))){
			$paramprint['judul2'] = "Periode Tanggal ". \app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_awal)." sd ".\app\components\DeltaFormatter::formatDateTimeForUser($model->tgl_akhir);
		}
		if(!empty($model->kayu_id)){
			$modKayu = MKayu::findOne($model->kayu_id);
			$paramprint['judul2'] .= "<br>Jenis Kayu " . $modKayu->kayu_nama;
		}
		if(!empty($model->volume_range)){
			$paramprint['judul2'] .= "<br>Diameter " . $model->volume_range;
		}
		if(!empty($model->pihak1_perusahaan)){
			$paramprint['judul2'] .= "<br>Nama Perusahaan " . $model->pihak1_perusahaan;
		}
		if(!empty($model->log_kontrak_id)){
			$modKontrak = TLogKontrak::findOne($model->log_kontrak_id);
			$paramprint['judul2'] .= "<br>No. Kontrak " . $modKontrak->nomor;
		}
		if(!empty($model->tongkang)){
			$paramprint['judul2'] .= "<br>Nama Tongkang " . $model->tongkang;
		}

		if($caraprint == 'PRINT'){
			return $this->renderPartial('/laporan/rekapLoglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}else if($caraprint == 'PDF'){
			$pdf = Yii::$app->pdf;
			$pdf->options = ['title' => $paramprint['judul']];
			$pdf->filename = $paramprint['judul'].'.pdf';
			$pdf->methods['SetHeader'] = ['Generated By: '.Yii::$app->user->getIdentity()->userProfile->fullname.'||Generated At: ' . date('d/m/Y H:i:s')];
			$pdf->content = $this->renderPartial('/laporan/rekapLoglist/print',['model'=>$model,'paramprint'=>$paramprint]);
			return $pdf->render();
		}else if($caraprint == 'EXCEL'){
			return $this->renderPartial('/laporan/rekapLoglist/print',['model'=>$model,'paramprint'=>$paramprint]);
		}
	}
}
